Repository guildxyz/guild.xyz, pull requests merged in 2021-11, with the labels that each got.

#73 Halls & guilds - descriptions
  src/components/[group]/EditForm.tsx
  src/components/[guild]/EditForm.tsx
  src/components/common/Layout/Layout.tsx
  src/components/create/Description.tsx
  src/pages/[hall]/edit.tsx
  src/pages/[hall]/index.tsx
  src/pages/create-guild.tsx
  src/pages/create-hall.tsx
  src/pages/guild/[guild]/edit.tsx
  src/pages/guild/[guild]/index.tsx
  src/theme/components/input.ts
  src/theme/components/textarea.ts
Labels: feature

#76 Address management
  src/components/[guild]/JoinButton/components/JoinModal/hooks/useJoinPlatform.ts
  src/components/[guild]/JoinButton/components/JoinModal/hooks/useJoinSuccessToast.ts
  src/components/[guild]/hooks/useUser.ts
  src/components/common/Layout/components/Account/Account.tsx
  src/components/common/Layout/components/Account/components/AccountModal/AccountModal.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/LinkedAddress.tsx
  src/components/common/Layout/components/Account/components/AccountModal/hooks/useUpdateUser.ts
  src/temporaryData/types.ts
Labels: feature

#78 FormCard animations
  src/components/common/CardMotionWrapper.tsx
  src/components/common/ColorCard.tsx
  src/components/create-guild/Requirements/Requirements.tsx
  src/components/create-guild/Requirements/components/FormCard.tsx
  src/components/create-guild/Requirements/components/NftFormCard/NftFormCard.tsx
  src/components/create-guild/Requirements/components/PoapFormCard/PoapFormCard.tsx
  src/components/create-guild/Requirements/components/SnapshotFormCard/SnapshotFormCard.tsx
  src/components/create-guild/Requirements/components/TokenFormCard.tsx
  src/components/create-guild/Requirements/components/WhitelistFormCard.tsx
Labels: improvement

#68 Search & sort animations
  src/components/[guild]/JoinButton/hooks/useIsMember.ts
  src/components/common/CardMotionWrapper.tsx
  src/components/common/ExplorerCardMotionWrapper.tsx
  src/components/create-hall/GuildPicker/GuildPicker.tsx
  src/components/create-hall/GuildPicker/components/SelectableGuildCard.tsx
  src/components/index/CategorySection.tsx
  src/components/index/HallCard.tsx
  src/components/index/OrderSelect.tsx
  src/components/index/SearchBar.tsx
  src/components/index/hooks/useFilteredData.ts
  src/components/index/hooks/useOrder.ts
  src/components/index/hooks/useUsersHallsGuilds.ts
  src/components/index/hooks/useUsersHallsGuildsIds.ts
  src/pages/halls.tsx
  src/pages/index.tsx
Labels: improvement

#60 UI improvements
  src/components/[guild]/JoinButton/JoinButton.tsx
  src/components/[guild]/RequirementCard/RequirementCard.tsx
  src/components/[guild]/RequirementCard/components/RequirementText.tsx
  src/components/[guild]/RequirementCard/components/SnapshotStrategy.tsx
  src/components/[guild]/RequirementCard/components/Whitelist.tsx
  src/components/common/ColorButton.tsx
  src/components/common/ColorCard.tsx
  src/components/common/CtaButton.tsx
  src/components/common/EditButtonGroup.tsx
  src/components/common/Layout/Layout.tsx
  src/components/common/Layout/components/Header.tsx
  src/components/create-guild/Requirements/components/FormCard.tsx
  src/components/create-guild/Requirements/components/NftFormCard/NftFormCard.tsx
  src/components/create-guild/Requirements/components/PoapFormCard/PoapFormCard.tsx
  src/components/create-guild/Requirements/components/RequirementTypeText.tsx
  src/components/create-guild/Requirements/components/SnapshotFormCard/SnapshotFormCard.tsx
  src/components/create-guild/Requirements/components/TokenFormCard.tsx
  src/components/create-guild/Requirements/components/WhitelistFormCard.tsx
  src/components/create/SubmitButton.tsx
  src/pages/guild/[guild]/index.tsx
Labels: improvement

#81 React select - rendering menulist in a portal fix
  src/components/common/ChakraReactSelect/ChakraReactSelect.tsx
Labels: bug

#85 Multichain support
  package-lock.json
  package.json
  public/networkLogos/arbitrum.svg
  public/networkLogos/avalanche.svg
  public/networkLogos/celo.svg
  public/networkLogos/fantom.svg
  public/networkLogos/harmony.svg
  public/networkLogos/xdai.svg
  src/components/[guild]/RequirementCard/RequirementCard.tsx
  src/components/[guild]/RequirementCard/components/Token.tsx
  src/components/[guild]/RequirementCard/hooks/useTokenImage.ts
  src/components/[hall]/CustomizationButton/hooks/useEdit.ts
  src/components/common/ChakraReactSelect/AsyncCreatableSelect.tsx
  src/components/common/ChakraReactSelect/AsyncSelect.tsx
  src/components/common/ChakraReactSelect/ChakraReactSelect.tsx
  src/components/common/ChakraReactSelect/CreatableSelect.tsx
  src/components/common/ChakraReactSelect/CustomSelectOption.tsx
  src/components/common/ChakraReactSelect/Select.tsx
  src/components/common/ChakraReactSelect/index.ts
  src/components/common/ChakraReactSelect/types.ts
  src/components/common/Layout/components/Account/Account.tsx
  src/components/common/Layout/components/Account/components/AccountButton.tsx
  src/components/common/Layout/components/Account/components/AccountCard.tsx
  src/components/common/Layout/components/Account/components/NetworkModal/NetworkModal.tsx
  src/components/common/Layout/components/Account/components/NetworkModal/components/NetworkButton/NetworkButton.tsx
  src/components/common/utils/guildJsonReplacer.ts
  src/components/create-guild/Requirements/Requirements.tsx
  src/components/create-guild/Requirements/components/ChainPicker.tsx
  src/components/create-guild/Requirements/components/FormCard.tsx
  src/components/create-guild/Requirements/components/NftFormCard/NftFormCard.tsx
  src/components/create-guild/Requirements/components/PoapFormCard/PoapFormCard.tsx
  src/components/create-guild/Requirements/components/RequirementChainTypeText.tsx
  src/components/create-guild/Requirements/components/RequirementTypeText.tsx
  src/components/create-guild/Requirements/components/SnapshotFormCard/SnapshotFormCard.tsx
  src/components/create-guild/Requirements/components/Symbol.tsx
  src/components/create-guild/Requirements/components/TokenFormCard.tsx
  src/components/create-guild/Requirements/components/WhitelistFormCard.tsx
  src/components/create/hooks/useCreate.ts
  src/connectors.ts
  src/hooks/useTokenData.ts
  src/hooks/useTokens.ts
  src/pages/[hall]/index.tsx
  src/pages/guild/[guild]/edit.tsx
  src/pages/guild/[guild]/index.tsx
  src/temporaryData/guilds.ts
  src/temporaryData/types.ts
  src/theme/styles.ts
Labels: feature

#92 Create guild - form fixes
  package-lock.json
  package.json
  src/components/[guild]/RequirementCard/RequirementCard.tsx
  src/components/[hall]/hooks/useHallWithSortedGuilds.ts
  src/components/common/utils/guildJsonReplacer.ts
  src/components/create-guild/Requirements/Requirements.tsx
  src/components/create-guild/Requirements/components/ChainPicker.tsx
  src/components/create-guild/Requirements/components/MirrorFormCard/MirrorFormCard.tsx
  src/components/create-guild/Requirements/components/NftFormCard/NftFormCard.tsx
  src/components/create-guild/Requirements/components/PoapFormCard/PoapFormCard.tsx
  src/components/create-guild/Requirements/components/SnapshotFormCard/SnapshotFormCard.tsx
  src/components/create-guild/Requirements/components/TokenFormCard.tsx
  src/components/create-guild/Requirements/components/WhitelistFormCard.tsx
  src/components/create/hooks/useCreate.ts
  src/connectors.ts
  src/pages/create-guild.tsx
  src/temporaryData/types.ts
Labels: bug, improvement

#87 New guild API endpoints for fetching NFT data
  .env
  src/components/create-guild/Requirements/components/NftFormCard/NftFormCard.tsx
  src/components/create-guild/Requirements/components/NftFormCard/hooks/useNftMetadata.ts
  src/components/create-guild/Requirements/components/NftFormCard/hooks/useNfts.ts
  src/components/create-guild/Requirements/components/NftFormCard/hooks/useOpenseaNft.ts
  src/pages/api/metadata/[nftslug].ts
  src/pages/api/nfts.ts
  src/pages/api/opensea/[address].ts
Labels: improvement
