Repository guildxyz/guild.xyz, pull requests merged in 2021-09, with the labels that each got.

#8 Only render guilds by urlName
  src/pages/[guild].tsx
Labels: invalid

#6 Token search with custom select
  src/components/[guild]/RequirementCard/RequirementCard.tsx
  src/components/common/ChakraReactSelect/ChakraReactSelect.tsx
  src/components/create-guild/NftFormCard/NftFormCard.tsx
  src/components/create-guild/NftFormCard/hooks/useMetadata.ts
  src/components/create-guild/NftFormCard/hooks/useNftsList.ts
  src/components/create-guild/TokenFormCard/TokenFormCard.tsx
  src/components/create-guild/TokenFormCard/hooks/useTokensList.ts
  src/components/create-guild/hooks/useNftCustomAttributeNames.ts
  src/components/create-guild/hooks/useNftCustomAttributeValues.ts
  src/components/create-guild/hooks/useSubmitMachine.ts
  src/hooks/useTokenData.ts
  src/pages/api/metadata/[nft].ts
  src/pages/api/nfts.ts
  src/pages/create-guild.tsx
  src/temporaryData/types.ts
Labels: enhancement

#11 Logic (for requirements)
  public/logicIcons/and.svg
  public/logicIcons/nand.svg
  public/logicIcons/nor.svg
  public/logicIcons/or.svg
  src/components/[guild]/LogicDivider.tsx
  src/components/create-guild/LogicIcon.tsx
  src/components/create-guild/LogicPicker.tsx
  src/components/create-guild/NftFormCard/NftFormCard.tsx
  src/components/create-guild/hooks/useSubmitMachine.ts
  src/pages/[guild].tsx
  src/pages/create-guild.tsx
  src/temporaryData/types.ts
Labels: enhancement

#12 UI improvements
  public/logo.svg
  src/components/[guild]/Members/Member.tsx
  src/components/[guild]/Members/Members.tsx
  src/components/common/GuildAvatar.tsx
  src/components/common/Layout/Layout.tsx
  src/components/common/Layout/components/Account/Account.tsx
  src/components/common/Layout/components/Account/components/AccountModal/AccountModal.tsx
  src/components/common/Section.tsx
  src/components/index/CategorySection.tsx
  src/components/index/GuildCard/GuildCard.tsx
  src/pages/[guild].tsx
  src/pages/index.tsx
Labels: enhancement

#14 Create guild page improvements
  next.config.js
  package-lock.json
  package.json
  src/components/create-guild/GuildNameAndIcon.tsx
  src/components/create-guild/IconSelector/IconSelector.tsx
  src/components/create-guild/LogicPicker.tsx
  src/components/create-guild/LogicPicker/LogicPicker.tsx
  src/components/create-guild/LogicPicker/components/LogicOption.tsx
  src/components/create-guild/LogicPicker/index.ts
  src/components/create-guild/PickGuildPlatform/components/CustomDiscord/CustomDiscord.tsx
  src/components/create-guild/PickGuildPlatform/components/CustomDiscord/hooks/useServerData.ts
  src/components/create-guild/PickGuildPlatform/components/PlatformOption.tsx
  src/pages/create-guild.tsx
  src/static/logicIcons/and.svg
  src/static/logicIcons/nand.svg
  src/static/logicIcons/nor.svg
  src/static/logicIcons/or.svg
Labels: enhancement

#9 Strategies
  src/components/[guild]/RequirementCard/RequirementCard.tsx
  src/components/create-guild/NftFormCard/hooks/useNftsList.ts
  src/components/create-guild/SnapshotFormCard/SnapshotFormCard.tsx
  src/components/create-guild/SnapshotFormCard/hooks/useSnapshotsList.ts
  src/components/create-guild/SnapshotFormCard/hooks/useStrategyParamsArray.ts
  src/components/create-guild/SnapshotFormCard/index.ts
  src/components/index/GuildCard/GuildCard.tsx
  src/pages/api/strategies.ts
  src/pages/create-guild.tsx
  src/temporaryData/types.ts
Labels: enhancement

#21 Snapshot strategy text & link on RequirementCard
  src/components/[guild]/RequirementCard/RequirementCard.tsx
  src/components/[guild]/RequirementCard/components/CopyableAddress.tsx
  src/components/[guild]/RequirementCard/components/StrategyParams.tsx
  src/components/common/Layout/components/Account/components/AccountModal/AccountModal.tsx
  src/temporaryData/types.ts
Labels: feature, prio 2
