Repository guildxyz/guild.xyz, pull requests merged in 2022-11, with the labels that each got.

#537 kycDAO integration
  public/requirementLogos/kycdao.svg
  src/components/[guild]/Requirements/Requirements.tsx
  src/components/[guild]/Requirements/components/KycDAORequirementCard.tsx
  src/components/create-guild/Requirements/SetRequirements.tsx
  src/components/create-guild/Requirements/components/AddRequirementCard.tsx
  src/components/create-guild/Requirements/components/FormCard.tsx
  src/components/create-guild/Requirements/components/KycDAOFormCard/KycDAOFormCard.tsx
  src/components/create-guild/Requirements/components/KycDAOFormCard/hooks/useKycDAOContracts.ts
  src/components/create-guild/Requirements/components/KycDAOFormCard/index.ts
  src/types.ts
Labels: feature

#561 CSRF handling in main window
  src/components/[guild]/JoinModal/hooks/useOauthPopupWindow.ts
  src/pages/oauth.tsx
Labels: bug, improvement

#542 Add Arb Nova Chain
  public/networkLogos/nova.svg
  src/connectors/index.ts
Labels: waiting for BE

#565 Arbitrum Nova, Boba Avax & Moonbeam support
  public/networkLogos/moonbeam.svg
  public/networkLogos/nova.svg
  src/components/common/Layout/components/Account/components/NetworkModal/utils/requestNetworkChange.ts
  src/components/create-guild/Requirements/components/ChainPicker.tsx
  src/connectors/index.ts
  src/hooks/useTokens.ts
  src/types.ts
Labels: feature, waiting for BE

#524 useMemo cleanup
  src/components/[guild]/CreatePoap/components/Distribution/components/SendDiscordEmbed/SendDiscordEmbed.tsx
  src/components/[guild]/CreatePoap/components/PoapListItem/PoapListItem.tsx
  src/components/[guild]/CreatePoap/components/Requirements/components/MonetizePoap/components/TokenPicker.tsx
  src/components/[guild]/Members/Members.tsx
  src/components/[guild]/Requirements/components/NftRequirementCard.tsx
  src/components/[guild]/RolePlatforms/components/PlatformCard/components/useDiscordCardProps/DiscordCardSettings/components/ChannelsToGate/components/Category.tsx
  src/components/common/Layout/components/NavMenu/hooks/useUpvoty.ts
  src/components/create-guild/Requirements/components/ChainPicker.tsx
  src/components/create-guild/Requirements/components/JuiceboxFormCard/JuiceboxFormCard.tsx
  src/components/create-guild/Requirements/components/NftFormCard/NftFormCard.tsx
  src/components/create-guild/Requirements/components/PoapFormCard/PoapFormCard.tsx
  src/components/create-guild/Requirements/components/TokenFormCard.tsx
  src/components/create-guild/Requirements/components/UnlockFormCard/UnlockFormCard.tsx
Labels: improvement

#572 Otterspace integration - multichain support
  src/components/[guild]/Requirements/components/OtterspaceRequirementCard.tsx
  src/components/create-guild/Requirements/components/ChainPicker.tsx
  src/components/create-guild/Requirements/components/OtterspaceFormCard/OtterspaceFormCard.tsx
  src/components/create-guild/Requirements/components/OtterspaceFormCard/hooks/useOtterspaceBadges.ts
Labels: feature, improvement

#568 Contract state - proxy support
  src/components/create-guild/Requirements/components/ContractStateFormCard/hooks/useAbi.ts
Labels: feature, improvement

#563 Guild Roles as requirements
  public/requirementLogos/guild.png
  src/components/[guild]/Requirements/components/GuildAdminRequirementCard.tsx
  src/components/[guild]/Requirements/components/GuildMinGuildsRequirementCard.tsx
  src/components/[guild]/Requirements/components/GuildRoleRequirementCard.tsx
  src/components/[guild]/Requirements/components/GuildUserSinceRequirementCard.tsx
  src/components/[guild]/Requirements/requirementCards.ts
  src/components/[guild]/RoleCard/components/AccessIndicator/AccessIndicator.tsx
  src/components/create-guild/Requirements/components/AddRequirement.tsx
  src/components/create-guild/Requirements/components/DiscordFormCard/DiscordFormCard.tsx
  src/components/create-guild/Requirements/components/GuildFormCard/GuildFormCard.tsx
  src/components/create-guild/Requirements/components/GuildFormCard/components/GuildAdmin.tsx
  src/components/create-guild/Requirements/components/GuildFormCard/components/MinAmountInput.tsx
  src/components/create-guild/Requirements/components/GuildFormCard/components/MinGuilds.tsx
  src/components/create-guild/Requirements/components/GuildFormCard/components/Role.tsx
  src/components/create-guild/Requirements/components/GuildFormCard/components/UserSince.tsx
  src/components/create-guild/Requirements/components/GuildFormCard/hooks/useGuilds.ts
  src/components/create-guild/Requirements/components/GuildFormCard/index.ts
  src/components/create-guild/Requirements/formCards.ts
  src/types.ts
Labels: feature

#573 ThemeContext rework
  src/components/[guild]/ThemeContext.tsx
Labels: bug

#576 Sismo badge integration
  public/requirementLogos/sismo.svg
  src/components/create-guild/Requirements/components/AddRequirement.tsx
  src/requirements/Sismo/SismoForm.tsx
  src/requirements/Sismo/SismoRequirement.tsx
  src/requirements/Sismo/hooks/useSismoBadges.ts
  src/requirements/common/Requirement.tsx
  src/requirements/requirements.ts
Labels: feature

#590 Guild landing - webp images
  public/landing/composable-membership-requirements-icons.png
  public/landing/composable-membership-requirements-icons.webp
  public/landing/composable-membership-requirements.png
  public/landing/composable-membership-requirements.webp
  public/landing/daomasters-guild-tutorial.jpg
  public/landing/discover/guild-cryptonary.webp
  public/landing/discover/guild-daily-nft-show.webp
  public/landing/discover/guild-daomasters.webp
  public/landing/discover/guild-delphidigital.webp
  public/landing/discover/guild-mirror.webp
  public/landing/discover/guild-twitter.webp
  public/landing/guild-guard.png
  public/landing/guild-guard.webp
  public/landing/platform-agnostic-communities.png
  public/landing/platform-agnostic-communities.webp
  public/landing/real-time-query-engine.png
  public/landing/real-time-query-engine.webp
  public/landing/reka-eth.png
  public/landing/reka-eth.webp
  public/landing/token-based-membership.png
  public/landing/token-based-membership.webp
  src/components/index/ComposableRequirements.tsx
  src/components/index/Discover.tsx
  src/components/index/GuardAgainstPhishingAttack.tsx
  src/components/index/PlatformAgnosticCommunities.tsx
  src/components/index/RealTimeQueryEngine.tsx
  src/components/index/TokenBasedMembership.tsx
Labels: improvement

#584 Lens integration upgrade
  src/requirements/Lens/LensForm.tsx
  src/requirements/Lens/LensRequirement.tsx
  src/requirements/requirements.ts
Labels: feature, improvement

#592 POAP payment flow improvements
  src/components/[guild]/CreatePoap/hooks/usePoapLinks.ts
  src/components/[guild]/claim-poap/components/ClaimModal/ClaimModal.tsx
  src/components/[guild]/claim-poap/hooks/usePayFee.ts
  src/pages/[guild]/claim-poap/[fancyId].tsx
  src/pages/api/poap/can-claim/[poapId].ts
Labels: improvement
