Repository guildxyz/guild.xyz, pull requests merged in 2022-07, with the labels that each got.

#402 Gnosis Safe signature support
  package-lock.json
  package.json
  src/components/[guild]/AddRoleButton/AddRoleButton.tsx
  src/components/[guild]/CreatePoap/components/SetupBot/SetupBot.tsx
  src/components/[guild]/EditGuild/EditGuild.tsx
  src/components/[guild]/EditGuild/components/Admins/Admins.tsx
  src/components/[guild]/EditGuild/components/DeleteGuildButton/DeleteGuildButton.tsx
  src/components/[guild]/Onboarding/components/SummonMembers/SummonMembers.tsx
  src/components/[guild]/RolesByPlatform/components/JoinButton/components/JoinModal/JoinDiscordModal.tsx
  src/components/[guild]/RolesByPlatform/components/JoinButton/components/JoinModal/JoinModal.tsx
  src/components/[guild]/RolesByPlatform/components/JoinButton/components/JoinModal/JoinTelegramModal.tsx
  src/components/[guild]/RolesByPlatform/components/RoleListItem/components/EditRole/EditRole.tsx
  src/components/[guild]/RolesByPlatform/components/RoleListItem/components/EditRole/components/DeleteRoleButton/DeleteRoleButton.tsx
  src/components/[guild]/hooks/useGuild.ts
  src/components/[guild]/hooks/useUser.ts
  src/components/common/Layout/components/Account/components/AccountModal/components/AccountConnections.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/LinkedAddress.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/LinkedSocialAccount.tsx
  src/components/create-guild/Requirements/components/AllowlistFormCard.tsx
  src/components/guard/setup/ServerSetupCard/ServerSetupCard.tsx
  src/connectors/index.ts
  src/hooks/useSubmit/index.ts
  src/hooks/useSubmit/useSubmit.ts
  src/hooks/useSubmit/utils/getFixedTimestamp.ts
  src/hooks/useSubmit/utils/gnosisSafeSignCallback.ts
  src/hooks/useSubmitWithUpload.ts
  src/pages/create-guild/telegram.tsx
  src/static/abis/gnosisSafeL2.json
  src/static/abis/gnosisSignMessageLib.json
  src/types.ts
Labels: feature

#404 fix: Guild page - using AnimateSharedLayout
  src/pages/[guild]/index.tsx
Labels: bug

#384 POAP monetization
  next.config.js
  package-lock.json
  package.json
  public/img/gnosis-safe-green.svg
  public/img/gnosis-safe-white.svg
  src/components/[guild]/CreatePoap/CreatePoap.tsx
  src/components/[guild]/CreatePoap/components/CreatePoapContext.tsx
  src/components/[guild]/CreatePoap/components/CreatePoapForm.tsx
  src/components/[guild]/CreatePoap/components/CreatePoapSuccess.tsx
  src/components/[guild]/CreatePoap/components/MonetizePoap/MonetizePoap.tsx
  src/components/[guild]/CreatePoap/components/MonetizePoap/gnosisAPiUrls.ts
  src/components/[guild]/CreatePoap/components/MonetizePoap/hooks/useIsGnosisSafe.ts
  src/components/[guild]/CreatePoap/components/MonetizePoap/hooks/useRegisterVault.ts
  src/components/[guild]/CreatePoap/components/MonetizePoap/hooks/useUsersGnosisSafes.ts
  src/components/[guild]/CreatePoap/components/MonetizePoap/index.ts
  src/components/[guild]/CreatePoap/components/PoapListItem.tsx
  src/components/[guild]/CreatePoap/components/PoapListItem/PoapListItem.tsx
  src/components/[guild]/CreatePoap/components/PoapListItem/hooks/useGetVault.ts
  src/components/[guild]/CreatePoap/components/PoapListItem/hooks/useWithdraw.ts
  src/components/[guild]/CreatePoap/components/PoapListItem/index.ts
  src/components/[guild]/CreatePoap/components/SetupBot/SetupBot.tsx
  src/components/[guild]/CreatePoap/components/UploadMintLinks.tsx
  src/components/[guild]/CreatePoap/hooks/useCreatePoap.ts
  src/components/[guild]/CreatePoap/hooks/usePoapLinks.ts
  src/components/[guild]/CreatePoap/hooks/usePoapVault.ts
  src/components/[guild]/CreatePoap/hooks/useSavePoap.ts
  src/components/[guild]/GuildMenu/GuildMenu.tsx
  src/components/[guild]/claim-poap/hooks/useClaimPoap.ts
  src/components/[guild]/claim-poap/hooks/useHasPaid.ts
  src/components/[guild]/claim-poap/hooks/usePayFee.ts
  src/components/[guild]/claim-poap/hooks/useUsersTokenBalance.ts
  src/components/_app/Web3ConnectionManager/Web3ConnectionManager.tsx
  src/components/common/Layout/components/Account/components/NetworkModal/NetworkModal.tsx
  src/components/create-guild/hooks/useCreateRole.tsx
  src/hooks/useCoinBalance.ts
  src/hooks/useContract.ts
  src/hooks/useFeeCollectorContract.ts
  src/pages/[guild]/claim-poap/[fancyId].tsx
  src/static/abis/erc20Abi.json
  src/static/abis/feeCollectorAbi.json
  src/types.ts
Labels: feature

#372 SSG optimization
  src/pages/[guild]/index.tsx
Labels: improvement

#395 Telegram authentication
  src/components/[guild]/RolesByPlatform/components/JoinButton/components/JoinModal/JoinDiscordModal.tsx
  src/components/[guild]/RolesByPlatform/components/JoinButton/components/JoinModal/JoinTelegramModal.tsx
  src/components/[guild]/RolesByPlatform/components/JoinButton/components/JoinModal/hooks/useTGAuth.ts
Labels: feature

#411 POAP monetization improvements
  src/components/[guild]/CreatePoap/components/CreatePoapContext.tsx
  src/components/[guild]/CreatePoap/components/CreatePoapForm.tsx
  src/components/[guild]/CreatePoap/components/MonetizePoap/MonetizePoap.tsx
  src/components/[guild]/CreatePoap/components/MonetizePoap/components/TokenPicker.tsx
  src/components/[guild]/CreatePoap/components/MonetizePoap/hooks/useCoinById.ts
  src/components/[guild]/CreatePoap/components/MonetizePoap/hooks/useFeeInUSD.ts
  src/components/[guild]/CreatePoap/components/MonetizePoap/hooks/useIsGnosisSafe.ts
  src/components/[guild]/CreatePoap/components/MonetizePoap/hooks/useUsersGnosisSafes.ts
  src/components/[guild]/CreatePoap/components/PoapListItem/PoapListItem.tsx
  src/components/[guild]/CreatePoap/hooks/usePoapVault.ts
  src/components/[guild]/claim-poap/hooks/usePayFee.ts
  src/components/_app/Web3ConnectionManager/Web3ConnectionManager.tsx
  src/components/common/Layout/components/Account/components/NetworkModal/NetworkModal.tsx
  src/components/common/Layout/components/Account/components/NetworkModal/components/NetworkButton.tsx
  src/components/common/Layout/components/Account/components/NetworkModal/components/NetworkButton/index.ts
  src/components/common/Layout/components/Account/components/NetworkModal/components/NetworkButtonsList.tsx
  src/components/common/StyledSelect/StyledSelect.tsx
  src/hooks/useFeeCollectorContract.ts
  src/pages/[guild]/claim-poap/[fancyId].tsx
  src/static/abis/feeCollectorAbi.json
  src/types.ts
Labels: improvement

#415 POAP monetization - multichain fixes
  src/components/[guild]/CreatePoap/components/CreatePoapContext.tsx
  src/components/[guild]/CreatePoap/components/MonetizePoap/MonetizePoap.tsx
  src/components/[guild]/CreatePoap/components/PoapListItem/PoapListItem.tsx
  src/components/[guild]/CreatePoap/components/PoapListItem/hooks/useGetVault.ts
  src/components/[guild]/CreatePoap/hooks/usePoapVault.ts
  src/components/[guild]/claim-poap/hooks/useHasPaid.ts
  src/components/[guild]/claim-poap/hooks/usePayFee.ts
  src/components/common/Layout/components/Account/components/NetworkModal/components/NetworkButton.tsx
  src/components/common/Layout/components/Account/components/NetworkModal/components/NetworkButtonsList.tsx
  src/components/common/Layout/components/Account/components/NetworkModal/utils/requestNetworkChange.ts
  src/connectors/index.ts
  src/pages/[guild]/claim-poap/[fancyId].tsx
  src/pages/api/get-poap-vault.ts
  src/pages/api/get-vault.ts
  src/types.ts
Labels: bug, improvement

#420 NftFormCard: add key-value inputs for Polygon NFTs
  src/components/create-guild/Requirements/components/NftFormCard/NftFormCard.tsx
Labels: feature

#422 Google integration
  .env
  public/platforms/google.png
  public/platforms/google_bg.png
  public/videos/google-config-guide.webm
  src/components/[guild]/AccessHub/AccessHub.tsx
  src/components/[guild]/RolePlatforms/RolePlatforms.tsx
  src/components/[guild]/RolePlatforms/components/AddPlatformButton/AddPlatformButton.tsx
  src/components/[guild]/RolePlatforms/components/AddPlatformButton/components/AddGooglePanel.tsx
  src/components/[guild]/RolePlatforms/components/PlatformCard/PlatformCard.tsx
  src/components/[guild]/RolePlatforms/components/PlatformCard/components/DiscordCard/DiscordCard.tsx
  src/components/[guild]/RolePlatforms/components/PlatformCard/components/GoogleCard.tsx
  src/components/[guild]/RolePlatforms/components/PlatformCard/components/TelegramCard.tsx
  src/components/[guild]/RolesByPlatform/components/JoinButton/components/JoinModal/JoinModal.tsx
  src/components/[guild]/RolesByPlatform/components/JoinButton/components/JoinModal/components/GoogleAuthButton.tsx
  src/components/[guild]/RolesByPlatform/components/JoinButton/components/JoinModal/hooks/useConnect.ts
  src/components/[guild]/RolesByPlatform/components/JoinButton/components/JoinModal/hooks/useGoogleAuth.ts
  src/components/[guild]/RolesByPlatform/components/JoinButton/components/JoinModal/hooks/useGoogleAuthWithCallback.ts
  src/components/[guild]/RolesByPlatform/components/JoinButton/components/JoinModal/hooks/useJoin.ts
  src/components/common/GoogleGuildSetup/GoogleGuildSetup.tsx
  src/components/common/GoogleGuildSetup/components/GoogleDocCard.tsx
  src/components/common/GoogleGuildSetup/components/GoogleDocSetupCard.tsx
  src/components/common/GoogleGuildSetup/hooks/useGoogleGateables.ts
  src/components/common/GoogleGuildSetup/index.ts
  src/components/common/Layout/components/Account/components/AccountModal/components/LinkedSocialAccount.tsx
  src/components/create-guild/PlatformsGrid/PlatformsGrid.tsx
  src/components/create-guild/PlatformsGrid/components/GoogleSelectButton.tsx
  src/components/create-guild/PlatformsGrid/components/TelegramSelectButton.tsx
  src/pages/create-guild/google.tsx
  src/pages/googleauth.tsx
  src/types.ts
Labels: feature
