Repository guildxyz/guild.xyz, pull requests merged in 2022-01, with the labels that each got.

#126 Requirement chain indicator UI fix
  src/components/[guild]/RequirementCard/RequirementCard.tsx
  src/components/create-guild/Requirements/components/RequirementChainTypeText.tsx
Labels: bug, prio 1

#127 Fixed whitelist textarea validation
  src/components/create-guild/Requirements/components/WhitelistFormCard.tsx
Labels: bug, prio 2

#128 FormErrorMessage - collapse transition
  src/components/[guild]/EditButtonGroup/components/CustomizationButton/components/BackgroundImageUploader.tsx
  src/components/[guild]/EditButtonGroup/components/CustomizationButton/components/ColorModePicker.tsx
  src/components/[guild]/EditButtonGroup/components/CustomizationButton/components/ColorPicker.tsx
  src/components/common/FormErrorMessage.tsx
  src/components/create-guild/IconSelector/components/PhotoUploader.tsx
  src/components/create-guild/LogicPicker/LogicPicker.tsx
  src/components/create-guild/NameAndIcon.tsx
  src/components/create-guild/PickRolePlatform/PickRolePlatform.tsx
  src/components/create-guild/PickRolePlatform/components/CustomDiscord/CustomDiscord.tsx
  src/components/create-guild/Requirements/components/JuiceboxFormCard/JuiceboxFormCard.tsx
  src/components/create-guild/Requirements/components/MirrorFormCard/MirrorFormCard.tsx
  src/components/create-guild/Requirements/components/NftFormCard/NftFormCard.tsx
  src/components/create-guild/Requirements/components/PoapFormCard/PoapFormCard.tsx
  src/components/create-guild/Requirements/components/SnapshotFormCard/SnapshotFormCard.tsx
  src/components/create-guild/Requirements/components/TokenFormCard.tsx
  src/components/create-guild/Requirements/components/UnlockFormCard/UnlockFormCard.tsx
  src/components/create-guild/Requirements/components/WhitelistFormCard.tsx
Labels: improvement, prio 3

#101 SnapshotFormCard fixes
  src/components/create-guild/Requirements/Requirements.tsx
  src/components/create-guild/Requirements/components/SnapshotFormCard/SnapshotFormCard.tsx
  src/components/create-guild/Requirements/components/SnapshotFormCard/hooks/useSnapshots.ts
  src/pages/api/strategies.ts
  src/utils/preprocessRequirements.ts
Labels: bug, improvement

#103 Token & NFT form cards - fetching on address paste
  src/components/create-guild/Requirements/components/NftFormCard/NftFormCard.tsx
  src/components/create-guild/Requirements/components/TokenFormCard.tsx
  src/components/create-guild/Requirements/components/UnlockFormCard/UnlockFormCard.tsx
Labels: improvement

#130 Fix first time appearance customization
  src/components/[guild]/EditButtonGroup/components/CustomizationButton/components/ColorPicker.tsx
  src/components/[guild]/ThemeContext.tsx
Labels: bug, prio 3

#131 Fix crash on switching to an unsupported chain
  package-lock.json
  package.json
Labels: bug, prio 3

#135 Image optimization
  src/components/[guild]/RolesByPlatform/components/RoleListItem/RoleListItem.tsx
  src/components/common/DisplayCard.tsx
  src/components/common/GuildLogo.tsx
  src/components/common/Layout/Layout.tsx
  src/components/create-guild/IconSelector/components/PhotoUploader.tsx
Labels: improvement

#152 Fix machine warnings
  next-env.d.ts
  src/hooks/useSubmit/useSubmit.ts
Labels: bug

#138 Telegram group integration
  src/components/[guild]/EditButtonGroup/components/AddRoleButton.tsx
  src/components/[guild]/RolesByPlatform/RolesByPlatform.tsx
  src/components/[guild]/RolesByPlatform/components/JoinButton/JoinButton.tsx
  src/components/[guild]/RolesByPlatform/components/JoinButton/components/JoinModal/JoinTelegramModal.tsx
  src/components/[guild]/RolesByPlatform/components/JoinButton/platformsContent.ts
  src/components/create-guild/PickRolePlatform/PickRolePlatform.tsx
  src/components/create-guild/PickRolePlatform/components/CustomDiscord/CustomDiscord.tsx
  src/components/create-guild/PickRolePlatform/components/OfficialDiscord.tsx
  src/components/create-guild/PickRolePlatform/components/TelegramGroup/TelegramGroup.tsx
  src/components/create-guild/PickRolePlatform/components/TelegramGroup/hooks/useIsTGBotIn.ts
  src/components/create-guild/PickRolePlatform/components/TelegramGroup/index.ts
  src/components/create-guild/hooks/useCreate.ts
Labels: feature

#154 Platform ID validation hotfix
  src/components/create-guild/PickRolePlatform/components/CustomDiscord/CustomDiscord.tsx
  src/components/create-guild/PickRolePlatform/components/OfficialDiscord.tsx
  src/components/create-guild/PickRolePlatform/components/TelegramGroup/TelegramGroup.tsx
  src/components/create-guild/hooks/useCreate.ts
Labels: bug

#134 Dynamic link preview images
  next-env.d.ts
  package-lock.json
  package.json
  src/components/common/LinkPreviewHead.tsx
  src/pages/[guild]/index.tsx
  src/pages/[guild]/linkpreview.tsx
  src/pages/_document.tsx
  src/pages/api/linkpreview/[[...urlName]].ts
  src/pages/index.tsx
  src/pages/linkpreview.tsx
  tsconfig.json
Labels: feature, prio 3

#144 Guild name - check availability on blur
  src/components/create-guild/NameAndIcon.tsx
Labels: improvement

#132 Using LazyMotion
  src/components/common/CardMotionWrapper.tsx
  src/components/common/ErrorAnimation.tsx
  src/components/create-guild/Requirements/components/WhitelistFormCard.tsx
Labels: improvement

#149 Common Alert component
  src/components/[guild]/EditButtonGroup/components/CustomizationButton/CustomizationButton.tsx
  src/components/[guild]/RolesByPlatform/components/JoinButton/components/JoinModal/JoinDiscordModal.tsx
  src/components/[guild]/edit/[role]/DeleteRoleCard/DeleteRoleCard.tsx
  src/components/[guild]/edit/index/DeleteGuildCard/DeleteGuildCard.tsx
  src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx
  src/components/common/DiscardAlert.tsx
  src/components/common/Layout/components/Account/components/AccountModal/AccountModal.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/LinkedAddress.tsx
  src/components/common/Layout/components/Account/components/NetworkModal/NetworkModal.tsx
  src/components/common/Modal.tsx
  src/components/create-guild/IconSelector/IconSelector.tsx
Labels: improvement

#156 Added Goerli support
  src/connectors.ts
  src/hooks/useTokens.ts
Labels: feature

#150 New header design & delete button on drawers
  src/components/[guild]/DeleteButton.tsx
  src/components/[guild]/EditButtonGroup/components/AddRoleButton.tsx
  src/components/[guild]/EditButtonGroup/components/EditGuildButton.tsx
  src/components/[guild]/RolesByPlatform/components/RoleListItem/components/EditRole.tsx
  src/components/[guild]/edit/[role]/DeleteRoleButton/DeleteRoleButton.tsx
  src/components/[guild]/edit/[role]/DeleteRoleButton/hooks/useDeleteRole.ts
  src/components/[guild]/edit/[role]/DeleteRoleButton/index.ts
  src/components/[guild]/edit/[role]/DeleteRoleCard/DeleteRoleCard.tsx
  src/components/[guild]/edit/[role]/DeleteRoleCard/index.ts
  src/components/[guild]/edit/index/DeleteGuildButton/DeleteGuildButton.tsx
  src/components/[guild]/edit/index/DeleteGuildButton/hooks/useDeleteGuild.ts
  src/components/[guild]/edit/index/DeleteGuildButton/index.ts
  src/components/[guild]/edit/index/DeleteGuildCard/DeleteGuildCard.tsx
  src/components/[guild]/edit/index/DeleteGuildCard/index.ts
  src/components/common/DrawerHeader.tsx
  src/components/common/Section.tsx
  src/components/create-guild/NameAndIcon.tsx
Labels: improvement

#160 refact: create-guild platformId cleanup
  src/components/create-guild/PickRolePlatform/components/CustomDiscord/CustomDiscord.tsx
  src/components/create-guild/PickRolePlatform/components/OfficialDiscord.tsx
  src/components/create-guild/PickRolePlatform/components/TelegramGroup/TelegramGroup.tsx
  src/components/create-guild/hooks/useCreate.ts
Labels: improvement

#145 Leave guild button
  src/components/[guild]/EditButtonGroup/EditButtonGroup.tsx
  src/components/[guild]/LeaveButton/LeaveButton.tsx
  src/components/[guild]/LeaveButton/hooks/useLeaveGuild.ts
  src/components/[guild]/LeaveButton/index.ts
  src/pages/[guild]/index.tsx
Labels: feature

#163 Edit modals - accessibility fixes
  src/components/[guild]/EditButtonGroup/EditButtonGroup.tsx
  src/components/[guild]/EditButtonGroup/components/AddRoleDrawer.tsx
  src/components/[guild]/EditButtonGroup/components/CustomizationButton/CustomizationButton.tsx
  src/components/[guild]/EditButtonGroup/components/CustomizationButton/index.ts
  src/components/[guild]/EditButtonGroup/components/CustomizationModal/CustomizationModal.tsx
  src/components/[guild]/EditButtonGroup/components/CustomizationModal/components/BackgroundImageUploader.tsx
  src/components/[guild]/EditButtonGroup/components/CustomizationModal/components/ColorModePicker.tsx
  src/components/[guild]/EditButtonGroup/components/CustomizationModal/components/ColorPicker.tsx
  src/components/[guild]/EditButtonGroup/components/CustomizationModal/components/RemoveBackgroundImage.tsx
  src/components/[guild]/EditButtonGroup/components/CustomizationModal/index.ts
  src/components/[guild]/EditButtonGroup/components/EditGuildDrawer.tsx
  src/components/[guild]/RolesByPlatform/components/RoleListItem/components/EditRole.tsx
  src/components/[guild]/hooks/useEdit.ts
  src/components/create-guild/IconSelector/IconSelector.tsx
  src/components/create-guild/NameAndIcon.tsx
Labels: bug, improvement

#169 MirrorFormCard improvements
  src/components/create-guild/Requirements/components/MirrorFormCard/MirrorFormCard.tsx
Labels: feature

#170 Fixed customization issues
  src/components/[guild]/EditButtonGroup/components/CustomizationModal/CustomizationModal.tsx
  src/components/[guild]/EditButtonGroup/components/CustomizationModal/components/BackgroundImageUploader.tsx
  src/components/[guild]/EditButtonGroup/components/CustomizationModal/components/RemoveBackgroundImage.tsx
  src/components/[guild]/hooks/useEdit.ts
  src/components/common/Layout/Layout.tsx
  src/pages/create-guild.tsx
Labels: bug

#178 Sorting roles by members count
  src/pages/[guild]/index.tsx
Labels: feature

#176 Select menus improvements
  package-lock.json
  package.json
  src/components/common/ChakraReactSelect/AsyncCreatableSelect.tsx
  src/components/common/ChakraReactSelect/AsyncSelect.tsx
  src/components/common/ChakraReactSelect/ChakraReactSelect.tsx
  src/components/common/ChakraReactSelect/CreatableSelect.tsx
  src/components/common/ChakraReactSelect/CustomSelectOption.tsx
  src/components/common/ChakraReactSelect/Select.tsx
  src/components/common/ChakraReactSelect/index.ts
  src/components/common/ChakraReactSelect/types.ts
  src/components/common/StyledSelect/StyledSelect.tsx
  src/components/common/StyledSelect/components/CustomClearIndicator.tsx
  src/components/common/StyledSelect/components/CustomMenuList.tsx
  src/components/common/StyledSelect/components/CustomSelectOption.tsx
  src/components/common/StyledSelect/index.ts
  src/components/create-guild/Requirements/components/ChainPicker.tsx
  src/components/create-guild/Requirements/components/JuiceboxFormCard/JuiceboxFormCard.tsx
  src/components/create-guild/Requirements/components/MirrorFormCard/MirrorFormCard.tsx
  src/components/create-guild/Requirements/components/NftFormCard/NftFormCard.tsx
  src/components/create-guild/Requirements/components/PoapFormCard/PoapFormCard.tsx
  src/components/create-guild/Requirements/components/SnapshotFormCard/SnapshotFormCard.tsx
  src/components/create-guild/Requirements/components/Symbol.tsx
  src/components/create-guild/Requirements/components/TokenFormCard.tsx
  src/components/create-guild/Requirements/components/UnlockFormCard/UnlockFormCard.tsx
  src/pages/_document.tsx
  src/theme/custom-scrollbar.css
  src/theme/styles.ts
  src/types.ts
Labels: improvement

#177 Form card fixes (on create guild page & in edit drawers)
  src/components/create-guild/Requirements/Requirements.tsx
  src/components/create-guild/Requirements/components/JuiceboxFormCard/JuiceboxFormCard.tsx
  src/components/create-guild/Requirements/components/JuiceboxFormCard/hooks/useJuicebox.ts
  src/components/create-guild/Requirements/components/NftFormCard/NftFormCard.tsx
  src/components/create-guild/Requirements/components/NftFormCard/hooks/useNftMetadata.ts
  src/components/create-guild/Requirements/components/NftFormCard/hooks/useNfts.ts
  src/components/create-guild/Requirements/components/PoapFormCard/PoapFormCard.tsx
  src/components/create-guild/Requirements/components/Symbol.tsx
  src/components/create-guild/Requirements/components/UnlockFormCard/UnlockFormCard.tsx
  src/components/create-guild/Requirements/components/UnlockFormCard/hooks/useLocks.ts
  src/pages/api/juicebox.ts
  src/types.ts
  src/utils/mapRequirements.ts
  src/utils/preprocessRequirements.ts
Labels: bug, improvement

#185 Fix getting 500 internal server error instead of 404 on unexisting guild urls
  src/pages/[guild]/index.tsx
Labels: bug, prio 3
