Repository guildxyz/guild.xyz, pull requests merged in 2022-10, with the labels that each got.

#500 POAP payment/voice participation updates
  src/components/[guild]/CreatePoap/components/Requirements/components/CheckboxColorCard.tsx
  src/components/[guild]/CreatePoap/components/Requirements/components/MonetizePoap/MonetizePoap.tsx
  src/components/[guild]/CreatePoap/components/Requirements/components/VoiceParticipation/VoiceParticipation.tsx
  src/components/[guild]/CreatePoap/components/Requirements/components/VoiceParticipation/hooks/usePoapEventDetails.ts
  src/components/[guild]/claim-poap/components/ClaimModal/ClaimModal.tsx
  src/components/[guild]/claim-poap/components/ClaimModal/components/PayFeeMenuItem.tsx
  src/components/[guild]/claim-poap/hooks/useAllowance.ts
  src/components/[guild]/claim-poap/hooks/useHasPaid.ts
  src/components/[guild]/claim-poap/hooks/usePayFee.ts
  src/components/[guild]/claim-poap/hooks/useUserPoapEligibility.ts
  src/pages/[guild]/claim-poap/[fancyId].tsx
Labels: improvement

#465 GitPOAP integration
  public/requirementLogos/gitpoap.svg
  src/components/[guild]/Requirements/Requirements.tsx
  src/components/[guild]/Requirements/components/PoapRequirementCard/GitPoapRequirementCard.tsx
  src/components/create-guild/Requirements/SetRequirements.tsx
  src/components/create-guild/Requirements/components/AddRequirementCard.tsx
  src/components/create-guild/Requirements/components/GitPoapFormCard/GitPoapFormCard.tsx
  src/components/create-guild/Requirements/components/GitPoapFormCard/hooks/useGitPoaps.ts
  src/components/create-guild/Requirements/components/GitPoapFormCard/index.ts
  src/types.ts
Labels: feature

#504 POAP creation/edit endpoints rework
  package-lock.json
  package.json
  src/pages/api/poap/fancyId.ts
  src/pages/api/poap/index.ts
Labels: bug

#503 useBalancy - multichain support
  src/components/create-guild/Requirements/hooks/useBalancy.ts
Labels: feature, improvement

#509 OG images with `@vercel/og`
  api/linkpreview/index.ts
  next.config.js
  package-lock.json
  package.json
  public/fonts/Inter-Black.woff2
  public/fonts/Inter-BlackItalic.woff2
  public/fonts/Inter-Bold.ttf
  public/fonts/Inter-Bold.woff2
  public/fonts/Inter-BoldItalic.woff2
  public/fonts/Inter-ExtraBold.woff2
  public/fonts/Inter-ExtraBoldItalic.woff2
  public/fonts/Inter-ExtraLight.woff2
  public/fonts/Inter-ExtraLightItalic.woff2
  public/fonts/Inter-Italic.woff2
  public/fonts/Inter-Light.woff2
  public/fonts/Inter-LightItalic.woff2
  public/fonts/Inter-Medium.woff2
  public/fonts/Inter-MediumItalic.woff2
  public/fonts/Inter-Regular.ttf
  public/fonts/Inter-Regular.woff2
  public/fonts/Inter-SemiBold.woff2
  public/fonts/Inter-SemiBoldItalic.woff2
  public/fonts/Inter-Thin.woff2
  public/fonts/Inter-ThinItalic.woff2
  public/fonts/fonts.css
  public/img/guilders.svg
  src/components/[guild]/CreatePoap/components/PoapListItem/components/Withdraw/hooks/useWithdrawableAmounts.ts
  src/components/[guild]/CreatePoap/hooks/usePoapVault.ts
  src/components/[guild]/Requirements/components/NftRequirementCard/hooks/useNftImage.ts
  src/components/[guild]/Requirements/components/common/OpenseaUrl.tsx
  src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx
  src/components/common/LinkPreviewHead.tsx
  src/connectors/coinbaseWallet.ts
  src/connectors/metaMask.ts
  src/connectors/walletConnect.ts
  src/pages/[guild]/claim-poap/[fancyId].tsx
  src/pages/[guild]/index.tsx
  src/pages/[guild]/linkpreview.tsx
  src/pages/_document.tsx
  src/pages/api/linkpreview/[timestamp]/[guild].tsx
  src/pages/api/linkpreview/[timestamp]/index.tsx
  src/pages/api/opensea-asset-data/[address].ts
  src/pages/api/poap/get-poap-vault/[vaultId]/[chainId].ts
  src/pages/api/poap/get-vault/[vaultId]/[chainId].ts
  src/pages/api/poap/get-withdrawable-amount/[guildId]/[poapId].ts
  src/pages/developer-meetup-2022.tsx
  src/pages/index.tsx
  src/pages/lego.tsx
  src/pages/linkpreview.tsx
Labels: improvement

#499 Discord oauth rework
  src/components/[guild]/JoinModal/hooks/useConnectPlatform.ts
  src/components/[guild]/JoinModal/hooks/useDCAuth.ts
  src/components/[guild]/JoinModal/hooks/useDCAuthWithCallback.ts
  src/components/[guild]/JoinModal/hooks/useOauthPopupWindow.ts
  src/components/[guild]/Requirements/Requirements.tsx
  src/components/[guild]/Requirements/components/DiscordRoleRequirementCard.tsx
  src/components/[guild]/Requirements/components/common/ConnectRequirementPlatformButton.tsx
  src/components/[guild]/RoleCard/components/AccessIndicator/AccessIndicator.tsx
  src/components/[guild]/RolePlatforms/components/PlatformCard/components/useDiscordCardProps/DiscordCardSettings/components/ChannelsToGate/ChannelsToGate.tsx
  src/components/[guild]/RolePlatforms/components/PlatformCard/components/useDiscordCardProps/DiscordCardSettings/components/ChannelsToGate/components/Category.tsx
  src/components/[guild]/RolePlatforms/components/PlatformCard/components/useDiscordCardProps/DiscordCardSettings/components/ChannelsToGate/components/Channel.tsx
  src/components/[guild]/RolePlatforms/components/PlatformCard/components/useDiscordCardProps/DiscordCardSettings/components/RoleToManage/components/ExistingRoleSettings.tsx
  src/components/[guild]/RolePlatforms/components/PlatformCard/components/useDiscordCardProps/DiscordCardSettings/components/RoleToManage/components/UnauthenticatedOptions.tsx
  src/components/[guild]/hooks/useAutoStatusUpdate.ts
  src/components/common/DiscordGuildSetup.tsx
  src/components/common/StyledSelect/StyledSelect.tsx
  src/components/create-guild/PlatformsGrid/components/BaseOAuthSelectButton.tsx
  src/components/create-guild/PlatformsGrid/components/DiscordSelectButton.tsx
  src/components/create-guild/PlatformsGrid/components/GitHubSelectButton.tsx
  src/components/create-guild/Requirements/SetRequirements.tsx
  src/components/create-guild/Requirements/components/AddRequirementCard.tsx
  src/components/create-guild/Requirements/components/DiscordFormCard/DiscordFormCard.tsx
  src/components/create-guild/Requirements/components/DiscordFormCard/components/DiscordRole.tsx
  src/components/create-guild/Requirements/components/DiscordFormCard/index.ts
  src/components/create-guild/Requirements/components/FormCard.tsx
  src/components/guard/setup/DCServerCard.tsx
  src/components/index/CallToAction.tsx
  src/hooks/useGateables.ts
  src/hooks/useIsConnected.ts
  src/hooks/useUsersServers.ts
  src/pages/create-guild/discord.tsx
  src/pages/guard/index.tsx
  src/pages/guard/setup.tsx
  src/pages/oauth.tsx
  src/types.ts
Labels: improvement

#518 Datadog logging rework
  src/components/[guild]/JoinModal/components/ConnectAccount.tsx
  src/components/[guild]/JoinModal/components/JoinStep.tsx
  src/components/[guild]/JoinModal/components/WalletAuthButtonWithBalance.tsx
  src/components/[guild]/JoinModal/hooks/useConnectPlatform.ts
  src/components/[guild]/JoinModal/hooks/useJoin.tsx
  src/components/[guild]/Onboarding/Onboarding.tsx
  src/components/[guild]/Onboarding/components/SummonMembers/SummonMembers.tsx
  src/components/[guild]/Onboarding/components/SummonMembers/components/PanelBody/components/PanelDescription.tsx
  src/components/[guild]/Onboarding/components/SummonMembers/components/PanelBody/components/PanelTitle.tsx
  src/components/[guild]/Onboarding/components/SummonMembers/components/PanelButton.tsx
  src/components/[guild]/Onboarding/components/SummonMembers/components/SendDiscordJoinButtonModal.tsx
  src/components/[guild]/Onboarding/components/SummonMembers/hooks/useSendJoin.tsx
  src/components/[guild]/claim-poap/components/ClaimModal/ClaimModal.tsx
  src/components/[guild]/hooks/useAutoStatusUpdate.ts
  src/components/_app/Datadog/Datadog.tsx
  src/components/_app/Datadog/index.ts
  src/components/_app/Datadog/useDatadog.ts
  src/components/_app/Web3ConnectionManager/Web3ConnectionManager.tsx
  src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/components/ConnectorButton.tsx
  src/components/create-guild/EntryChannel.tsx
  src/components/create-guild/Name.tsx
  src/components/create-guild/Requirements/SetRequirements.tsx
  src/components/create-guild/TelegramGroup/TelegramGroup.tsx
  src/components/create-guild/hooks/useCreateGuild.tsx
  src/components/create-guild/hooks/useCreateRole.tsx
  src/components/explorer/SearchBar.tsx
  src/components/guard/setup/ServerSetupCard/ServerSetupCard.tsx
  src/hooks/useKeyPair.ts
  src/hooks/useLocalStorage.ts
  src/pages/api/ddrum.ts
  src/pages/tgauth.tsx
Labels: feature, improvement

#530 Disconnect alert position fix
  src/theme/components/modal.ts
Labels: bug

#532 Link previews: light mode support
  public/guildLogos/logo-dark.svg
  public/img/guilders-dark.svg
  src/pages/api/linkpreview/[timestamp]/[guild].tsx
  src/pages/api/linkpreview/[timestamp]/index.tsx
Labels: feature, improvement

#533 useTimeInaccuracy with `shouldFetch`
  src/hooks/useLocalStorage.ts
  src/hooks/useSubmit/useSubmit.ts
  src/hooks/useTimeInaccuracy.ts
  src/pages/api/linkpreview/[timestamp]/[guild].tsx
  src/pages/api/linkpreview/[timestamp]/index.tsx
Labels: improvement
