Repository guildxyz/guild.xyz, pull requests merged in 2022-05, with the labels that each got.

#345 Gate channels on role creation
  src/components/[guild]/AddRoleButton.tsx
  src/components/[guild]/RolesByPlatform/components/RoleListItem/components/EditRole/components/ChannelsToGate/ChannelsToGate.tsx
  src/components/[guild]/RolesByPlatform/components/RoleListItem/components/EditRole/hooks/useEditRole.ts
  src/components/create-guild/hooks/useCreateRole.tsx
  src/utils/preprocessGatedChannels.ts
Labels: improvement

#338 Account button rework & join guild on any chain
  src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx
  src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/utils/processConnectionError.ts
  src/components/common/Layout/components/Account/Account.tsx
  src/connectors.ts
Labels: improvement

#308 New create guild flow with onboarding steps
  package-lock.json
  package.json
  public/videos/dc-bot-role-config-guide.webm
  src/components/[guild]/AddRoleButton.tsx
  src/components/[guild]/EditGuildButton/EditGuildButton.tsx
  src/components/[guild]/EditGuildButton/components/Guard.tsx
  src/components/[guild]/Onboarding/Onboarding.tsx
  src/components/[guild]/Onboarding/components/AddRolesAndRequirements.tsx
  src/components/[guild]/Onboarding/components/OnboardingProvider.tsx
  src/components/[guild]/Onboarding/components/PaginationButtons.tsx
  src/components/[guild]/Onboarding/components/SummonMembers/SummonMembers.tsx
  src/components/[guild]/Onboarding/components/SummonMembers/components/PanelBody/PanelBody.tsx
  src/components/[guild]/Onboarding/components/SummonMembers/components/PanelBody/components/PanelDescription.tsx
  src/components/[guild]/Onboarding/components/SummonMembers/components/PanelBody/components/PanelTitle.tsx
  src/components/[guild]/Onboarding/components/SummonMembers/components/PanelBody/index.ts
  src/components/[guild]/Onboarding/components/SummonMembers/components/PanelButton.tsx
  src/components/[guild]/Onboarding/components/SummonMembers/hooks/useSendJoin.tsx
  src/components/[guild]/Onboarding/components/SummonMembers/index.ts
  src/components/[guild]/Onboarding/index.ts
  src/components/[guild]/RolesByPlatform/components/Platform.tsx
  src/components/[guild]/RolesByPlatform/components/RoleListItem/components/EditRole/EditRole.tsx
  src/components/[guild]/RolesByPlatform/components/RoleListItem/components/EditRole/components/ChannelsToGate/ChannelsToGate.tsx
  src/components/[guild]/TwitterShare.tsx
  src/components/common/DiscordGuildSetup.tsx
  src/components/common/OnboardingMarker.tsx
  src/components/common/Switch.tsx
  src/components/create-guild/EntryChannel.tsx
  src/components/create-guild/PickRolePlatform/PickRolePlatform.tsx
  src/components/create-guild/PickRolePlatform/components/Discord/Discord.tsx
  src/components/create-guild/PickRolePlatform/components/Discord/index.ts
  src/components/create-guild/PickRolePlatform/components/PlatformOption.tsx
  src/components/create-guild/PickRolePlatform/index.ts
  src/components/create-guild/TelegramGroup/TelegramGroup.tsx
  src/components/create-guild/TelegramGroup/hooks/useIsTGBotIn.ts
  src/components/create-guild/TelegramGroup/index.ts
  src/components/create-guild/hooks/useSetImageAndNameFromPlatformData.ts
  src/components/guard/setup/DCServerCard.tsx
  src/components/guard/setup/ServerSetupCard/ServerSetupCard.tsx
  src/components/guard/setup/ServerSetupCard/components/PickSecurityLevel/components/KeepAccessInfoText.tsx
  src/hooks/useColorPalette.ts
  src/hooks/useServerData.ts
  src/hooks/useUsersServers.ts
  src/pages/[guild]/index.tsx
  src/pages/create-guild/discord.tsx
  src/pages/create-guild/index.tsx
  src/pages/create-guild/telegram.tsx
  src/pages/guard/setup.tsx
  src/theme/colors.ts
  src/theme/components/index.ts
  src/theme/styles.ts
Labels: feature, improvement

#337 fix: never show route change warning on guild delete success
  src/components/[guild]/EditGuildButton/EditGuildButton.tsx
  src/components/[guild]/EditGuildButton/components/DeleteGuildButton/hooks/useDeleteGuild.ts
Labels: bug

#354 remove requirements on turning on free entry
  src/components/create-guild/Requirements/SetRequirements.tsx
Labels: improvement

#353 Guard improvements
  src/components/[guild]/EditGuildButton/EditGuildButton.tsx
  src/components/[guild]/EditGuildButton/components/Guard.tsx
  src/components/_app/Web3ConnectionManager/Web3ConnectionManager.tsx
  src/components/create-guild/EntryChannel.tsx
  src/components/guard/setup/DCServerCard.tsx
  src/components/guard/setup/ServerSetupCard/ServerSetupCard.tsx
  src/pages/guard/setup.tsx
Labels: improvement

#325 refactor/perf: useSubmit without XState
  README.md
  package-lock.json
  package.json
  src/components/[guild]/EditGuildButton/components/DeleteGuildButton/hooks/useDeleteGuild.ts
  src/components/[guild]/EditGuildButton/hooks/useEditGuild.ts
  src/components/[guild]/LeaveButton/hooks/useLeaveGuild.ts
  src/components/[guild]/Onboarding/components/SummonMembers/hooks/useSendJoin.tsx
  src/components/[guild]/RolesByPlatform/components/JoinButton/components/JoinModal/hooks/useJoinPlatform.ts
  src/components/[guild]/RolesByPlatform/components/RoleListItem/components/EditRole/components/DeleteRoleButton/hooks/useDeleteRole.ts
  src/components/[guild]/RolesByPlatform/components/RoleListItem/components/EditRole/hooks/useEditRole.ts
  src/components/[guild]/hooks/useUser.ts
  src/components/common/Layout/components/Account/components/AccountModal/hooks/useUpdateUser.ts
  src/components/create-guild/hooks/useCreateGuild.tsx
  src/components/create-guild/hooks/useCreateRole.tsx
  src/hooks/useSubmit.ts
  src/hooks/useSubmit/index.ts
  src/hooks/useSubmit/utils/fetchMachine.ts
  src/types.ts
Labels: improvement

#352 Added Rinkeby, Metis, Cronos and Boba chains
  public/networkLogos/boba.svg
  public/networkLogos/cronos.svg
  public/networkLogos/metis.svg
  src/components/[guild]/Requirements/components/TokenRequirementCard/TokenRequirementCard.tsx
  src/connectors.ts
  src/hooks/useTokens.ts
  src/types.ts
Labels: feature

#324 refactor: image uploading hooks rework
  src/components/[guild]/AddRoleButton/AddRoleButton.tsx
  src/components/[guild]/EditGuildButton/EditGuildButton.tsx
  src/components/[guild]/EditGuildButton/components/BackgroundImageUploader.tsx
  src/components/[guild]/RolesByPlatform/components/RoleListItem/components/EditRole/EditRole.tsx
  src/components/create-guild/IconSelector/IconSelector.tsx
  src/components/create-guild/IconSelector/components/PhotoUploader.tsx
  src/components/create-guild/SubmitButton.tsx
  src/components/create-guild/TelegramGroup/TelegramGroup.tsx
  src/components/create-guild/hooks/useSetImageAndNameFromPlatformData.ts
  src/components/guard/setup/ServerSetupCard/ServerSetupCard.tsx
  src/hooks/usePinata/index.ts
  src/hooks/usePinata/usePinata.ts
  src/hooks/usePinata/utils/pinataUpload.ts
  src/hooks/useSubmitWithUpload.ts
  src/hooks/useUploadImage.ts
  src/hooks/useUploadPromise.ts
  src/pages/create-guild/telegram.tsx
Labels: improvement

#350 New requirement card designs
  public/explorerLogos/boba-light.svg
  public/explorerLogos/bscscan-dark.svg
  public/explorerLogos/bscscan-light.svg
  public/explorerLogos/cronos-dark.svg
  public/explorerLogos/etherscan-dark.svg
  public/explorerLogos/etherscan-light.svg
  public/explorerLogos/ftmscan.svg
  public/explorerLogos/metis-dark.svg
  public/explorerLogos/snowtrace.svg
  public/networkLogos/gnosis.svg
  public/requirementLogos/opensea.svg
  src/components/[guild]/Requirements/components/AllowlistRequirementCard.tsx
  src/components/[guild]/Requirements/components/JuiceboxRequirementCard/JuiceboxRequirementCard.tsx
  src/components/[guild]/Requirements/components/MirrorRequirementCard.tsx
  src/components/[guild]/Requirements/components/NftRequirementCard/NftRequirementCard.tsx
  src/components/[guild]/Requirements/components/NftRequirementCard/hooks/useNftImage.ts
  src/components/[guild]/Requirements/components/PoapRequirementCard/PoapRequirementCard.tsx
  src/components/[guild]/Requirements/components/TokenRequirementCard/TokenRequirementCard.tsx
  src/components/[guild]/Requirements/components/TokenRequirementCard/hooks/useTokenImage.ts
  src/components/[guild]/Requirements/components/UnlockRequirementCard.tsx
  src/components/[guild]/Requirements/components/common/BlockExplorerUrl.tsx
  src/components/[guild]/Requirements/components/common/OpenseaUrl.tsx
  src/components/[guild]/Requirements/components/common/RequirementCard.tsx
  src/connectors.ts
  src/pages/api/opensea-asset-data/[address].ts
Labels: improvement

#355 Trigger actions on `OnboardingMarker` click
  src/components/[guild]/AddRoleButton/AddRoleButton.tsx
  src/components/[guild]/EditGuildButton/EditGuildButton.tsx
  src/components/[guild]/RolesByPlatform/components/RoleListItem/components/EditRole/EditRole.tsx
  src/components/common/OnboardingMarker.tsx
Labels: improvement

#356 Improved join button panel preview
  src/components/[guild]/Onboarding/components/SummonMembers/SummonMembers.tsx
  src/components/[guild]/Onboarding/components/SummonMembers/components/PanelBody/PanelBody.tsx
  src/components/[guild]/Onboarding/components/SummonMembers/components/PanelBody/components/EditableControls.tsx
  src/components/[guild]/Onboarding/components/SummonMembers/components/PanelBody/components/PanelDescription.tsx
  src/components/[guild]/Onboarding/components/SummonMembers/components/PanelBody/components/PanelTitle.tsx
  src/components/[guild]/Onboarding/components/SummonMembers/components/PanelButton.tsx
Labels: improvement

#361 Filtered explorer page
  src/pages/explorer.tsx
  src/types.ts
Labels: feature, improvement
