Repository guildxyz/guild.xyz, pull requests merged in 2022-03, with the labels that each got.

#227 feature: Show members toggle
  src/components/[guild]/EditGuildButton/EditGuildButton.tsx
  src/components/[guild]/EditGuildButton/components/MembersToggle.tsx
  src/pages/[guild]/index.tsx
  src/types.ts
Labels: feature, waiting for BE

#240 Requirements refactor
  src/components/[guild]/RequirementCard/RequirementCard.tsx
  src/components/[guild]/RequirementCard/components/Mirror.tsx
  src/components/[guild]/RequirementCard/components/SnapshotStrategy.tsx
  src/components/[guild]/RequirementCard/components/Token.tsx
  src/components/[guild]/RequirementCard/components/Whitelist.tsx
  src/components/[guild]/RolesByPlatform/components/RoleListItem/components/EditRole/hooks/useEditRole.ts
  src/components/[guild]/RolesByPlatform/components/RoleListItem/hooks/useRequirementLabels.ts
  src/components/create-guild/CreateGuildName.tsx
  src/components/create-guild/Description.tsx
  src/components/create-guild/IconSelector/IconSelector.tsx
  src/components/create-guild/LogicPicker/LogicPicker.tsx
  src/components/create-guild/PickRolePlatform/PickRolePlatform.tsx
  src/components/create-guild/PickRolePlatform/components/Discord/Discord.tsx
  src/components/create-guild/PickRolePlatform/components/TelegramGroup/TelegramGroup.tsx
  src/components/create-guild/Requirements/Requirements.tsx
  src/components/create-guild/Requirements/components/ERC1155FormCard/ERC1155FormCard.tsx
  src/components/create-guild/Requirements/components/ERC1155FormCard/index.ts
  src/components/create-guild/Requirements/components/JuiceboxFormCard/JuiceboxFormCard.tsx
  src/components/create-guild/Requirements/components/MirrorFormCard/MirrorFormCard.tsx
  src/components/create-guild/Requirements/components/NftFormCard/NftFormCard.tsx
  src/components/create-guild/Requirements/components/PoapFormCard/PoapFormCard.tsx
  src/components/create-guild/Requirements/components/SnapshotFormCard/SnapshotFormCard.tsx
  src/components/create-guild/Requirements/components/TokenFormCard.tsx
  src/components/create-guild/Requirements/components/UnlockFormCard/UnlockFormCard.tsx
  src/components/create-guild/Requirements/components/WhitelistFormCard.tsx
  src/components/create-guild/hooks/useCreate.ts
  src/pages/create-guild.tsx
  src/types.ts
  src/utils/guildJsonReplacer.ts
  src/utils/mapRequirements.ts
  src/utils/preprocessRequirements.ts
  src/utils/tryToParse.ts
Labels: improvement

#254 Mutating guild list on guild create/edit/delete
  src/components/[guild]/EditGuildButton/components/DeleteGuildButton/hooks/useDeleteGuild.ts
  src/components/[guild]/EditGuildButton/hooks/useEditGuild.ts
  src/components/create-guild/hooks/useCreate.ts
  src/hooks/useMatchMutate.ts
Labels: improvement

#261 NOR and NAND requirements logic
  src/components/create-guild/LogicPicker/LogicPicker.tsx
Labels: feature

#268 Add Discord bot to server UX improvements
  src/components/create-guild/PickRolePlatform/components/Discord/Discord.tsx
  src/components/create-guild/PickRolePlatform/components/Discord/hooks/useServerData.ts
  src/hooks/usePopupWindow.ts
Labels: improvement

#278 Check accesses on role creation
  src/components/create-guild/hooks/useCreate.tsx
Labels: bug
