Repository guildxyz/guild.xyz, pull requests merged in 2022-08, with the labels that each got.

#445 Datadog sourcemaps
  .github/workflows/dd-sourcemaps.yaml
  next.config.js
  package-lock.json
  package.json
  tsconfig.json
Labels: improvement

#451 Nouns traits
  package-lock.json
  package.json
  src/components/[guild]/Requirements/Requirements.tsx
  src/components/[guild]/Requirements/components/NftRequirementCard/NftRequirementCard.tsx
  src/components/create-guild/Requirements/SetRequirements.tsx
  src/components/create-guild/Requirements/components/FormCard.tsx
  src/components/create-guild/Requirements/components/NftFormCard/NftFormCard.tsx
  src/components/create-guild/Requirements/components/NftFormCard/hooks/useNftMetadata.ts
  src/components/create-guild/Requirements/components/NftFormCard/hooks/useNftType.ts
  src/types.ts
  src/utils/mapRequirements.ts
Labels: improvement

#452 Twitter connect button fix for no wallet connection
  src/components/[guild]/JoinModal/components/ConnectAccount.tsx
  src/components/[guild]/JoinModal/components/ConnectPlatform.tsx
  src/components/[guild]/JoinModal/components/JoinStep.tsx
  src/components/[guild]/claim-poap/components/ClaimModal.tsx
Labels: improvement

#443 POAP drop UX improvements
  src/components/[guild]/CreatePoap/CreatePoap.tsx
  src/components/[guild]/CreatePoap/components/CreatePoapForm.tsx
  src/components/[guild]/CreatePoap/components/Distribution/Distribution.tsx
  src/components/[guild]/CreatePoap/components/Distribution/components/EmbedButton.tsx
  src/components/[guild]/CreatePoap/components/Distribution/components/EmbedDescription.tsx
  src/components/[guild]/CreatePoap/components/Distribution/components/EmbedTitle.tsx
  src/components/[guild]/CreatePoap/components/Distribution/index.ts
  src/components/[guild]/CreatePoap/components/MonetizePoap/MonetizePoap.tsx
  src/components/[guild]/CreatePoap/components/MonetizePoap/components/MonetizationModal.tsx
  src/components/[guild]/CreatePoap/components/MonetizePoap/components/MonetizedPoapCard.tsx
  src/components/[guild]/CreatePoap/components/MonetizePoap/hooks/useRegisterVault.ts
  src/components/[guild]/CreatePoap/components/PoapListItem/PoapListItem.tsx
  src/components/[guild]/CreatePoap/components/SetupBot/index.ts
  src/components/[guild]/CreatePoap/components/UploadMintLinks.tsx
  src/components/[guild]/JoinModal/components/WalletAuthButtonWithBalance.tsx
  src/components/[guild]/claim-poap/components/ClaimModal.tsx
  src/components/[guild]/claim-poap/hooks/useHasPaid.ts
  src/components/[guild]/claim-poap/hooks/usePayFee.ts
  src/pages/[guild]/claim-poap/[fancyId].tsx
  src/types.ts
Labels: improvement

#456 feat: multichain POAP monetization
  src/components/[guild]/CreatePoap/CreatePoap.tsx
  src/components/[guild]/CreatePoap/components/CreatePoapContext.tsx
  src/components/[guild]/CreatePoap/components/CreatePoapForm.tsx
  src/components/[guild]/CreatePoap/components/MonetizePoap/MonetizePoap.tsx
  src/components/[guild]/CreatePoap/components/MonetizePoap/components/MonetizationModal.tsx
  src/components/[guild]/CreatePoap/components/MonetizePoap/components/MonetizedPoapCard.tsx
  src/components/[guild]/CreatePoap/components/MonetizePoap/hooks/useDeleteMonetization.ts
  src/components/[guild]/CreatePoap/components/PoapListItem/PoapListItem.tsx
  src/components/[guild]/CreatePoap/components/PoapListItem/components/Withdraw/Withdraw.tsx
  src/components/[guild]/CreatePoap/components/PoapListItem/components/Withdraw/components/WithdrawButton.tsx
  src/components/[guild]/CreatePoap/components/PoapListItem/components/Withdraw/hooks/useWithdrawableAmounts.ts
  src/components/[guild]/CreatePoap/components/PoapListItem/components/Withdraw/index.ts
  src/components/[guild]/CreatePoap/components/PoapListItem/hooks/useGetVault.ts
  src/components/[guild]/CreatePoap/hooks/useCreatePoap.ts
  src/components/[guild]/CreatePoap/hooks/usePoapVault.ts
  src/components/[guild]/claim-poap/components/ChooseFeeModal/ChooseFeeModal.tsx
  src/components/[guild]/claim-poap/components/ChooseFeeModal/components/PayFeeButton.tsx
  src/components/[guild]/claim-poap/components/ChooseFeeModal/index.ts
  src/components/[guild]/claim-poap/components/ClaimModal.tsx
  src/components/[guild]/claim-poap/hooks/usePayFee.ts
  src/hooks/useTokenData.ts
  src/pages/[guild]/claim-poap/[fancyId].tsx
  src/pages/api/poap/create-poap.ts
  src/pages/api/poap/get-poap-vault.ts
  src/pages/api/poap/get-vault.ts
  src/pages/api/poap/get-withdrawable-amount.ts
  src/types.ts
Labels: feature, improvement

#463 POAP payment flow improvements
  src/components/[guild]/CreatePoap/components/MonetizePoap/MonetizePoap.tsx
  src/components/[guild]/CreatePoap/components/PoapListItem/PoapListItem.tsx
  src/components/[guild]/JoinModal/components/JoinStep.tsx
  src/components/[guild]/claim-poap/components/ChooseFeeModal/ChooseFeeModal.tsx
  src/components/[guild]/claim-poap/components/ChooseFeeModal/components/PayFeeButton.tsx
  src/components/[guild]/claim-poap/components/ChooseFeeModal/index.ts
  src/components/[guild]/claim-poap/components/ClaimModal/ClaimModal.tsx
  src/components/[guild]/claim-poap/components/ClaimModal/components/PayFeeMenuItem.tsx
  src/components/[guild]/claim-poap/components/ClaimModal/index.ts
  src/components/common/AddCard.tsx
Labels: improvement

#458 Google level up
  src/components/[guild]/RoleCard/components/Reward.tsx
  src/components/[guild]/RolePlatforms/components/AddRewardModal/components/AddGooglePanel.tsx
  src/components/[guild]/RolePlatforms/components/PlatformCard/components/useGoogleCardProps/GoogleCardSettings.tsx
  src/components/[guild]/RolePlatforms/components/PlatformCard/components/useGoogleCardProps/index.ts
  src/components/[guild]/RolePlatforms/components/PlatformCard/components/useGoogleCardProps/useGoogleCardProps.tsx
  src/components/common/GoogleGuildSetup/GoogleGuildSetup.tsx
  src/components/common/GoogleGuildSetup/components/GoogleDocCard.tsx
  src/components/common/GoogleGuildSetup/components/GoogleDocSetupCard.tsx
  src/components/common/GoogleGuildSetup/components/PermissionSelection.tsx
  src/pages/create-guild/google.tsx
  src/platforms.ts
  src/types.ts
Labels: improvement, prio 2, waiting for BE

#472 Search for private Galaxy campaigns
  src/components/create-guild/Requirements/components/GalaxyFormCard/GalaxyFormCard.tsx
Labels: feature, improvement

#473 Optimize backend requests
  src/components/[guild]/hooks/useGuild.ts
  src/components/[guild]/hooks/useUser.ts
  src/components/explorer/hooks/useMemberships.ts
Labels: improvement
