Repository guildxyz/guild.xyz, pull requests merged in 2022-04, with the labels that each got.

#282 Don't validate name field by urlName on creation
  src/components/create-guild/CreateGuildName.tsx
Labels: improvement

#281 fix: background height glitch
  src/components/common/Layout/Layout.tsx
Labels: bug

#273 feat: Get name and icon by platform automatically
  next.config.js
  src/components/create-guild/CreateGuildName.tsx
  src/components/create-guild/IconSelector/IconSelector.tsx
  src/components/create-guild/IconSelector/components/PhotoUploader.tsx
  src/components/create-guild/PickRolePlatform/PickRolePlatform.tsx
  src/components/create-guild/PickRolePlatform/components/Discord/Discord.tsx
  src/components/create-guild/PickRolePlatform/components/Discord/hooks/useServerData.ts
  src/components/create-guild/PickRolePlatform/components/TelegramGroup/TelegramGroup.tsx
  src/components/create-guild/PickRolePlatform/components/TelegramGroup/hooks/useIsTGBotIn.ts
  src/components/create-guild/PickRolePlatform/hooks/useSetImageAndNameFromPlatformData.ts
  src/components/create-guild/hooks/useCreate.tsx
  src/pages/create-guild.tsx
  src/utils/getRandomInt.ts
Labels: feature

#277 feat: Discord server select instead of invite input on create
  public/default_discord_icon.png
  src/components/[guild]/RolesByPlatform/components/JoinButton/components/JoinModal/JoinDiscordModal.tsx
  src/components/[guild]/RolesByPlatform/components/JoinButton/components/JoinModal/components/DCAuthButton.tsx
  src/components/[guild]/RolesByPlatform/components/JoinButton/components/JoinModal/hooks/useDCAuth.ts
  src/components/create-guild/PickRolePlatform/components/Discord/Discord.tsx
  src/components/create-guild/PickRolePlatform/components/Discord/hooks/useServerData.ts
  src/hooks/usePopupWindow.ts
  src/pages/dcauth.tsx
  src/types.ts
Labels: improvement

#300 Copy/export balancy addresses
  src/components/create-guild/Requirements/components/BalancyCounter.tsx
  src/components/create-guild/Requirements/hooks/useBalancy.ts
Labels: feature

#298 Fix: pasting address in the select inputs on mobile
  src/components/common/StyledSelect/StyledSelect.tsx
Labels: bug

#302 fix: url name validation
  src/components/[guild]/EditGuildButton/components/UrlName.tsx
Labels: bug

#287 Include a CSRF token in OAuth state, and validate it on `dcauth` page
  src/components/[guild]/RolesByPlatform/components/JoinButton/components/JoinModal/hooks/useDCAuth.ts
  src/hooks/useLocalStorage.ts
  src/pages/dcauth.tsx
Labels: improvement

#303 feat(guard): support existing guilds
  .env.production
  src/components/[guild]/EditGuildButton/EditGuildButton.tsx
  src/components/[guild]/EditGuildButton/hooks/useEditGuild.ts
  src/components/[guild]/hooks/useGuild.ts
  src/components/create-guild/PickRolePlatform/hooks/useSetImageAndNameFromPlatformData.ts
  src/components/create-guild/hooks/useCreate.tsx
  src/components/guard/setup/hooks/useGuildByPlatformId.ts
  src/pages/guard/setup.tsx
Labels: improvement

#307 refactor(guard): separate ServerSetupCard & Disclaimer components
  src/components/guard/setup/ServerSetupCard/ServerSetupCard.tsx
  src/components/guard/setup/ServerSetupCard/components/Disclaimer.tsx
  src/components/guard/setup/ServerSetupCard/components/PickSecurityLevel/PickSecurityLevel.tsx
  src/components/guard/setup/ServerSetupCard/components/PickSecurityLevel/components/KeepAccessInfoText.tsx
  src/components/guard/setup/ServerSetupCard/components/PickSecurityLevel/components/SecurityLevelOption.tsx
  src/components/guard/setup/ServerSetupCard/components/PickSecurityLevel/index.ts
  src/components/guard/setup/ServerSetupCard/index.ts
  src/pages/guard/setup.tsx
Labels: improvement

#312 improvement(guard): get guild by 1 endpoint, summon by 1 request
  src/components/guard/setup/ServerSetupCard/ServerSetupCard.tsx
  src/components/guard/setup/hooks/useGuildByPlatformId.ts
Labels: improvement

#314 refactor: useDCAuth return token & export fetcher function
  src/components/[guild]/RolesByPlatform/components/JoinButton/components/JoinModal/JoinDiscordModal.tsx
  src/components/[guild]/RolesByPlatform/components/JoinButton/components/JoinModal/hooks/useDCAuth.ts
  src/components/create-guild/PickRolePlatform/components/Discord/Discord.tsx
  src/pages/guard/index.tsx
Labels: improvement

#315 DC servers fetched on `/guard/setup`
  src/components/common/ErrorAlert.tsx
  src/components/create-guild/PickRolePlatform/components/Discord/Discord.tsx
  src/hooks/useUsersServers.ts
  src/pages/create-guild.tsx
  src/pages/guard/index.tsx
  src/pages/guard/setup.tsx
Labels: improvement

#316 Guard server card button improvements
  src/components/create-guild/PickRolePlatform/components/Discord/hooks/useServerData.ts
  src/components/guard/setup/DCServerCard.tsx
  src/components/guard/setup/ServerSetupCard/ServerSetupCard.tsx
  src/components/guard/setup/hooks/useGuildByPlatformId.ts
  src/pages/guard/setup.tsx
Labels: improvement

#322 feat: Automatic theme color by image
  package-lock.json
  package.json
  src/components/create-guild/PickRolePlatform/hooks/useSetImageAndNameFromPlatformData.ts
Labels: feature, prio 3

#327 Temporary fix for links in descriptions
  src/components/[guild]/RolesByPlatform/components/RoleListItem/RoleListItem.tsx
  src/components/common/Layout/Layout.tsx
  src/utils/parseDescription.tsx
Labels: improvement

#321 Requirements: min/max fields (amount)
  src/components/[guild]/Requirements/components/JuiceboxRequirementCard.tsx
  src/components/[guild]/Requirements/components/NftRequirementCard.tsx
  src/components/[guild]/Requirements/components/TokenRequirementCard/TokenRequirementCard.tsx
  src/components/[guild]/RolesByPlatform/components/RoleListItem/hooks/useRequirementLabels.ts
  src/components/create-guild/Requirements/components/JuiceboxFormCard/JuiceboxFormCard.tsx
  src/components/create-guild/Requirements/components/MinMaxAmount.tsx
  src/components/create-guild/Requirements/components/NftFormCard/NftFormCard.tsx
  src/components/create-guild/Requirements/components/TokenFormCard.tsx
  src/components/create-guild/Requirements/hooks/useBalancy.ts
  src/types.ts
Labels: feature, improvement

#331 MinMaxAmount add info tooltip & fix fractional amount support
  src/components/create-guild/Requirements/components/MinMaxAmount.tsx
  src/components/create-guild/Requirements/components/TokenFormCard.tsx
Labels: improvement

#333 hotfix: guild page optimization
  src/components/[guild]/Members/Members.tsx
  src/hooks/useGuildMembers.ts
Labels: improvement

#328 Image on requirement cards
  src/components/[guild]/Requirements/Requirements.tsx
  src/components/[guild]/Requirements/components/JuiceboxRequirementCard.tsx
  src/components/[guild]/Requirements/components/JuiceboxRequirementCard/JuiceboxRequirementCard.tsx
  src/components/[guild]/Requirements/components/JuiceboxRequirementCard/hooks/useJuiceboxProject.ts
  src/components/[guild]/Requirements/components/JuiceboxRequirementCard/index.ts
  src/components/[guild]/Requirements/components/MirrorRequirementCard.tsx
  src/components/[guild]/Requirements/components/NftRequirementCard.tsx
  src/components/[guild]/Requirements/components/NftRequirementCard/NftRequirementCard.tsx
  src/components/[guild]/Requirements/components/NftRequirementCard/hooks/useNftImage.ts
  src/components/[guild]/Requirements/components/NftRequirementCard/index.ts
  src/components/[guild]/Requirements/components/PoapRequirementCard.tsx
  src/components/[guild]/Requirements/components/PoapRequirementCard/PoapRequirementCard.tsx
  src/components/[guild]/Requirements/components/PoapRequirementCard/hooks/usePoap.ts
  src/components/[guild]/Requirements/components/PoapRequirementCard/index.ts
  src/components/[guild]/Requirements/components/TokenRequirementCard/TokenRequirementCard.tsx
  src/components/[guild]/Requirements/components/UnlockRequirementCard.tsx
  src/components/create-guild/Requirements/components/JuiceboxFormCard/hooks/useJuicebox.ts
  src/components/create-guild/Requirements/components/MirrorFormCard/MirrorFormCard.tsx
  src/components/create-guild/Requirements/components/MirrorFormCard/hooks/useMirror.ts
  src/pages/api/juicebox/[id].ts
  src/pages/api/juicebox/index.ts
  src/pages/api/opensea-asset-image/[address].ts
  src/types.ts
Labels: feature

#326 Pre commit hook fix
  .husky/pre-commit
  .husky/pre-push
  package.json
Labels: improvement
