Repository guildxyz/guild.xyz, pull requests merged in 2022-06, with the labels that each got.

#370 POAP drop
  package-lock.json
  package.json
  public/img/poap-illustration.svg
  src/components/[guild]/CreatePoap/CreatePoap.tsx
  src/components/[guild]/CreatePoap/components/CreatePoapContext.tsx
  src/components/[guild]/CreatePoap/components/CreatePoapForm.tsx
  src/components/[guild]/CreatePoap/components/CreatePoapSuccess.tsx
  src/components/[guild]/CreatePoap/components/PoapListItem.tsx
  src/components/[guild]/CreatePoap/components/SetupBot/SetupBot.tsx
  src/components/[guild]/CreatePoap/components/SetupBot/components/EmbedButton.tsx
  src/components/[guild]/CreatePoap/components/SetupBot/components/EmbedDescription.tsx
  src/components/[guild]/CreatePoap/components/SetupBot/components/EmbedTitle.tsx
  src/components/[guild]/CreatePoap/components/SetupBot/index.ts
  src/components/[guild]/CreatePoap/components/UploadMintLinks.tsx
  src/components/[guild]/CreatePoap/hooks/useCreatePoap.ts
  src/components/[guild]/CreatePoap/hooks/usePoapLinks.ts
  src/components/[guild]/CreatePoap/hooks/useSavePoap.ts
  src/components/[guild]/CreatePoap/hooks/useUploadMintLinks.ts
  src/components/[guild]/CreatePoap/index.ts
  src/components/[guild]/EditGuild/EditGuild.tsx
  src/components/[guild]/EditGuild/components/Admins/Admins.tsx
  src/components/[guild]/EditGuild/components/Admins/components/AdminSelect.tsx
  src/components/[guild]/EditGuild/components/Admins/index.ts
  src/components/[guild]/EditGuild/components/BackgroundImageUploader.tsx
  src/components/[guild]/EditGuild/components/ColorModePicker.tsx
  src/components/[guild]/EditGuild/components/ColorPicker.tsx
  src/components/[guild]/EditGuild/components/DeleteGuildButton/DeleteGuildButton.tsx
  src/components/[guild]/EditGuild/components/DeleteGuildButton/hooks/useDeleteGuild.ts
  src/components/[guild]/EditGuild/components/DeleteGuildButton/index.ts
  src/components/[guild]/EditGuild/components/Guard.tsx
  src/components/[guild]/EditGuild/components/HideFromExplorerToggle.tsx
  src/components/[guild]/EditGuild/components/MembersToggle.tsx
  src/components/[guild]/EditGuild/components/RemoveBackgroundImage.tsx
  src/components/[guild]/EditGuild/components/UrlName.tsx
  src/components/[guild]/EditGuild/hooks/useEditGuild.ts
  src/components/[guild]/EditGuild/index.ts
  src/components/[guild]/EditGuildButton/index.ts
  src/components/[guild]/GuildMenu/GuildMenu.tsx
  src/components/[guild]/GuildMenu/index.ts
  src/components/[guild]/Onboarding/components/SummonMembers/hooks/useSendJoin.tsx
  src/components/create-guild/EntryChannel.tsx
  src/components/create-guild/hooks/useJsConfetti.ts
  src/pages/[guild]/index.tsx
  src/pages/_document.tsx
  src/pages/api/create-poap.ts
  src/theme/styles.ts
  src/types.ts
Labels: feature

#379 fix: MinMaxAmount formatting with regex
  src/components/create-guild/Requirements/components/MinMaxAmount.tsx
Labels: bug

#377 Guild landing - mobile safari fixes
  src/components/index/Discover.tsx
  src/components/index/ExploreTrendingGuilds.tsx
  src/components/index/PlatformAgnosticCommunities.tsx
Labels: bug

#376 Palm chain
  public/networkLogos/palm.png
  src/connectors/index.ts
  src/hooks/useTokens.ts
Labels: feature

#382 POAP search improvements
  src/components/create-guild/Requirements/components/PoapFormCard/PoapFormCard.tsx
  src/components/create-guild/Requirements/components/PoapFormCard/hooks/useGuildsPoaps.ts
  src/components/create-guild/Requirements/components/PoapFormCard/hooks/usePoapById.ts
Labels: improvement

#394 Method based authentication
  src/hooks/useSubmit.ts
  src/types.ts
  src/utils/fetcher.ts
Labels: improvement

#400 Allowlist - upload .txt/.csv
  src/components/create-guild/Requirements/components/AllowlistFormCard.tsx
Labels: improvement

#399 New guild page UI
  src/components/[guild]/AddRoleButton/AddRoleButton.tsx
  src/components/[guild]/EditGuild/components/Guard.tsx
  src/components/[guild]/LeaveButton/LeaveButton.tsx
  src/components/[guild]/LogicDivider.tsx
  src/components/[guild]/Requirements/Requirements.tsx
  src/components/[guild]/Requirements/components/AllowlistRequirementCard.tsx
  src/components/[guild]/Requirements/components/ExpandRequirementsButton.tsx
  src/components/[guild]/Requirements/components/FreeRequirementCard.tsx
  src/components/[guild]/Requirements/components/NftRequirementCard/NftRequirementCard.tsx
  src/components/[guild]/Requirements/components/SnapshotRequirementCard.tsx
  src/components/[guild]/Requirements/components/TokenRequirementCard/TokenRequirementCard.tsx
  src/components/[guild]/Requirements/components/common/BlockExplorerUrl.tsx
  src/components/[guild]/Requirements/components/common/OpenseaUrl.tsx
  src/components/[guild]/Requirements/components/common/RequirementButton.tsx
  src/components/[guild]/Requirements/components/common/RequirementCard.tsx
  src/components/[guild]/Requirements/components/common/RequirementText.tsx
  src/components/[guild]/RoleCard/RoleCard.tsx
  src/components/[guild]/RoleCard/components/MemberCount.tsx
  src/components/[guild]/RoleCard/index.ts
  src/components/[guild]/RolesByPlatform/RolesByPlatform.tsx
  src/components/[guild]/RolesByPlatform/components/JoinButton/JoinButton.tsx
  src/components/[guild]/RolesByPlatform/components/RoleListItem/RoleListItem.tsx
  src/components/[guild]/RolesByPlatform/components/RoleListItem/components/AccessIndicator/AccessIndicator.tsx
  src/components/[guild]/RolesByPlatform/components/RoleListItem/components/AccessIndicator/components/AccessIndicatorUI.tsx
  src/components/[guild]/RolesByPlatform/hooks/useAccess.ts
  src/components/[guild]/Tabs/Tabs.tsx
  src/components/[guild]/Tabs/components/TabButton.tsx
  src/components/common/Layout/Layout.tsx
  src/components/create-guild/Requirements/components/AllowlistFormCard.tsx
  src/pages/[guild]/index.tsx
  src/theme/components/tag.ts
Labels: improvement
