Repository guildxyz/guild.xyz, pull requests merged in 2023-01, with the labels that each got.

#626 Galxe integration - remove chain picker
  src/requirements/Galaxy/GalaxyForm.tsx
Labels: improvement

#628 feat: Fetch detailed NFT metadata where possible
  src/hooks/useOpenseaAssetData.ts
  src/pages/api/opensea-asset-data/[address].ts
  src/pages/api/opensea-asset-data/[chain]/[address]/[[...tokenId]].ts
  src/requirements/Nft/NftRequirement.tsx
  src/requirements/common/OpenseaUrl.tsx
Labels: feature

#646 Unify requirement components
  src/components/[guild]/Requirements/components/RequirementDisplayComponent.tsx
  src/components/[guild]/RolePlatforms/RolePlatforms.tsx
  src/components/common/DataBlock.tsx
  src/requirements/101/101Requirement.tsx
  src/requirements/Allowlist/AllowlistRequirement.tsx
  src/requirements/Cask/CaskRequirement.tsx
  src/requirements/ContractState/ContractStateRequirement.tsx
  src/requirements/Disco/DiscoRequirement.tsx
  src/requirements/Discord/DiscordRequirement.tsx
  src/requirements/Galaxy/GalaxyRequirement.tsx
  src/requirements/Galaxy/components/ApiError.tsx
  src/requirements/Galaxy/hooks/useGalaxyCampaigns.ts
  src/requirements/GitPoap/GitPoapRequirement.tsx
  src/requirements/Github/GithubRequirement.tsx
  src/requirements/Guild/GuildRequirement.tsx
  src/requirements/Juicebox/JuiceboxRequirement.tsx
  src/requirements/Juicebox/hooks/useJuicebox.ts
  src/requirements/KycDAO/KycDAORequirement.tsx
  src/requirements/KycDAO/hooks/useKycDAOContracts.ts
  src/requirements/Lens/LensRequirement.tsx
  src/requirements/Mirror/MirrorRequirement.tsx
  src/requirements/Mirror/hooks/useMirrorEdition.ts
  src/requirements/Nft/NftRequirement.tsx
  src/requirements/Noox/NooxRequirement.tsx
  src/requirements/Optimism/OptimismRequirement.tsx
  src/requirements/Orange/OrangeRequirement.tsx
  src/requirements/Otterspace/OtterspaceRequirement.tsx
  src/requirements/Parallel/ParallelRequirement.tsx
  src/requirements/Poap/PoapRequirement.tsx
  src/requirements/Poap/hooks/usePoaps.ts
  src/requirements/Rabbithole/RabbitholeRequirement.tsx
  src/requirements/Rep3/Rep3Requirement.tsx
  src/requirements/Sismo/SismoRequirement.tsx
  src/requirements/Sound/SoundRequirement.tsx
  src/requirements/Token/TokenRequirement.tsx
  src/requirements/Twitter/TwitterRequirement.tsx
  src/requirements/Unlock/UnlockRequirement.tsx
  src/requirements/Yup/YupRequirement.tsx
  src/requirements/common/DataBlock.tsx
  src/requirements/common/DataBlockWithCopy.tsx
Labels: improvement

#661 Sound integration update
  src/requirements/Sound/SoundForm.tsx
  src/requirements/Sound/SoundRequirement.tsx
  src/requirements/Sound/components/SoundMinAmount.tsx
  src/requirements/Sound/components/SoundTopCollector.tsx
Labels: feature, improvement

#603 feat: Link address manually
  src/components/[guild]/JoinModal/hooks/useConnectPlatform.ts
  src/components/[guild]/JoinModal/hooks/useJoin.tsx
  src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx
  src/components/common/Layout/components/Account/components/AccountModal/AccountModal.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/AccountConnections.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/LinkAddressButton.tsx
  src/components/create-guild/PlatformsGrid/components/BaseOAuthSelectButton.tsx
  src/components/create-guild/PlatformsGrid/components/GoogleSelectButton.tsx
  src/hooks/useKeyPair.ts
  src/requirements/index.ts
Labels: feature

#640 Multi-tab verification fix
  src/hooks/useKeyPair.ts
Labels: bug

#598 Tessera integration
  public/explorerLogos/tessera.svg
  public/requirementLogos/tessera.png
  src/requirements/Guild/GuildRequirement.tsx
  src/requirements/Tessera/TesseraForm.tsx
  src/requirements/Tessera/TesseraRequirement.tsx
  src/requirements/Tessera/components/Hold.tsx
  src/requirements/Tessera/components/HoldCollection.tsx
  src/requirements/Tessera/components/HoldState.tsx
  src/requirements/Tessera/components/Listings.tsx
  src/requirements/Tessera/components/NumberField.tsx
  src/requirements/Tessera/components/TesseraUrl.tsx
  src/requirements/Tessera/components/VaultField.tsx
  src/requirements/Tessera/hooks/useTesseraVault.ts
  src/requirements/Tessera/hooks/useTesseraVaults.ts
  src/requirements/requirements.ts
Labels: feature

#655 Shield integration
  public/requirementLogos/shield.png
  src/requirements/Shield/ShieldForm.tsx
  src/requirements/Shield/ShieldRequirement.tsx
  src/requirements/Shield/components/TornadoCash.tsx
  src/requirements/requirements.ts
Labels: feature

#581 New auth method with stringified payloads
  package-lock.json
  src/components/[guild]/AddRewardButton/hooks/useAddReward.ts
  src/components/[guild]/CreatePoap/components/Distribution/components/ManageEvent/hooks/useManageEvent.ts
  src/components/[guild]/CreatePoap/components/Requirements/components/MonetizePoap/hooks/useDeleteMonetization.ts
  src/components/[guild]/CreatePoap/components/Requirements/components/MonetizePoap/hooks/useMonetizePoap.ts
  src/components/[guild]/CreatePoap/components/Requirements/components/VoiceParticipation/hooks/useDeleteVoiceRequirement.ts
  src/components/[guild]/CreatePoap/components/Requirements/components/VoiceParticipation/hooks/useEditVoiceRequirement.ts
  src/components/[guild]/CreatePoap/components/Requirements/components/VoiceParticipation/hooks/useSetVoiceRequirement.ts
  src/components/[guild]/CreatePoap/hooks/useSavePoap.ts
  src/components/[guild]/CreatePoap/hooks/useUpdateGuildPoap.ts
  src/components/[guild]/CreatePoap/hooks/useUploadMintLinks.ts
  src/components/[guild]/EditGuild/components/DeleteGuildButton/hooks/useDeleteGuild.ts
  src/components/[guild]/EditGuild/hooks/useEditGuild.ts
  src/components/[guild]/JoinModal/hooks/useConnectPlatform.ts
  src/components/[guild]/JoinModal/hooks/useJoin.tsx
  src/components/[guild]/LeaveButton/hooks/useLeaveGuild.ts
  src/components/[guild]/Onboarding/components/SummonMembers/hooks/useSendJoin.tsx
  src/components/[guild]/RoleCard/components/EditRole/components/DeleteRoleButton/hooks/useDeleteRole.ts
  src/components/[guild]/RoleCard/components/EditRole/hooks/useEditRole.ts
  src/components/[guild]/RolePlatforms/components/PlatformCard/components/useDiscordCardProps/DiscordCardMenu/components/DiscordRewardSettings.tsx.tsx
  src/components/[guild]/RolePlatforms/components/PlatformCard/components/useDiscordCardProps/DiscordCardMenu/hooks/useSyncMembersFromDiscord.ts
  src/components/[guild]/RolePlatforms/components/RemovePlatformButton/hooks/useRemovePlatform.ts
  src/components/common/Layout/components/Account/components/AccountModal/hooks/useDisconnect.ts
  src/components/create-guild/PlatformsGrid/components/BaseOAuthSelectButton.tsx
  src/components/create-guild/PlatformsGrid/components/GoogleSelectButton.tsx
  src/components/create-guild/hooks/useCreateGuild.tsx
  src/components/create-guild/hooks/useCreateRole.tsx
  src/hooks/useKeyPair.ts
  src/hooks/useSubmit/index.ts
  src/hooks/useSubmit/useSubmit.ts
  src/pages/api/poap/index.ts
  src/utils/fetcher.ts
Labels: feature, improvement

#599 Snapshot integration update
  .env
  src/components/[guild]/Requirements/RoleRequirements.tsx
  src/requirements/Snapshot/SnapshotForm.tsx
  src/requirements/Snapshot/SnapshotRequirement.tsx
  src/requirements/Snapshot/components/FollowSince.tsx
  src/requirements/Snapshot/components/MajorityVotes.tsx
  src/requirements/Snapshot/components/ProposalSelect.tsx
  src/requirements/Snapshot/components/Proposals.tsx
  src/requirements/Snapshot/components/SnapshotSpaceLink.tsx
  src/requirements/Snapshot/components/SpaceSelect.tsx
  src/requirements/Snapshot/components/Strategy/Strategy.tsx
  src/requirements/Snapshot/components/Strategy/components/SingleStrategy.tsx
  src/requirements/Snapshot/components/Strategy/index.ts
  src/requirements/Snapshot/components/StrategyParamsTable.tsx
  src/requirements/Snapshot/components/UserSince.tsx
  src/requirements/Snapshot/components/Votes.tsx
  src/requirements/Snapshot/hooks/useProposal.ts
  src/requirements/Snapshot/hooks/useProposals.ts
  src/requirements/Snapshot/hooks/useSnapshots.ts
  src/requirements/Snapshot/hooks/useSpace.ts
  src/requirements/Snapshot/hooks/useSpaces.ts
  src/requirements/Snapshot/hooks/useStrategyParamsArray.ts
  src/requirements/common/ChainPicker.tsx
  src/requirements/index.ts
  src/requirements/requirements.ts
Labels: feature, improvement
