Repository guildxyz/guild.xyz, pull requests merged in 2023-09, with the labels that each got.

#879 Fix invalid form default values
  src/components/[guild]/CreatePoap/components/PoapRoleCard/PoapRoleCard.tsx
  src/components/[guild]/RoleCard/RoleCard.tsx
  src/components/[guild]/hooks/useGuild.ts
  src/hooks/useSWRWithOptionalAuth.ts
  src/pages/[guild]/index.tsx
Labels: bug

#880 hotfix: optional auth SWR error
  src/hooks/useSWRWithOptionalAuth.ts
Labels: bug

#883 feat(NFT reward): add more PostHog events
  src/components/[guild]/AddRewardButton/hooks/useAddReward.ts
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddContractCallPanel/components/CreateNftForm/hooks/useCreateNft.ts
  src/platforms/ContractCall/ContractCallReward.tsx
  src/platforms/ContractCall/ContractCallRewardCardButton.tsx
Labels: improvement

#886 Separate requests for contacts, admins and featureFlags
  package-lock.json
  src/components/[guild]/EditGuild/EditGuildDrawer.tsx
  src/components/[guild]/EditGuild/hooks/useEditGuild.ts
  src/components/[guild]/Onboarding/components/SummonMembers/SummonMembers.tsx
  src/types.ts
  src/utils/fetcher.ts
  src/utils/handleSubmitDirty.ts
Labels: improvement

#887 fix: put `addressLinkParams` in its own context
  src/components/_app/AddressLinkProvider.tsx
  src/components/_app/KeyPairProvider.tsx
  src/components/_app/Web3ConnectionManager/Web3ConnectionManager.tsx
  src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/hooks/useShouldLinkToUser.ts
  src/components/common/Layout/components/Account/components/AccountModal/components/LinkAddressButton.tsx
  src/pages/_app.tsx
Labels: bug

#729 Activity log
  package-lock.json
  package.json
  src/components/[guild]/Tabs/Tabs.tsx
  src/components/[guild]/Tabs/index.ts
  src/components/[guild]/activity/ActivityLogAction/ActivityLogAction.tsx
  src/components/[guild]/activity/ActivityLogAction/ActivityLogActionContext.tsx
  src/components/[guild]/activity/ActivityLogAction/components/ActionIcon.tsx
  src/components/[guild]/activity/ActivityLogAction/components/ActionLabel.tsx
  src/components/[guild]/activity/ActivityLogAction/components/ActivityLogChildAction.tsx
  src/components/[guild]/activity/ActivityLogAction/components/BeforeAfterActions.tsx
  src/components/[guild]/activity/ActivityLogAction/components/GuildTag.tsx
  src/components/[guild]/activity/ActivityLogAction/components/IdentityTag.tsx
  src/components/[guild]/activity/ActivityLogAction/components/MoreActions.tsx
  src/components/[guild]/activity/ActivityLogAction/components/RewardTag.tsx
  src/components/[guild]/activity/ActivityLogAction/components/RoleTag.tsx
  src/components/[guild]/activity/ActivityLogAction/components/UpdatedDataGrid.tsx
  src/components/[guild]/activity/ActivityLogAction/components/UserTag.tsx
  src/components/[guild]/activity/ActivityLogAction/index.ts
  src/components/[guild]/activity/ActivityLogContext.tsx
  src/components/[guild]/activity/ActivityLogFiltersBar/ActivityLogFiltersBar.tsx
  src/components/[guild]/activity/ActivityLogFiltersBar/components/ActivityLogFiltersContext.tsx
  src/components/[guild]/activity/ActivityLogFiltersBar/components/DateRangeInput.tsx
  src/components/[guild]/activity/ActivityLogFiltersBar/components/Dropdown.tsx
  src/components/[guild]/activity/ActivityLogFiltersBar/components/FilterTag/FilterTag.tsx
  src/components/[guild]/activity/ActivityLogFiltersBar/components/FilterTag/components/ActionSuggestons.tsx
  src/components/[guild]/activity/ActivityLogFiltersBar/components/FilterTag/components/NoResults.tsx
  src/components/[guild]/activity/ActivityLogFiltersBar/components/FilterTag/components/RewardSuggestions.tsx
  src/components/[guild]/activity/ActivityLogFiltersBar/components/FilterTag/components/RoleSuggestions.tsx
  src/components/[guild]/activity/ActivityLogFiltersBar/components/FilterTag/index.ts
  src/components/[guild]/activity/ActivityLogFiltersBar/components/FiltersInput.tsx
  src/components/[guild]/activity/ActivityLogFiltersBar/components/Suggestion.tsx
  src/components/[guild]/activity/ActivityLogFiltersBar/index.ts
  src/components/[guild]/activity/ActivityLogSkeleton.tsx
  src/components/[guild]/activity/constants.ts
  src/components/_app/Web3ConnectionManager/Web3ConnectionManager.tsx
  src/components/balancy/BalancyBar.tsx
  src/components/common/ErrorAlert.tsx
  src/components/common/Layout/StickyBar.tsx
  src/components/common/Layout/components/Account/Account.tsx
  src/components/common/Layout/components/Account/components/AccountButton.tsx
  src/components/common/Layout/components/Account/components/NetworkModal/NetworkModal.tsx
  src/components/common/Layout/components/Account/components/NetworkModal/components/NetworkButton.tsx
  src/components/common/Layout/components/Account/components/NetworkModal/components/NetworkButtonsList.tsx
  src/components/common/Layout/components/Account/components/NetworkModal/index.ts
  src/components/common/Layout/components/Account/components/UserActivityLogPopover.tsx
  src/components/explorer/ExploreAllGuilds.tsx
  src/components/explorer/ExplorerTabs.tsx
  src/components/explorer/GoToCreateGuildButton.tsx
  src/pages/[guild]/activity.tsx
  src/pages/[guild]/index.tsx
  src/pages/explorer.tsx
  src/pages/profile/activity.tsx
  src/requirements/PolygonId/PolygonIdRequirement.tsx
  src/static/avatars/ghost.svg
  src/utils/requestNetworkChange.ts
Labels: feature

#888 fix: add userId to generatedKeyPair SWR key
  src/components/_app/KeyPairProvider.tsx
  src/components/common/Layout/components/Account/components/AccountModal/AccountModal.tsx
Labels: bug

#889 feat: send access check error codes to intercom
  src/components/[guild]/hooks/useAccess.ts
Labels: feature

#890 feat: display correlation id on error toasts
  src/components/[guild]/AddAndOrderRoles/hooks/useReorderRoles.ts
  src/components/[guild]/AddRewardButton/hooks/useAddReward.ts
  src/components/[guild]/CreatePoap/hooks/useUpdateGuildPoap.ts
  src/components/[guild]/CreatePoap/hooks/useUploadMintLinks.ts
  src/components/[guild]/EditGuild/hooks/useEditGuild.ts
  src/components/[guild]/JoinModal/hooks/useConnectPlatform.ts
  src/components/[guild]/LeaveButton/hooks/useLeaveGuild.ts
  src/components/[guild]/Onboarding/components/SummonMembers/hooks/useSendJoin.tsx
  src/components/[guild]/ResendRewardButton.tsx
  src/components/[guild]/RoleCard/components/EditRole/hooks/useEditRole.ts
  src/components/[guild]/collect/components/CollectNftButton.tsx
  src/components/create-guild/hooks/useCreateGuild.tsx
  src/components/create-guild/hooks/useCreateRole.tsx
  src/hooks/useShowErrorToast.ts
  src/hooks/useShowErrorToast.tsx
  src/requirements/Captcha/hooks/useVerifyCaptcha.ts
  src/utils/fetcher.ts
Labels: feature, improvement

#891 PulseMarker and tryToParseJSON refactor
  src/components/common/PulseMarker.tsx
  src/components/common/PulseMarker/Marker.tsx
  src/components/common/PulseMarker/PulseMarker.tsx
  src/components/common/PulseMarker/index.ts
  src/utils/tryToParseJSON.ts
Labels: bug

#892 NFT reward: improve wysiwyg editor
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddContractCallPanel/components/CreateNftForm/components/RichTextDescriptionEditor.tsx
  src/components/[guild]/collect/components/RichTextDescription.tsx
  src/components/lexical/nodes/ImageNode.tsx
  src/components/lexical/plugins/ImagesPlugin.tsx
  src/components/lexical/plugins/ToolbarPlugin/ToolbarPlugin.tsx
  src/components/lexical/plugins/ToolbarPlugin/components/ImageEditor.tsx
  src/components/lexical/plugins/ToolbarPlugin/components/LinkEditor.tsx
  src/components/lexical/plugins/ToolbarPlugin/index.ts
Labels: feature, improvement

#897 feat(profile/activity): filter by guild
  src/components/[guild]/activity/ActivityLogAction/components/ActionLabel.tsx
  src/components/[guild]/activity/ActivityLogAction/components/GuildTag.tsx
  src/components/[guild]/activity/ActivityLogFiltersBar/components/ActivityLogFiltersContext.tsx
  src/components/[guild]/activity/ActivityLogFiltersBar/components/FilterTag/FilterTag.tsx
  src/components/[guild]/activity/ActivityLogFiltersBar/components/FilterTag/components/GuildSuggestions.tsx
  src/components/[guild]/activity/ActivityLogFiltersBar/components/FiltersInput.tsx
Labels: feature, improvement

#902 feat(useResolveAddress): save resolved name to IDB
  src/hooks/resolving/useResolveAddress.ts
Labels: improvement

#894 V2 - Use migrated endpoints
  cypress/e2e/1-discord/0-create-guild.spec.ts
  src/components/[guild]/CreatePoap/components/Distribution/components/SendPoapDiscordEmbed/SendPoapDiscordEmbed.tsx
  src/components/[guild]/CreatePoap/components/EditPoapRole/EditPoapRole.tsx
  src/components/[guild]/CreatePoap/hooks/useMintPoapButton.tsx
  src/components/[guild]/CreatePoap/hooks/usePoapLinks.ts
  src/components/[guild]/CreatePoap/hooks/useUpdatePoapRequirements.ts
  src/components/[guild]/CreatePoap/hooks/useUploadMintLinks.ts
  src/components/[guild]/EditGuild/components/TransferOwnership/TransferOwnership.tsx
  src/components/[guild]/EditGuild/components/TransferOwnership/hooks/useTransferOwnership.ts
  src/components/[guild]/EditGuild/components/UrlName.tsx
  src/components/[guild]/EditGuild/hooks/useEditGuild.ts
  src/components/[guild]/JoinModal/hooks/useJoin.tsx
  src/components/[guild]/Members/components/MembersExporter.tsx
  src/components/[guild]/Onboarding/components/SummonMembers/components/SendDiscordJoinButtonModal.tsx
  src/components/[guild]/Onboarding/components/SummonMembers/hooks/useSendJoin.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/MintGuildPinContext.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/GuildPinImage.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/buttons/BuyButton.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/hooks/useMintGuildPin.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/hooks/usePayFee.ts
  src/components/[guild]/claim-poap/hooks/useClaimPoap.ts
  src/components/[guild]/claim-poap/hooks/usePoapPayFee.ts
  src/components/[guild]/claim-poap/hooks/useUserPoapEligibility.ts
  src/components/[guild]/hooks/useAutoStatusUpdate.ts
  src/components/create-guild/Requirements/components/RequirementEditableCard.tsx
  src/components/create-guild/TelegramGroup/hooks/useIsTGBotIn.ts
  src/components/explorer/hooks/useMemberships.ts
  src/components/index/ExploreTrendingGuilds.tsx
  src/hooks/useGateables.ts
  src/hooks/useServerData.ts
  src/hooks/useTokenData.ts
  src/pages/api/linkpreview/[timestamp]/[guild].tsx
  src/pages/api/poap/can-claim/[poapId]/[guildId].ts
  src/pages/api/poap/get-withdrawable-amount/[guildId]/[poapId].ts
  src/platforms/Discord/DiscordCardMenu/components/DiscordCaptchaSwitch.tsx
  src/platforms/Discord/DiscordCardMenu/components/DiscordRewardSettings.tsx.tsx
  src/platforms/hooks/usePlatformUsageInfo.ts
  src/requirements/Captcha/components/CompleteCaptcha.tsx
  src/requirements/Galaxy/hooks/useGalaxyCampaigns.ts
  src/requirements/Juicebox/hooks/useJuicebox.ts
  src/requirements/Nft/NftRequirement.tsx
  src/requirements/Nft/hooks/useNftMetadata.ts
  src/requirements/Nft/hooks/useNftType.ts
  src/requirements/Nft/hooks/useNfts.ts
  src/requirements/Poap/hooks/useGuildsPoaps.ts
  src/requirements/Poap/hooks/usePoapById.ts
  src/requirements/Poap/hooks/usePoaps.ts
  src/requirements/PoapPayment/hooks/useRegisterVault.ts
  src/requirements/PoapVoice/hooks/usePoapEventDetails.ts
  src/requirements/PolygonId/components/ConnectPolygonID.tsx
  src/requirements/Snapshot/SnapshotRequirement.tsx
  src/requirements/Snapshot/components/SnapshotSpaceLink.tsx
  src/requirements/Snapshot/components/SpaceSelect.tsx
  src/requirements/Snapshot/components/Strategy/components/SingleStrategy.tsx
  src/requirements/Snapshot/hooks/useProposals.ts
  src/requirements/Twitter/TwitterRequirement.tsx
  src/requirements/Twitter/components/TwitterUserInput.tsx
Labels: improvement

#901 feat: ReportGuildButton
  src/components/[guild]/ReportGuildButton.tsx
  src/components/[guild]/collect/components/ShareButton.tsx
  src/pages/[guild]/collect/[chain]/[address].tsx
Labels: feature

#893 Email identity
  src/components/[guild]/JoinModal/components/ConnectPlatform.tsx
  src/components/[guild]/JoinModal/hooks/useConnectPlatform.ts
  src/components/_app/Web3ConnectionManager/Web3ConnectionManager.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/AccountConnections.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/SocialAccount.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/SocialAccount/EmailAddress.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/SocialAccount/SocialAccount.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/SocialAccount/components/DisconnectAccountButton.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/SocialAccount/components/SocialAccountUI.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/SocialAccount/index.ts
  src/components/common/Layout/components/Account/components/AccountModal/components/SocialAccount/utils/processEmailError.ts
  src/components/common/Layout/components/Account/components/AccountModal/hooks/useDisconnect.ts
  src/components/create-guild/PlatformsGrid/PlatformsGrid.tsx
  src/platforms/platforms.tsx
  src/types.ts
Labels: feature

#906 NFT reward UX improvements
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddContractCallPanel/components/CreateNftForm/CreateNftForm.tsx
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddContractCallPanel/components/CreateNftForm/components/ImagePicker.tsx
  src/components/[guild]/collect/components/Details/components/BlockExplorerLink.tsx
  src/components/[guild]/collect/components/Links.tsx
  src/components/[guild]/collect/components/ShareButton.tsx
  src/hooks/useDropzone.ts
  src/pages/[guild]/collect/[chain]/[address].tsx
  src/pages/[guild]/index.tsx
  src/platforms/ContractCall/CollectNftModalButton.tsx
  src/platforms/ContractCall/ContractCallRewardCardButton.tsx
  src/types.ts
Labels: improvement

#908 Remove Visibility, Payment, NFT Reward feature flags
  src/components/[guild]/AddRewardButton/hooks/useAddReward.ts
  src/components/[guild]/EditGuild/components/FeatureFlags.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/BuyPass.tsx
  src/components/[guild]/RoleCard/components/EditRole/hooks/useEditRole.ts
  src/components/[guild]/SetVisibility.tsx
  src/components/common/RadioSelect/components/RadioOption.tsx
  src/components/create-guild/PlatformsGrid/PlatformsGrid.tsx
  src/components/create-guild/PlatformsGrid/components/PlatformSelectButton.tsx
  src/components/create-guild/Requirements/components/AddRequirement.tsx
  src/components/create-guild/hooks/useCreateRole.tsx
  src/platforms/platforms.tsx
Labels: feature

#903 Guild Pin UX improvements
  src/components/[guild]/AccessHub/AccessHub.tsx
  src/components/[guild]/AccessHub/components/GuildPinRewardCard.tsx
  src/components/[guild]/EditGuild/EditGuildButton.tsx
  src/components/[guild]/EditGuild/EditGuildDrawer.tsx
  src/components/[guild]/EditGuild/EditGuildDrawerContext.tsx
  src/components/[guild]/EditGuild/components/SaveAlert.tsx
  src/components/[guild]/EditGuild/hooks/useEditGuild.ts
  src/components/[guild]/JoinModal/hooks/useJoin.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/MintGuildPin/MintGuildPin.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/MintGuildPin/components/ActivateGuildPinForm.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/MintGuildPin/components/ActivateGuildPinModal.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/MintGuildPin/index.ts
  src/components/[guild]/Requirements/components/GuildCheckout/MintGuildPinContext.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/GuildPinFees.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/GuildPinImage.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/MintGuildPinChainPicker.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/TransactionStatusModal/components/OpenseaLink.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/buttons/MintGuildPinButton.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/hooks/useGuildPinContractsData.ts
  src/components/[guild]/Requirements/components/GuildCheckout/hooks/useGuildPinFee.ts
  src/components/[guild]/Requirements/components/GuildCheckout/hooks/useMintGuildPin.tsx
  src/components/[guild]/RoleCard/components/EditRole/EditRole.tsx
  src/components/[guild]/RoleCard/components/EditRole/hooks/useEditRole.ts
  src/components/[guild]/ThemeContext.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/UsersGuildCredentials/GuildPin.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/UsersGuildCredentials/UsersGuildPins.tsx
  src/components/create-guild/hooks/useCreateRole.tsx
  src/hooks/useUsersGuildPins.ts
  src/pages/[guild]/index.tsx
  src/requirements/Nft/NftRequirement.tsx
  src/types.ts
  src/utils/convertSVGToPNG.ts
  src/utils/guildCheckout/constants.ts
  src/utils/preprocessRequirements.ts
Labels: improvement

#910 Email requirements
  src/components/[guild]/Requirements/components/ConnectRequirementPlatformButton.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/SocialAccount/EmailAddress.tsx
  src/components/create-guild/Requirements/components/AddRequirement.tsx
  src/requirements/Email/EmailForm.tsx
  src/requirements/Email/EmailRequirement.tsx
  src/requirements/requirements.ts
Labels: feature

#905 feat: event source editor & new sources
  .env
  next.config.js
  public/platforms/eventbrite.png
  public/platforms/link3.png
  public/platforms/luma.png
  src/components/[guild]/EditGuild/EditGuildDrawer.tsx
  src/components/[guild]/EditGuild/components/Events/EventInput.tsx
  src/components/[guild]/EditGuild/components/Events/Events.tsx
  src/components/[guild]/Events/DiscordEventCard/index.ts
  src/components/[guild]/Events/EventCard/EventCard.tsx
  src/components/[guild]/Events/EventCard/components/EventImage.tsx
  src/components/[guild]/Events/EventCard/components/EventInfo.tsx
  src/components/[guild]/Events/EventCard/components/JoinEventButton.tsx
  src/components/[guild]/Events/EventCard/index.ts
  src/hooks/useDiscordEvents.ts
  src/hooks/useGuildEvents.ts
  src/pages/[guild]/events.tsx
  src/types.ts
  src/utils/handleSubmitDirty.ts
Labels: feature

#911 platformGuildData: rename `image` to `imageUrl`
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddContractCallPanel/components/CreateNftForm/hooks/useCreateNft.ts
  src/components/[guild]/collect/hooks/useNftDetails.ts
  src/platforms/ContractCall/useContractCallCardProps.ts
  src/types.ts
Labels: feature
