Repository guildxyz/guild.xyz, pull requests merged in 2023-05, with the labels that each got.

#788 Requests optimization & signature fix
  src/components/[guild]/hooks/useGuild.ts
  src/hooks/useSWRWithOptionalAuth.ts
  src/pages/[guild]/index.tsx
Labels: improvement

#789 fix: delete Discord roles after E2E test runs
  .github/workflows/e2e-tests.yaml
  cypress/e2e/1-discord/1-cleanup.spec.ts
  synpress.config.ts
Labels: improvement

#790 feat: detailed FeeTable component
  src/components/[guild]/Requirements/components/GuildCheckout/components/BuyTotal.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/FeesTable.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/PurchaseFeeAndTotal.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/buttons/PurchaseAllowanceButton.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/buttons/PurchaseButton.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/hooks/usePayFee.ts
  src/components/[guild]/Requirements/components/GuildCheckout/hooks/usePurchaseAsset.ts
  src/pages/api/fetchPrice.ts
  src/utils/guildCheckout/utils.ts
Labels: feature

#759 Guild Credentials
  package-lock.json
  public/img/guild-credential-key-3d.svg
  public/landing/bg_light.svg
  public/networkLogos/ethereum.svg
  public/networkLogos/polygon.svg
  public/networkLogos/zksync-era.svg
  src/components/[guild]/AccessHub/AccessHub.tsx
  src/components/[guild]/AccessHub/components/GuildCredentialRewardCard.tsx
  src/components/[guild]/EditGuild/components/FeatureFlags.tsx
  src/components/[guild]/JoinModal/hooks/useJoin.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/BuyPass.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/MintCredential.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/MintCredentialContext.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/PurchaseRequirement.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/CredentialFees.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/CredentialImage.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/CredentialReward.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/GuildCheckoutContex.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/MintCredentialChainPicker.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/TransactionStatusModal/TransactionStatusModal.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/TransactionStatusModal/components/OpenseaLink.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/TransactionStatusModal/components/TransactionLink.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/TransactionStatusModal/components/TxInProgress.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/TransactionStatusModal/components/TxSuccess.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/buttons/MintCredentialButton.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/buttons/SwitchNetworkButton.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/hooks/useCredentialFee.ts
  src/components/[guild]/Requirements/components/GuildCheckout/hooks/useMintCredential.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/hooks/useSubmitTransaction.ts
  src/components/common/Button.tsx
  src/components/common/ColorCard/ColorCardLabel.tsx
  src/components/common/RewardCard.tsx
  src/connectors/index.ts
  src/hooks/useUsersGuildCredentials.ts
  src/pages/[guild]/index.tsx
  src/requirements/PoapPayment/components/BuyPoapRequirement.tsx
  src/static/abis/guildCredential.json
  src/theme/colors.ts
  src/types.ts
  src/utils/guildCheckout/constants.ts
Labels: feature

#795 fix: optional auth invalid timestamp
  src/utils/fetcher.ts
Labels: bug

#772 Add new supported chains
  public/networkLogos/scroll.png
  public/networkLogos/zetachain.svg
  src/connectors/index.ts
  src/hooks/useTokens.ts
Labels: feature

#784 feat: Purchase requirements - BSC support
  src/components/[guild]/Requirements/components/GuildCheckout/hooks/usePurchaseAsset.ts
  src/utils/guildCheckout/constants.ts
Labels: feature

#794 Guild Credentials improvements
  public/img/guild-pin-key-3d.svg
  src/components/[guild]/AccessHub/AccessHub.tsx
  src/components/[guild]/AccessHub/components/GuildCredentialRewardCard.tsx
  src/components/[guild]/AccessHub/components/GuildPinRewardCard.tsx
  src/components/[guild]/EditGuild/EditGuildDrawer.tsx
  src/components/[guild]/JoinModal/hooks/useJoin.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/MintCredentialContext.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/MintGuildPin.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/MintGuildPinContext.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/GuildPinFees.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/GuildPinImage.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/GuildPinReward.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/MintGuildPinChainPicker.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/TransactionStatusModal/components/OpenseaLink.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/buttons/MintCredentialButton.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/buttons/MintGuildPinButton.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/hooks/useCredentialFee.ts
  src/components/[guild]/Requirements/components/GuildCheckout/hooks/useGuildPinFee.ts
  src/components/[guild]/Requirements/components/GuildCheckout/hooks/useMintGuildPin.tsx
  src/components/common/DiscordGuildSetup/components/ServerSetupCard/ServerSetupCard.tsx
  src/components/common/Layout/components/Account/components/AccountModal/AccountModal.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/UsersGuildCredentials/GuildPin.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/UsersGuildCredentials/GuildPinSkeleton.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/UsersGuildCredentials/UsersGuildPins.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/UsersGuildCredentials/index.ts
  src/components/create-guild/BasicInfo/BasicInfo.tsx
  src/components/create-guild/IconSelector/IconSelector.tsx
  src/components/create-guild/IconSelector/components/PhotoUploader.tsx
  src/hooks/useUsersGuildCredentials.ts
  src/hooks/useUsersGuildPins.ts
  src/pages/[guild]/index.tsx
  src/static/abis/guildPin.json
  src/types.ts
  src/utils/guildCheckout/constants.ts
Labels: feature, improvement

#800 feat(E2E tests): upload artifacts
  .github/workflows/e2e-tests.yaml
Labels: feature, improvement

#802 feat: zkSync Era support
  src/connectors/index.ts
  src/hooks/useTokens.ts
Labels: feature

#801 feat: Save non-purchasable assets to Vercel KV
  package-lock.json
  package.json
  src/components/[guild]/EditGuild/components/FeatureFlags.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/DynamicPurchaseRequirement.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/PurchaseRequirement.tsx
  src/components/[guild]/hooks/useNonPurchasableAssets.ts
  src/pages/api/fetchPrice.ts
  src/pages/api/nonPurchasableAssets.ts
  src/requirements/Nft/NftRequirement.tsx
  src/requirements/Token/TokenRequirement.tsx
  src/utils/guildCheckout/constants.ts
Labels: feature
