Repository guildxyz/guild.xyz, pull requests merged in 2023-03, with the labels that each got.

#707 Visibility
  src/components/[guild]/AddRoleButton/AddRoleButton.tsx
  src/components/[guild]/JoinModal/JoinModal.tsx
  src/components/[guild]/JoinModal/hooks/useJoin.tsx
  src/components/[guild]/LeaveButton/hooks/useLeaveGuild.ts
  src/components/[guild]/Members/components/MembersExporter.tsx
  src/components/[guild]/Requirements/RoleRequirements.tsx
  src/components/[guild]/Requirements/components/Requirement.tsx
  src/components/[guild]/Requirements/components/RequirementDisplayComponent.tsx
  src/components/[guild]/RoleCard/RoleCard.tsx
  src/components/[guild]/RoleCard/components/EditRole/EditRole.tsx
  src/components/[guild]/RoleCard/components/EditRole/hooks/useEditRole.ts
  src/components/[guild]/RoleCard/components/Reward.tsx
  src/components/[guild]/RolePlatforms/RolePlatforms.tsx
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddDiscordPanel.tsx
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddGithubPanel.tsx
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddGooglePanel.tsx
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddTelegramPanel.tsx
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/SelectExistingPlatform.tsx
  src/components/[guild]/SetVisibility.tsx
  src/components/[guild]/Visibility.tsx
  src/components/[guild]/hooks/useAccess.ts
  src/components/[guild]/hooks/useAutoStatusUpdate.ts
  src/components/[guild]/hooks/useGuild.ts
  src/components/[guild]/hooks/useUser.ts
  src/components/common/DrawerHeader.tsx
  src/components/common/Layout/components/Account/components/AccountModal/hooks/useDisconnect.ts
  src/components/common/RadioSelect/RadioSelect.tsx
  src/components/common/RadioSelect/components/RadioOption.tsx
  src/components/common/RewardCard.tsx
  src/components/create-guild/PlatformsGrid/components/PlatformSelectButton.tsx
  src/components/create-guild/Requirements/components/AddRequirement.tsx
  src/components/create-guild/Requirements/components/RequirementEditableCard.tsx
  src/components/create-guild/hooks/useCreateRole.tsx
  src/components/explorer/hooks/useMemberships.ts
  src/hooks/useGuildByPlatformId.ts
  src/hooks/useKeyPair.ts
  src/hooks/useSWRWithOptionalAuth.ts
  src/pages/[guild]/index.tsx
  src/types.ts
  src/utils/fetcher.ts
Labels: feature

#718 Upgrade dependencies
  package-lock.json
  package.json
  src/components/[guild]/Onboarding/Onboarding.tsx
  src/components/common/DynamicSteps.tsx
  src/pages/create-guild.tsx
  src/theme/components/index.ts
  src/theme/components/steps.ts
Labels: improvement

#714 Captcha as requirement
  package-lock.json
  package.json
  src/components/[guild]/Requirements/components/RequiementAccessIndicator.tsx
  src/components/create-guild/Requirements/components/AddRequirement.tsx
  src/requirements/Captcha/CaptchaForm.tsx
  src/requirements/Captcha/CaptchaRequirement.tsx
  src/requirements/Captcha/components/CompleteCaptcha.tsx
  src/requirements/Captcha/hooks/useVerifyCaptcha.ts
  src/requirements/requirements.ts
Labels: feature

#719 feat(DiscordRewardSettings): inline captcha switch
  package-lock.json
  src/components/common/Switch.tsx
  src/platforms/Discord/DiscordCardMenu/DiscordCardMenu.tsx
  src/platforms/Discord/DiscordCardMenu/components/DiscordCaptchaSwitch.tsx
  src/types.ts
Labels: feature

#710 feat: Fetch Snapshot assets from the Guild API
  .env
  src/requirements/Galaxy/hooks/useGalaxyCampaigns.ts
  src/requirements/Juicebox/hooks/useJuicebox.ts
  src/requirements/Snapshot/SnapshotRequirement.tsx
  src/requirements/Snapshot/components/ProposalSelect.tsx
  src/requirements/Snapshot/components/SnapshotSpaceLink.tsx
  src/requirements/Snapshot/components/SpaceSelect.tsx
  src/requirements/Snapshot/components/Strategy/components/SingleStrategy.tsx
  src/requirements/Snapshot/hooks/useProposal.ts
  src/requirements/Snapshot/hooks/useProposals.ts
  src/requirements/Snapshot/hooks/useSnapshots.ts
  src/requirements/Snapshot/hooks/useSpace.ts
  src/requirements/Snapshot/hooks/useSpaces.ts
Labels: feature, improvement, waiting for BE

#730 Feature flags - guild edit fix
  src/components/[guild]/EditGuild/EditGuildDrawer.tsx
Labels: bug

#727 Show alert if `hasJoinButton` is false
  src/components/[guild]/Onboarding/components/SummonMembers/SummonMembers.tsx
  src/components/[guild]/Onboarding/components/SummonMembers/components/SendDiscordJoinButtonAlert.tsx
  src/components/common/OnboardingMarker.tsx
  src/components/common/PulseMarker.tsx
Labels: improvement

#728 Auth header flag
  src/utils/fetcher.ts
Labels: improvement

#731 Add `isHidden` to `Requirement` & remove type casts
  src/components/[guild]/Requirements/RoleRequirements.tsx
  src/components/[guild]/Requirements/components/RequirementDisplayComponent.tsx
  src/types.ts
Labels: improvement

#732 Fetch Twitter avatars from the Guild API
  src/requirements/Twitter/TwitterRequirement.tsx
  src/requirements/Twitter/components/TwitterUserInput.tsx
Labels: feature

#733 Popup messaging rework
  src/components/[guild]/JoinModal/hooks/useConnectPlatform.ts
  src/components/[guild]/JoinModal/hooks/useDCAuth.ts
  src/components/[guild]/JoinModal/hooks/useGHAuth.ts
  src/components/[guild]/JoinModal/hooks/useOauthPopupWindow.ts
  src/components/[guild]/JoinModal/hooks/useTwitterAuth.ts
  src/components/_app/Web3ConnectionManager/Web3ConnectionManager.tsx
  src/components/_app/Web3ConnectionManager/hooks/useConnectFromLocalStorage.ts
  src/hooks/usePopupWindow.ts
  src/pages/oauth.tsx
  src/types.ts
  src/utils/timeoutPromise.ts
Labels: improvement

#736 Info toast if smart contract wallet is on wrong chain
  src/components/_app/Web3ConnectionManager/Web3ConnectionManager.tsx
  src/hooks/useContractWalletInfoToast.ts
Labels: feature

#740 Generalized time inputs
  src/components/common/RelativeTimeInput.tsx
  src/components/common/TimestampInput.tsx
  src/requirements/Captcha/CaptchaForm.tsx
  src/requirements/Discord/components/DiscordJoin.tsx
  src/requirements/Discord/components/DiscordJoinFromNow.tsx
  src/requirements/Discord/components/DiscordMemberSince.tsx
  src/requirements/PolygonId/components/PolygonIdProofAge.tsx
  src/requirements/Snapshot/components/FollowSince.tsx
  src/requirements/Snapshot/components/UserSince.tsx
  src/requirements/Twitter/components/TwitterAccountAge.tsx
  src/requirements/Twitter/components/TwitterAccountAgeRelative.tsx
Labels: improvement

#748 Handle invisible role in guild requirement
  src/requirements/Guild/GuildRequirement.tsx
Labels: bug
