Repository guildxyz/guild.xyz, pull requests merged in 2023-08, with the labels that each got.

#862 Covalent wallet activity requirements
  src/requirements/WalletActivity/WalletActivityForm.tsx
  src/requirements/WalletActivity/WalletActivityRequirement.tsx
  src/requirements/WalletActivity/components/BlockNumberFormControl.tsx
  src/requirements/requirements.ts
  src/utils/preprocessRequirements.ts
Labels: improvement

#864 Fix non-discord templated guild creation
  src/components/create-guild/CreateGuildContext.tsx
Labels: bug

#863 Captcha verification of users
  .env
  package-lock.json
  package.json
  src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx
  src/hooks/useKeyPair.ts
  src/pages/_app.tsx
  src/theme/styles.ts
  src/types.ts
Labels: improvement

#853 feat: Guild Pin Mystery Box claiming
  package-lock.json
  package.json
  public/img/guild-mystery-box.jpg
  public/img/mystery-box.webp
  src/components/leaderboard/MysteryBoxCard.tsx
  src/components/leaderboard/UsersLeaderboardPositionCard.tsx
  src/components/leaderboard/hooks/useClaimMysteryBox.ts
  src/components/leaderboard/hooks/useHasAlreadyClaimedMysteryBox.ts
  src/components/leaderboard/hooks/useIsEligibleForMysteryBox.ts
  src/components/leaderboard/hooks/useUsersLeaderboardPosition.ts
  src/pages/api/leaderboard/mystery-box/[address].ts
  src/pages/api/leaderboard/mystery-box/index.ts
  src/pages/leaderboard.tsx
Labels: feature

#870 Remove v2 A/B test
  src/components/[guild]/AccessHub/hooks/useRemoveGuildPlatform.ts
  src/components/[guild]/AddAndOrderRoles/components/OrderRolesModal.tsx
  src/components/[guild]/AddAndOrderRoles/hooks/useReorderRoles.ts
  src/components/[guild]/CreatePoap/components/Distribution/Distribution.tsx
  src/components/[guild]/CreatePoap/hooks/useSavePoap.ts
  src/components/[guild]/CreatePoap/hooks/useUpdateGuildPoap.ts
  src/components/[guild]/EditGuild/EditGuildDrawer.tsx
  src/components/[guild]/EditGuild/components/Admins/Admins.tsx
  src/components/[guild]/EditGuild/components/DeleteGuildButton/hooks/useDeleteGuild.ts
  src/components/[guild]/EditGuild/hooks/useEditGuild.ts
  src/components/[guild]/JoinModal/hooks/useConnectPlatform.ts
  src/components/[guild]/RoleCard/components/EditRole/EditRole.tsx
  src/components/[guild]/RoleCard/components/EditRole/components/DeleteRoleButton/hooks/useDeleteRole.ts
  src/components/[guild]/RoleCard/components/EditRole/hooks/useEditRole.ts
  src/components/[guild]/RolePlatforms/components/RemovePlatformButton/hooks/useRemovePlatform.ts
  src/components/[guild]/hooks/useGuild.ts
  src/components/[guild]/hooks/useUser.ts
  src/components/_app/IntercomProvider.tsx
  src/components/common/Layout/components/Account/components/AccountModal/AccountModal.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/LinkedAddress.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/SocialAccount.tsx
  src/components/common/Layout/components/Account/components/AccountModal/hooks/useDisconnect.ts
  src/components/create-guild/Requirements/components/RequirementEditableCard.tsx
  src/components/create-guild/hooks/useCreateGuild.tsx
  src/components/create-guild/hooks/useCreateRole.tsx
  src/components/explorer/YourGuilds.tsx
  src/hooks/useIsV2.ts
  src/hooks/useKeyPair.ts
Labels: improvement

#865 platforms.ts & add reward modal refactor
  public/platforms/discord_bg.png
  public/platforms/github_bg.png
  public/platforms/google_bg.png
  public/platforms/poap_bg.png
  public/platforms/telegram_bg.png
  src/components/[guild]/AddAndOrderRoles/components/AddRoleDrawer.tsx
  src/components/[guild]/AddRewardButton/AddRewardButton.tsx
  src/components/[guild]/AddRewardButton/hooks/useAddReward.ts
  src/components/[guild]/AddRewardButton/hooks/useSetRoleImageAndNameFromPlatformData.ts
  src/components/[guild]/AddRewardContext.tsx
  src/components/[guild]/CreatePoap/AddPoapPanel.tsx
  src/components/[guild]/CreatePoap/components/ImportPoap.tsx
  src/components/[guild]/CreatePoap/components/PoapDataForm/CreatePoapForm.tsx
  src/components/[guild]/Members/components/MembersExporter.tsx
  src/components/[guild]/RoleCard/components/EditRole/hooks/useEditRole.ts
  src/components/[guild]/RolePlatforms/RolePlatforms.tsx
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/AddRoleRewardModal.tsx
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/SelectExistingPlatform.tsx
  src/components/[guild]/RoleSelector.tsx
  src/components/common/DiscordGuildSetup/DiscordGuildSetup.tsx
  src/components/common/DiscordGuildSetup/components/DCServerCard.tsx
  src/components/common/GitHubGuildSetup.tsx
  src/components/common/GoogleGuildSetup/GoogleGuildSetup.tsx
  src/components/common/GoogleGuildSetup/components/GoogleDocCard.tsx
  src/components/common/OptionCard.tsx
  src/components/common/Section.tsx
  src/components/create-guild/CreateGuildContext.tsx
  src/components/create-guild/PlatformsGrid/PlatformsGrid.tsx
  src/components/create-guild/PlatformsGrid/components/PlatformSelectButton.tsx
  src/components/create-guild/Requirements/SetRequirements.tsx
  src/components/create-guild/TelegramGroup/hooks/useIsTGBotIn.ts
  src/components/create-guild/github/RepoCard.tsx
  src/components/create-guild/hooks/useCreateRole.tsx
  src/hooks/useGuildByPlatformId.ts
  src/platforms/components/DiscordPreview.tsx
  src/platforms/components/GitHubPreview.tsx
  src/platforms/components/GooglePreview.tsx
  src/platforms/components/PlatformPreview.tsx
  src/platforms/components/PoapPreview.tsx
  src/platforms/components/SelectRoleOrSetRequirements.tsx
  src/platforms/components/TelegramPreview.tsx
  src/platforms/hooks/usePlatformUsageInfo.ts
  src/platforms/platforms.tsx
  src/types.ts
Labels: improvement

#871 feat: add Zora chain support
  public/networkLogos/zora.svg
  src/connectors/index.ts
  src/hooks/useTokens.ts
  src/requirements/WalletActivity/WalletActivityForm.tsx
Labels: feature

#858 OAuth improvements
  .env
  src/components/[guild]/JoinModal/hooks/useConnectPlatform.ts
  src/components/[guild]/JoinModal/hooks/useDCAuth.ts
  src/components/[guild]/JoinModal/hooks/useGHAuth.ts
  src/components/[guild]/JoinModal/hooks/useGoogleAuth.ts
  src/components/[guild]/JoinModal/hooks/useGoogleAuthWithCallback.ts
  src/components/[guild]/JoinModal/hooks/useLegacyTwitterAuth.ts
  src/components/[guild]/JoinModal/hooks/useOAuthWithCallback.ts
  src/components/[guild]/JoinModal/hooks/useOauthPopupWindow.ts
  src/components/[guild]/JoinModal/hooks/useTGAuth.ts
  src/components/[guild]/JoinModal/hooks/useTwitterAuth.ts
  src/components/[guild]/Requirements/components/ConnectRequirementPlatformButton.tsx
  src/components/create-guild/PlatformsGrid/PlatformsGrid.tsx
  src/components/create-guild/PlatformsGrid/components/PlatformSelectButton.tsx
  src/components/create-guild/PlatformsGrid/hooks/useGoogleButtonProps.tsx
  src/components/create-guild/PlatformsGrid/hooks/useOAuthButtonProps.tsx
  src/pages/tgauth.tsx
  src/platforms/platforms.tsx
Labels: improvement

#874 Fix safe api urls
  src/requirements/PoapPayment/gnosisAPiUrls.ts
Labels: improvement

#875 ERC-1155 UI changes
  src/components/[guild]/Requirements/components/BlockExplorerUrl.tsx
  src/requirements/Nft/NftRequirement.tsx
Labels: improvement

#876 Avalanche wallet activity with covalent
  src/requirements/WalletActivity/WalletActivityForm.tsx
Labels: improvement

#873 Ethereum attestation requirement
  package-lock.json
  public/requirementLogos/eas.png
  src/components/[guild]/Requirements/components/BlockExplorerUrl.tsx
  src/requirements/EthereumAttestation/EthereumAttestationForm.tsx
  src/requirements/EthereumAttestation/EthereumAttestationRequirement.tsx
  src/requirements/EthereumAttestation/components/EthereumAttestation.tsx
  src/requirements/requirements.ts
Labels: improvement

#877 POAP hotfixes
  src/components/[guild]/AddRewardButton/AddRewardButton.tsx
  src/components/[guild]/CreatePoap/AddPoapPanel.tsx
  src/components/[guild]/CreatePoap/components/EditPoapRole/EditPoapRole.tsx
  src/platforms/Poap/DeactivatePoapMenuItem.tsx
Labels: bug
