Repository guildxyz/guild.xyz, pull requests merged in 2023-04, with the labels that each got.

#761 PostHog: checkout flow events
  .env
  next.config.js
  package-lock.json
  package.json
  src/components/[guild]/Requirements/components/GuildCheckout/BuyPass.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/PurchaseRequirement.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/InfoModal/components/InfoModalFooter.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/PaymentCurrencyPicker/components/CurrencyListItem.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/PaymentMethodButtons.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/buttons/BuyAllowanceButton.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/buttons/BuyButton.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/buttons/PurchaseAllowanceButton.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/buttons/PurchaseButton.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/buttons/SwitchNetworkButton.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/hooks/usePayFee.ts
  src/components/[guild]/Requirements/components/GuildCheckout/hooks/usePurchaseAsset.ts
  src/components/[guild]/Requirements/components/GuildCheckout/hooks/useSubmitTransaction.ts
  src/components/[guild]/Requirements/components/GuildCheckout/hooks/useTokenBuyerContractData.ts
  src/components/_app/PostHogProvider.tsx
  src/components/common/Layout/components/Account/Account.tsx
  src/pages/_app.tsx
  src/utils/guildCheckout/constants.ts
  src/utils/guildCheckout/utils.ts
Labels: feature

#769 Optimistic mutations after join and leave
  src/components/[guild]/AccessHub/AccessHub.tsx
  src/components/[guild]/JoinModal/hooks/useJoin.tsx
  src/components/[guild]/LeaveButton/hooks/useLeaveGuild.ts
  src/components/[guild]/hooks/useAutoStatusUpdate.ts
  src/components/[guild]/hooks/useIsMember.ts
  src/components/_app/IntercomProvider.tsx
  src/components/explorer/hooks/useMemberships.ts
  src/pages/explorer.tsx
Labels: improvement

#766 feat: re-check access button
  src/components/[guild]/JoinModal/hooks/useJoin.tsx
  src/components/[guild]/ResendRewardButton.tsx
  src/pages/[guild]/index.tsx
Labels: feature

#768 feat: more effective search in requirement setup forms
  src/components/common/StyledSelect/StyledSelect.tsx
  src/requirements/Galaxy/GalaxyForm.tsx
  src/requirements/Galaxy/hooks/useGalaxyCampaigns.ts
  src/requirements/Juicebox/JuiceboxForm.tsx
  src/requirements/Juicebox/hooks/useJuicebox.ts
  src/requirements/Poap/PoapForm.tsx
  src/requirements/Poap/hooks/usePoaps.ts
  src/requirements/Snapshot/components/SpaceSelect.tsx
  src/requirements/Snapshot/hooks/useProposals.ts
Labels: improvement

#738 Wallet activity requirement
  src/components/create-guild/Requirements/components/AddRequirement.tsx
  src/requirements/WalletActivity/WalletActivityForm.tsx
  src/requirements/WalletActivity/WalletActivityRequirement.tsx
  src/requirements/WalletActivity/components/AddressFormControl.tsx
  src/requirements/WalletActivity/components/AlchemyContractDeploy.tsx
  src/requirements/WalletActivity/components/AlchemyContractDeployRelative.tsx
  src/requirements/WalletActivity/components/AlchemyFirstTx.tsx
  src/requirements/WalletActivity/components/AlchemyFirstTxRelative.tsx
  src/requirements/WalletActivity/components/AlchemyTxCount.tsx
  src/requirements/WalletActivity/components/AlchemyTxCountRelative.tsx
  src/requirements/WalletActivity/components/AlchemyTxValue.tsx
  src/requirements/WalletActivity/components/AlchemyTxValueRelative.tsx
  src/requirements/WalletActivity/components/BlockNumberFormControl.tsx
  src/requirements/WalletActivity/components/ControlledNumberInput.tsx
  src/requirements/WalletActivity/components/MinMaxBlockNumberFormControls.tsx
  src/requirements/WalletActivity/components/TxCountFormControl.tsx
  src/requirements/WalletActivity/components/TxValueFormControl.tsx
  src/requirements/WalletActivity/hooks/useBlockNumberByTimestamp.ts
  src/requirements/WalletActivity/hooks/useCurrentBlock.ts
  src/requirements/requirements.ts
  src/utils/formatRelativeTimeFromNow.ts
  src/utils/preprocessRequirements.ts
Labels: feature, linear

#773 Posthog events for Twitter connection
  src/components/[guild]/JoinModal/hooks/useConnectPlatform.ts
  src/components/[guild]/hooks/useAccess.ts
  src/components/_app/Web3ConnectionManager/Web3ConnectionManager.tsx
  src/components/common/Layout/components/Account/components/AccountModal/AccountModal.tsx
  src/pages/_app.tsx
Labels: improvement

#775 PostHog analytics rework
  src/components/[guild]/JoinModal/hooks/useConnectPlatform.ts
  src/components/[guild]/Requirements/components/GuildCheckout/BuyPass.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/PurchaseRequirement.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/InfoModal/components/InfoModalFooter.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/PaymentCurrencyPicker/components/CurrencyListItem.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/PaymentMethodButtons.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/buttons/BuyAllowanceButton.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/buttons/BuyButton.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/buttons/PurchaseAllowanceButton.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/buttons/PurchaseButton.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/hooks/usePayFee.ts
  src/components/[guild]/Requirements/components/GuildCheckout/hooks/usePurchaseAsset.ts
  src/components/[guild]/ResendRewardButton.tsx
  src/components/[guild]/hooks/useAccess.ts
  src/components/_app/PostHogProvider.tsx
  src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx
  src/pages/_app.tsx
Labels: improvement

#694 E2E tests
  .github/workflows/e2e-tests.yaml
  cypress.json
  cypress/e2e/0-platformless/0-create-guild.spec.ts
  cypress/e2e/0-platformless/1-cleanup.spec.ts
  cypress/e2e/1-discord/0-create-guild.spec.ts
  cypress/e2e/1-discord/1-cleanup.spec.ts
  cypress/fixtures/connectDiscord.json
  cypress/fixtures/cypress.jpg
  cypress/fixtures/testUserDiscordGateables.json
  cypress/fixtures/testUserIdentify.json
  cypress/index.d.ts
  cypress/integration/0-discord/1-create-guild.spec.js
  cypress/integration/0-discord/2-join-guild.spec.js
  cypress/integration/0-discord/3-delete-guild.spec.js
  cypress/integration/1-telegram/0-create-guild.spec.js
  cypress/integration/1-telegram/1-delete-guild.spec.js
  cypress/plugins/index.js
  cypress/plugins/index.ts
  cypress/support/commands.js
  cypress/support/commands.ts
  cypress/support/e2e.ts
  cypress/support/index.js
  package-lock.json
  package.json
  src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx
  src/components/common/DiscordGuildSetup/components/DCServerCard.tsx
  src/components/create-guild/CreateGuildButton.tsx
  src/components/create-guild/PlatformsGrid/PlatformsGrid.tsx
  src/components/create-guild/PlatformsGrid/components/PlatformSelectButton.tsx
  synpress.config.ts
  tsconfig.json
Labels: improvement, testing

#779 fix(github): reauth with the `repo,read:user` scope
  src/components/[guild]/JoinModal/JoinModal.tsx
  src/components/[guild]/JoinModal/hooks/useConnectPlatform.ts
  src/components/[guild]/Requirements/components/ConnectRequirementPlatformButton.tsx
Labels: bug

#781 Add role-related E2E tests
  .github/workflows/e2e-tests.yaml
  cypress/e2e/0-platformless/0-create-guild.spec.ts
  cypress/e2e/0-platformless/1-manage-roles.spec.ts
  cypress/e2e/0-platformless/2-cleanup.spec.ts
  cypress/e2e/1-discord/0-create-guild.spec.ts
  cypress/support/commands.ts
  src/components/[guild]/AddAndOrderRoles/AddAndOrderRoles.tsx
  src/components/[guild]/AddAndOrderRoles/components/AddRoleDrawer.tsx
  src/components/[guild]/RoleCard/components/EditRole/EditRole.tsx
  src/components/[guild]/RoleCard/components/EditRole/components/DeleteRoleButton/DeleteRoleButton.tsx
  src/components/create-guild/Requirements/components/AddRequirement.tsx
  synpress.config.ts
Labels: improvement

#786 e2e tests workflow file refactor
  .github/workflows/e2e-tests.yaml
Labels: improvement

#785 feat: `MaintenanceBanner` component
  src/components/_app/MaintenanceBanner.tsx
  src/pages/_app.tsx
Labels: feature
