Repository guildxyz/guild.xyz, pull requests merged in 2023-10, with the labels that each got.

#916 feat(wallet activity): zkSync Era support
  src/requirements/WalletActivity/WalletActivityForm.tsx
  src/requirements/WalletActivity/WalletActivityRequirement.tsx
Labels: feature

#915 feat(ContractStateForm): define values manually
  src/requirements/ContractState/ContractStateForm.tsx
  src/requirements/ContractState/ContractStateRequirement.tsx
  src/requirements/ContractState/hooks/useAbi.ts
  src/utils/handleSubmitDirty.ts
  src/utils/mapRequirements.ts
  src/utils/preprocessRequirements.ts
Labels: feature

#918 feat(SetVisibility): add PulseMarkers
  src/components/[guild]/SetVisibility.tsx
Labels: improvement

#921 feat(AddRewardButton): send detailed rolePlatform data
  src/components/[guild]/AddRewardButton/AddRewardButton.tsx
Labels: improvement

#914 feat: EAS support on Base Mainnet
  src/requirements/EthereumAttestation/EthereumAttestationRequirement.tsx
Labels: feature

#909 feat: add reward with hidden role by default
  src/components/[guild]/AddAndOrderRoles/components/AddRoleDrawer.tsx
  src/components/[guild]/AddRewardButton/AddRewardButton.tsx
  src/components/[guild]/AddRewardButton/hooks/useAddReward.ts
  src/components/[guild]/Requirements/components/GuildCheckout/MintGuildPin/components/ActivateGuildPinForm.tsx
  src/components/[guild]/RoleCard/RoleCard.tsx
  src/components/[guild]/SetVisibility.tsx
  src/components/create-guild/hooks/useCreateRole.tsx
Labels: feature

#907 feat: text as reward
  src/components/[guild]/AccessHub/hooks/useEditGuildPlatform.ts
  src/components/[guild]/AddRewardButton/AddRewardButton.tsx
  src/components/[guild]/RoleCard/RoleCard.tsx
  src/components/[guild]/RoleCard/components/Reward.tsx
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddContractCallPanel/components/CreateNftForm/components/RichTextDescriptionEditor.tsx
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddSecretTextPanel.tsx
  src/components/[guild]/RolePlatforms/components/PlatformCard/PlatformCard.tsx
  src/components/[guild]/collect/components/RichTextDescription.tsx
  src/components/create-guild/CreateGuildPlatform/CreateGuildPlatform.tsx
  src/components/create-guild/CreateGuildPlatform/components/CreateGuildSecretText.tsx
  src/components/create-guild/IconSelector/components/PhotoUploader.tsx
  src/components/create-guild/PlatformsGrid/PlatformsGrid.tsx
  src/components/lexical/plugins/ImagesPlugin.tsx
  src/platforms/ContractCall/ContractCallReward.tsx
  src/platforms/SecretText/EditSecretTextModal.tsx
  src/platforms/SecretText/SecretTextCardButton.tsx
  src/platforms/SecretText/SecretTextCardMenu.tsx
  src/platforms/SecretText/SecretTextDataForm/SecretTextDataForm.tsx
  src/platforms/SecretText/SecretTextDataForm/components/RewardImagePicker.tsx
  src/platforms/SecretText/SecretTextDataForm/index.ts
  src/platforms/SecretText/SecretTextReward.tsx
  src/platforms/SecretText/hooks/useClaimText.tsx
  src/platforms/SecretText/useSecretTextCardProps.tsx
  src/platforms/components/SecretTextPreview.tsx
  src/platforms/platforms.tsx
  src/static/icons/box.svg
  src/types.ts
Labels: feature

#923 feat: `useSimpleGuild` & `useRole` hooks
  src/components/[guild]/Requirements/components/GuildCheckout/MintGuildPin/components/ActivateGuildPinForm.tsx
  src/components/[guild]/hooks/useGuild.ts
  src/components/[guild]/hooks/useRole.ts
  src/requirements/Guild/GuildRequirement.tsx
  src/types.ts
Labels: feature

#928 fix: linkpreview error
  next.config.js
  package-lock.json
  package.json
Labels: bug

#929 fix(edit guild): handle boolean fields properly
  src/components/[guild]/EditGuild/components/TagManager.tsx
  src/utils/handleSubmitDirty.ts
Labels: bug

#927 feat: Farcaster requirement
  public/requirementLogos/farcaster.png
  src/requirements/Farcaster/FarcasterForm.tsx
  src/requirements/Farcaster/FarcasterRequirement.tsx
  src/requirements/Farcaster/components/FarcasterCastHash.tsx
  src/requirements/Farcaster/components/FarcasterTotalFollowers.tsx
  src/requirements/Farcaster/components/FarcasterUser.tsx
  src/requirements/Farcaster/hooks/useFarcasterUsers.ts
  src/requirements/requirements.ts
Labels: feature

#922 feat: Polygon zkEVM support
  src/connectors/index.ts
  src/hooks/useTokens.ts
  src/requirements/WalletActivity/WalletActivityForm.tsx
Labels: feature

#926 feat: role groups
  src/components/[guild]/AccessHub/AccessHub.tsx
  src/components/[guild]/AccessHub/components/RoleGroupCards.tsx
  src/components/[guild]/AddAndOrderRoles/components/OrderRolesModal.tsx
  src/components/[guild]/NoRolesAlert.tsx
  src/components/[guild]/RoleSelector.tsx
  src/components/[guild]/Tabs/GuildTabs.tsx
  src/components/[guild]/Tabs/Tabs.tsx
  src/components/[guild]/[group]/AddRoleCard.tsx
  src/components/[guild]/hooks/useGroup.ts
  src/components/common/Layout/Layout.tsx
  src/components/common/Layout/components/BackButton.tsx
  src/components/create-guild/hooks/useCreateRole.tsx
  src/pages/[guild]/[group].tsx
  src/pages/[guild]/events.tsx
  src/pages/[guild]/index.tsx
  src/pages/brain/[pageSlug].tsx
  src/pages/profile/activity.tsx
  src/platforms/components/SelectRoleOrSetRequirements.tsx
  src/types.ts
Labels: feature

#934 feat: General Terms and Conditions page
  public/guild-gtc.pdf
  src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx
  src/components/index/Footer.tsx
  src/pages/terms-and-conditions.tsx
Labels: feature

#932 feat(useActiveStatusUpdates): call the new `status-update` endpoint
  src/components/[guild]/ActiveStatusUpdates.tsx
  src/components/[guild]/RoleCard/components/MemberCount.tsx
  src/components/[guild]/crm/FilterByRoles/FilterByRoles.tsx
  src/components/[guild]/crm/FilterByRoles/components/AddHiddenRoleButton.tsx
  src/components/[guild]/crm/FilterByRoles/components/useCreateHiddenRole.tsx
  src/components/[guild]/crm/useMembers.tsx
  src/hooks/useActiveStatusUpdates.ts
Labels: feature

#933 feat(RoleTags): show `amount` on the tags
  src/components/[guild]/RoleTag.tsx
  src/components/[guild]/crm/FilterByRoles/components/SetHiddenRoleRequirements.tsx
  src/components/[guild]/crm/MemberModal.tsx
  src/components/[guild]/crm/RoleTags.tsx
  src/hooks/useActiveStatusUpdates.ts
Labels: feature

#938 [GUILD-1545] - Webcrypto auth fix
  src/components/_app/KeyPairProvider.tsx
  src/hooks/useSubmit/useSubmit.ts
  src/utils/bufferUtils.ts
Labels: bug

#939 feat: PGN & Neon EVM support
  public/explorerLogos/neonscan.svg
  public/explorerLogos/pgn-light.svg
  public/networkLogos/neon.svg
  public/networkLogos/pgn.svg
  src/connectors/index.ts
  src/hooks/useTokens.ts
  src/requirements/WalletActivity/WalletActivityForm.tsx
Labels: feature

#940 feat: role group setup flow
  src/components/[guild]/AccessHub/AccessHub.tsx
  src/components/[guild]/AccessHub/components/CampaignCards/CampaignCards.tsx
  src/components/[guild]/AccessHub/components/CampaignCards/components/CampaignCardMenu.tsx
  src/components/[guild]/AccessHub/components/CampaignCards/components/EditCampaignModal.tsx
  src/components/[guild]/AccessHub/components/CampaignCards/hooks/useDeleteRoleGroup.ts
  src/components/[guild]/AccessHub/components/CampaignCards/hooks/useEditRoleGroup.ts
  src/components/[guild]/AccessHub/components/CampaignCards/index.ts
  src/components/[guild]/AccessHub/components/RoleGroupCards.tsx
  src/components/[guild]/AddAndOrderRoles/components/OrderRolesModal.tsx
  src/components/[guild]/AddRewardAndCampaign.tsx
  src/components/[guild]/CreateCampaignModal/CreateCampaignModal.tsx
  src/components/[guild]/CreateCampaignModal/components/CampaignForm.tsx
  src/components/[guild]/CreateCampaignModal/hooks/useCreateRoleGroup.ts
  src/components/[guild]/CreateCampaignModal/index.ts
  src/components/[guild]/EditGuild/components/FeatureFlags.tsx
  src/components/[guild]/RoleSelector.tsx
  src/components/[guild]/[group]/EditCampaignButton.tsx
  src/components/[guild]/hooks/useGroup.ts
  src/components/[guild]/hooks/useRoleGroup.ts
  src/components/create-guild/IconSelector/IconSelector.tsx
  src/components/create-guild/hooks/useCreateRole.tsx
  src/pages/[guild]/[group].tsx
  src/pages/[guild]/index.tsx
  src/platforms/components/SelectRoleOrSetRequirements.tsx
  src/types.ts
Labels: feature

#941 Remove legacy POAP payment logic
  src/components/[guild]/CreatePoap/components/PoapDataForm/PoapDataForm.tsx
  src/components/[guild]/CreatePoap/components/PoapRequirementAccessIndicator.tsx
  src/components/[guild]/CreatePoap/components/PoapRequirements/PoapRequirements.tsx
  src/components/[guild]/CreatePoap/components/PoapRoleCard.tsx
  src/components/[guild]/CreatePoap/components/PoapRoleCard/components/ActionButton.tsx
  src/components/[guild]/CreatePoap/components/PoapRoleCard/components/Withdraw/Withdraw.tsx
  src/components/[guild]/CreatePoap/components/PoapRoleCard/components/Withdraw/components/WithdrawButton.tsx
  src/components/[guild]/CreatePoap/components/PoapRoleCard/components/Withdraw/hooks/useWithdrawableAmounts.ts
  src/components/[guild]/CreatePoap/components/PoapRoleCard/components/Withdraw/index.ts
  src/components/[guild]/CreatePoap/components/PoapRoleCard/hooks/useWithdraw.ts
  src/components/[guild]/CreatePoap/components/PoapRoleCard/index.ts
  src/components/[guild]/CreatePoap/components/RequestMintLinks/RequestMintLinks.tsx
  src/components/[guild]/CreatePoap/components/RequestMintLinks/hooks/useRequestMintLinks.ts
  src/components/[guild]/CreatePoap/components/RequestMintLinks/index.ts
  src/components/[guild]/CreatePoap/hooks/usePoapVault.ts
  src/components/[guild]/CreatePoap/hooks/useUpdateGuildPoap.ts
  src/components/[guild]/CreatePoap/hooks/useUploadMintLinks.ts
  src/components/[guild]/claim-poap/hooks/usePoapAllowance.ts
  src/components/[guild]/claim-poap/hooks/usePoapPayFee.ts
  src/components/[guild]/claim-poap/hooks/useUserPoapEligibility.ts
  src/hooks/useFeeCollectorContract.ts
  src/pages/[guild]/claim-poap/[fancyId].tsx
  src/pages/api/poap/can-claim/[poapId]/[guildId].ts
  src/pages/api/poap/check-mint-links.ts
  src/pages/api/poap/get-poap-vault/[vaultId]/[chainId].ts
  src/pages/api/poap/get-vault/[vaultId]/[chainId].ts
  src/pages/api/poap/get-withdrawable-amount/[guildId]/[poapId].ts
  src/pages/api/poap/request-mint-links.ts
  src/requirements/PoapPayment/PoapPaymentRequirement.tsx
  src/requirements/PoapPayment/PoapPaymentRequirementEditable.tsx
  src/requirements/PoapPayment/components/BuyPoapRequirement.tsx
  src/requirements/PoapPayment/components/PoapBuyTotal.tsx
  src/requirements/PoapPayment/components/PoapPaymentFeeCurrency.tsx
  src/requirements/PoapPayment/hooks/useRegisterVault.ts
  src/requirements/PoapVoice/PoapVoiceRequirement.tsx
  src/static/abis/legacyPoapFeeCollectorAbi.json
  src/types.ts
Labels: improvement

#943 feat: InvalidRequirementErrorBoundary component
  package-lock.json
  package.json
  src/components/[guild]/Requirements/components/RequirementDisplayComponent.tsx
  src/components/create-guild/Requirements/components/RequirementEditableCard.tsx
Labels: improvement

#944 Wagmi Safe fix
  src/components/_app/Web3ConnectionManager/Web3ConnectionManager.tsx
  src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx
Labels: bug
