Repository guildxyz/guild.xyz, pull requests merged in 2023-06, with the labels that each got.

#813 feat: Guild Pin - BSC & Arbitrum support
  src/components/[guild]/Requirements/components/GuildCheckout/components/MintGuildPinChainPicker.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/TransactionStatusModal/components/OpenseaLink.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/buttons/MintGuildPinButton.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/hooks/useGuildPinContractsData.ts
  src/components/[guild]/Requirements/components/GuildCheckout/hooks/useGuildPinFee.ts
  src/components/[guild]/Requirements/components/GuildCheckout/hooks/useMintGuildPin.tsx
  src/hooks/useUsersGuildPins.ts
  src/requirements/Nft/NftRequirement.tsx
  src/static/abis/guildPin.json
  src/utils/guildCheckout/constants.ts
Labels: feature

#814 Hotfix: hidden requirement platform connection
  src/components/[guild]/Requirements/RoleRequirements.tsx
  src/components/[guild]/Requirements/components/HiddenRequirement.tsx
  src/components/[guild]/Requirements/components/RequirementDisplayComponent.tsx
  src/components/[guild]/RoleCard/components/AccessIndicator/AccessIndicator.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/SocialAccount.tsx
  src/requirements/index.ts
  src/theme/components/button.ts
  src/types.ts
Labels: improvement

#805 Remove sorting in YourGuilds
  src/components/explorer/YourGuilds.tsx
Labels: improvement

#806 Social account recovery option & modal instead of toast
  src/components/[guild]/JoinModal/hooks/useConnectPlatform.ts
  src/components/_app/Web3ConnectionManager/Web3ConnectionManager.tsx
  src/components/_app/Web3ConnectionManager/components/PlatformMergeErrorAlert.tsx
Labels: improvement

#819 feat: WalletConnect V2 support
  .env
  next.config.js
  package-lock.json
  package.json
  src/components/_app/Web3ConnectionManager/Web3ConnectionManager.tsx
  src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx
  src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/components/ConnectorButton.tsx
  src/components/_app/Web3ConnectionManager/hooks/useEagerConnect.ts
  src/components/common/Layout/components/Account/components/AccountModal/AccountModal.tsx
  src/connectors/index.ts
  src/connectors/walletConnectV2.ts
Labels: feature

#820 Join modal improvements for hidden requirements/rewards
  src/components/[guild]/JoinButton.tsx
  src/components/[guild]/JoinModal/JoinModal.tsx
  src/components/[guild]/JoinModal/components/ConnectAccount.tsx
  src/components/[guild]/JoinModal/components/ConnectPlatform.tsx
  src/components/[guild]/hooks/useAccess.ts
  src/components/[guild]/hooks/usePlatformsToReconnect.ts
  src/components/common/Layout/components/Account/components/AccountModal/components/SocialAccount.tsx
  src/types.ts
Labels: improvement

#822 landing page: discover section update
  public/landing/discover/guild-cryptonary.webp
  public/landing/discover/guild-daily-nft-show.webp
  public/landing/discover/guild-daomasters.webp
  public/landing/discover/guild-dd.webp
  public/landing/discover/guild-delphidigital.webp
  public/landing/discover/guild-evolves-platformless-memberships.webp
  public/landing/discover/guild-lego-explorer.webp
  public/landing/discover/guild-mirror.webp
  public/landing/discover/guild-pins.webp
  public/landing/discover/guild-twitter.webp
  public/landing/discover/intro-to-guild.webp
  public/landing/discover/realize-the-earning-power-of-your-community.webp
  public/landing/discover/requirements-roles-rewards.webp
  src/components/index/Discover.tsx
Labels: improvement

#809 feat: Guild Pins leaderboard
  package-lock.json
  src/components/common/Layout/components/NavMenu/NavMenu.tsx
  src/components/leaderboard/LeaderboardUserCard.tsx
  src/components/leaderboard/ScoreFormulaPopover.tsx
  src/hooks/useUsersGuildPins.ts
  src/pages/api/leaderboard/[address].ts
  src/pages/api/leaderboard/index.ts
  src/pages/api/leaderboard/revalidate.ts
  src/pages/leaderboard.tsx
  src/types.ts
Labels: feature

#821 feat: `GALAXY_PARTICIPATION` requirement type
  src/requirements/Galaxy/GalaxyForm.tsx
  src/requirements/Galaxy/GalaxyRequirement.tsx
  src/requirements/requirements.ts
Labels: feature

#825 address merge: remove `localStorage` usage
  src/components/_app/Web3ConnectionManager/Web3ConnectionManager.tsx
  src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx
  src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/hooks/useShouldLinkToUser.ts
  src/components/common/Layout/components/Account/components/AccountModal/components/LinkAddressButton.tsx
  src/hooks/useKeyPair.ts
Labels: bug

#844 feat: `useActionToast` & `useTweetToast` hooks
  src/components/[guild]/JoinModal/hooks/useJoin.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/hooks/useMintGuildPin.tsx
  src/hooks/useToast.ts
  src/hooks/useToast.tsx
Labels: improvement
