Repository guildxyz/guild.xyz, pull requests merged in 2023-02, with the labels that each got.

#666 feat: Buy requirements
  package-lock.json
  package.json
  src/components/[guild]/JoinModal/components/WalletAuthButtonWithBalance.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/GuildCheckout.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/AlphaTag.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/FeeAndTotal.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/GuildCheckoutContex.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/InfoModal/InfoModal.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/InfoModal/components/InProgress.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/InfoModal/components/InfoModalFooter.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/InfoModal/components/PurchasedRequirementInfo.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/InfoModal/components/Success.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/InfoModal/components/TransactionLink.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/InfoModal/components/TxError.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/InfoModal/index.ts
  src/components/[guild]/Requirements/components/GuildCheckout/components/PaymentCurrencyPicker/PaymentCurrencyPicker.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/PaymentCurrencyPicker/components/CurrencyListItem.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/PaymentCurrencyPicker/components/TokenInfo.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/PaymentCurrencyPicker/index.ts
  src/components/[guild]/Requirements/components/GuildCheckout/components/TOSCheckbox.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/buttons/AllowanceButton.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/buttons/PurchaseButton.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/buttons/SwitchNetworkButton.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/hooks/useAllowance.ts
  src/components/[guild]/Requirements/components/GuildCheckout/hooks/usePrice.ts
  src/components/[guild]/Requirements/components/GuildCheckout/hooks/usePurchaseAsset.ts
  src/components/[guild]/Requirements/components/GuildCheckout/index.ts
  src/components/[guild]/Requirements/components/OpenseaUrl.tsx
  src/components/[guild]/Requirements/components/Requirement.tsx
  src/components/[guild]/Requirements/components/RequirementDisplayComponent.tsx
  src/components/[guild]/claim-poap/components/ClaimModal/ClaimModal.tsx
  src/components/[guild]/claim-poap/components/ClaimModal/components/PayFeeMenuItem.tsx
  src/components/[guild]/claim-poap/hooks/useUsersTokenBalance.ts
  src/components/_app/Datadog/useDatadog.ts
  src/components/_app/Web3ConnectionManager/Web3ConnectionManager.tsx
  src/components/common/Layout/components/Account/components/AccountModal/AccountModal.tsx
  src/components/create-guild/ChooseTemplate/components/TemplateCard.tsx
  src/connectors/index.ts
  src/hooks/useBalance.ts
  src/hooks/useCoinBalance.ts
  src/hooks/useContract.ts
  src/hooks/useEstimateGasFee.ts
  src/hooks/useTokenBalance.ts
  src/hooks/useTokenData.ts
  src/pages/api/fetchPrice.ts
  src/requirements/Nft/NftRequirement.tsx
  src/requirements/Token/TokenRequirement.tsx
  src/static/abis/tokenBuyerAbi.json
  src/theme/components/button.ts
  src/theme/components/index.ts
  src/theme/components/menu.ts
  src/theme/components/modal.ts
  src/theme/components/spinner.ts
  src/types.ts
  src/utils/guildCheckout/constants.ts
  src/utils/guildCheckout/encoders.ts
  src/utils/guildCheckout/utils.ts
Labels: feature

#594 Gitcoin Passport integration
  public/requirementLogos/gitcoin-passport.svg
  src/requirements/GitcoinPassport/GitcoinPassportForm.tsx
  src/requirements/GitcoinPassport/GitcoinPassportRequirement.tsx
  src/requirements/GitcoinPassport/components/Score.tsx
  src/requirements/GitcoinPassport/components/Stamp.tsx
  src/requirements/index.ts
  src/requirements/requirements.ts
Labels: feature

#680 101 requirement support on Celo
  src/requirements/101/101Form.tsx
  src/requirements/101/101Requirement.tsx
  src/requirements/101/hooks/use101Courses.ts
Labels: improvement

#685 Delegate.cash integration
  next.config.js
  package-lock.json
  package.json
  src/components/_app/Web3ConnectionManager/Web3ConnectionManager.tsx
  src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx
  src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/components/DelegateCashButton.tsx
  src/components/common/Layout/components/Account/Account.tsx
  src/components/common/Layout/components/Account/components/AccountModal/AccountModal.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/LinkAddressButton.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/LinkedAddress.tsx
  src/components/common/Layout/components/Account/components/delegate/DelegatePopoverWrapper.tsx
  src/components/common/Layout/components/Account/components/delegate/getDelegateVaults.ts
  src/components/common/Layout/components/Account/components/delegate/useDelegateVaults.ts
  src/connectors/index.ts
  src/hooks/useKeyPair.ts
  src/static/abis/delegateRegistry.json
  src/types.ts
  src/utils/multicall.ts
Labels: feature

#693 Feature flags
  src/components/[guild]/EditGuild/EditGuildDrawer.tsx
  src/components/[guild]/EditGuild/components/FeatureFlags.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/BuyPass.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/PurchaseRequirement.tsx
  src/components/create-guild/Requirements/components/AddRequirement.tsx
  src/requirements/Twitter/TwitterForm.tsx
  src/types.ts
  src/utils/guildCheckout/constants.ts
Labels: feature

#700 Guild Checkout improvements
  src/components/[guild]/Requirements/components/GuildCheckout/PurchaseRequirement.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/InfoModal/components/InfoModalFooter.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/PaymentCurrencyPicker/PaymentCurrencyPicker.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/PaymentCurrencyPicker/components/TokenInfo.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/PurchaseFeeAndTotal.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/buttons/ConnectWalletButton.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/buttons/PurchaseAllowanceButton.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/buttons/PurchaseButton.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/hooks/usePrice.ts
  src/components/[guild]/Requirements/components/GuildCheckout/hooks/usePurchaseAsset.ts
  src/hooks/useEstimateGasFee.ts
  src/pages/api/fetchPrice.ts
  src/utils/guildCheckout/constants.ts
  src/utils/guildCheckout/utils.ts
Labels: improvement

#701 Base Goerli network
  public/networkLogos/base.svg
  src/connectors/index.ts
  src/hooks/useTokens.ts
  src/requirements/ContractState/ContractStateForm.tsx
Labels: feature

#704 Exosama & Evmos support
  public/networkLogos/evmos.svg
  public/networkLogos/exosama.png
  src/components/[guild]/Requirements/components/BlockExplorerUrl.tsx
  src/connectors/index.ts
  src/hooks/useTokens.ts
  src/requirements/ContractState/ContractStateForm.tsx
Labels: feature, improvement, waiting for BE
