Repository guildxyz/guild.xyz, pull requests merged in 2024-02, with the labels that each got.

#1049 chore: use the stable Web3Inbox SDK
  package-lock.json
  package.json
  src/components/common/Layout/components/Account/components/Web3Inbox/Web3Inbox.tsx
  src/components/common/Layout/components/Account/components/Web3Inbox/Web3InboxMessage.tsx
Labels: improvement

#1053 chore(wallet activity): Remove Goerli, Mumbai, X1 testnet
  src/requirements/WalletActivity/WalletActivityForm.tsx
Labels: bitesize

#1055 feat: Manta Pacific Mainnet & Taiko Katla Testnet support
  public/networkLogos/manta.png
  public/networkLogos/taiko-katla.svg
  src/chains.ts
  src/hooks/useTokens.ts
  src/static/customChains.ts
Labels: feature

#1056 feat(WalletActivityForm): BSC support
  src/requirements/WalletActivity/WalletActivityForm.tsx
Labels: feature

#1058 feat(NFT reward): zkSync Era support
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddContractCallPanel/components/CreateNftForm/CreateNftForm.tsx
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddContractCallPanel/components/CreateNftForm/hooks/useCreateNft.ts
  src/pages/api/nft/collectors/[chain]/[address].ts
Labels: bitesize

#1060 collect nft page improvements
  src/components/[guild]/collect/components/CollectNft.tsx
  src/components/[guild]/collect/components/RequirementsCard.tsx
  src/components/[guild]/collect/hooks/useNftDetails.ts
  src/pages/[guild]/collect/[chain]/[address].tsx
  src/pages/api/nft/collectors/[chain]/[address].ts
Labels: improvement

#1054 [GUILD-2151] - Fix Delegate.cash inegration
  src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/LinkDelegateVaultButton.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/LinkedAddress.tsx
  src/components/common/Layout/components/Account/components/AccountModal/hooks/useLinkVaults.ts
  src/components/common/Layout/components/Account/components/delegate/DelegatePopoverWrapper.tsx
  src/components/common/Layout/components/Account/components/delegate/useDelegateVaults.ts
  src/hooks/useSetKeyPair.ts
  src/static/abis/delegateRegistry.ts
  src/types.ts
Labels: bug

#1066 fix: display `ConnectPolygonID` button properly
  src/requirements/Captcha/components/CompleteCaptcha.tsx
  src/requirements/PolygonID/components/ConnectPolygonID.tsx
Labels: bug

#1071 fix: don't use x.com intents on iOS
  src/hooks/useIsIOS.ts
  src/requirements/Twitter/components/TwitterIntent.tsx
  src/requirements/Twitter/components/TwitterTweetLink.tsx
  src/requirements/Twitter/components/TwitterUserLink.tsx
Labels: bug

#1024 feat: Forms
  package-lock.json
  package.json
  src/components/[guild]/CreateFormModal/components/CreateFormForm.tsx
  src/components/[guild]/CreateFormModal/components/Display/Choice.tsx
  src/components/[guild]/CreateFormModal/components/Display/LongText.tsx
  src/components/[guild]/CreateFormModal/components/Display/Number.tsx
  src/components/[guild]/CreateFormModal/components/Display/Rate.tsx
  src/components/[guild]/CreateFormModal/components/Display/ShortText.tsx
  src/components/[guild]/CreateFormModal/components/FormCardEditable/FormCardEditable.tsx
  src/components/[guild]/CreateFormModal/components/FormCardEditable/components/FormFieldTitle.tsx
  src/components/[guild]/CreateFormModal/components/FormCardEditable/index.ts
  src/components/[guild]/CreateFormModal/components/Setup/ChoiceSetup.tsx
  src/components/[guild]/CreateFormModal/components/Setup/OptionLayout.tsx
  src/components/[guild]/CreateFormModal/components/Setup/RateSetup.tsx
  src/components/[guild]/CreateFormModal/components/Setup/RemoveButton.tsx
  src/components/[guild]/CreateFormModal/formConfig.tsx
  src/components/[guild]/CreateFormModal/hooks/useCreateForm.ts
  src/components/[guild]/CreateFormModal/schemas.ts
  src/components/[guild]/EditGuild/components/FeatureFlags.tsx
  src/components/[guild]/JoinModal/JoinModal.tsx
  src/components/[guild]/JoinModal/utils/mapAccessJobState.ts
  src/components/[guild]/Requirements/RoleRequirements.tsx
  src/components/[guild]/Requirements/components/RequiementAccessIndicatorUI.tsx
  src/components/[guild]/RoleCard/index.ts
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddFormPanel.tsx
  src/components/[guild]/collect/components/GuildImageAndName.tsx
  src/components/[guild]/crm/FilterByRoles/components/AddAndEditHiddenRoles.tsx
  src/components/[guild]/forms/FillForm.tsx
  src/components/[guild]/forms/FillFormProgress.tsx
  src/components/[guild]/forms/FormNoAccess.tsx
  src/components/[guild]/forms/SuccessfullySubmittedForm.tsx
  src/components/[guild]/hooks/useGuildForms.ts
  src/components/common/CardMotionWrapper.tsx
  src/components/common/FloatingFooter.tsx
  src/components/common/Layout/Layout.tsx
  src/components/common/LinkMenuItem.tsx
  src/components/common/StyledSelect/components/CustomSelectOption/components/OptionIcon.tsx
  src/components/create-guild/GuildCreationProgress/GuildCreationProgress.tsx
  src/components/create-guild/MultiPlatformGrid/components/MultiPlatformSelectButton.tsx
  src/components/create-guild/PlatformsGrid/PlatformsGrid.tsx
  src/components/create-guild/Requirements/components/AddRequirement.tsx
  src/pages/[guild]/[group].tsx
  src/pages/[guild]/forms/[formId]/index.tsx
  src/platforms/Forms/EditFormModal.tsx
  src/platforms/Forms/FormCardLinkButton.tsx
  src/platforms/Forms/FormCardMenu.tsx
  src/platforms/Forms/hooks/useEditForm.tsx
  src/platforms/Forms/hooks/useUserSubmission.tsx
  src/platforms/Forms/useFormCardProps.tsx
  src/platforms/components/FormPreview.tsx
  src/platforms/components/FormReward.tsx
  src/platforms/platforms.tsx
  src/requirements/Form/FormForm.tsx
  src/requirements/Form/FormRequirement.tsx
  src/requirements/requirements.ts
  src/types.ts
  src/utils/getFieldsToSwap.ts
Labels: feature

#1078 feat: Oasis Sapphire, Blast Sepolia, Base Sepolia support
  public/networkLogos/blast.png
  public/networkLogos/oasis-sapphire.svg
  src/chains.ts
  src/hooks/useTokens.ts
  src/requirements/EthereumAttestation/components/EthereumAttestationRequirementFooter.tsx
  src/requirements/WalletActivity/WalletActivityForm.tsx
  src/static/customChains.ts
Labels: feature

#1086 Add SheFi to the Web3Inbox requirement
  public/requirementLogos/shefi.jpg
  src/requirements/Web3Inbox/Web3InboxForm.tsx
Labels: bitesize

#1096 feat: Optimism support for payment requirement
  src/components/[guild]/Requirements/components/GuildCheckout/BuyPass.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/hooks/usePayFee.ts
  src/utils/guildCheckout/constants.ts
Labels: feature
