Repository guildxyz/guild.xyz, pull requests merged in 2024-01, with the labels that each got.

#993 [GUILD-2053] - Color change fix
  src/components/[guild]/EditGuild/components/ColorPicker.tsx
Labels: bug

#994 [GUILD-2055] - Empty allowlist
  src/requirements/Allowlist/AllowlistForm.tsx
Labels: improvement

#995 [GUILD-2054] - Role requirement - Guild option fix
  src/requirements/Guild/components/Role.tsx
Labels: bug

#996 [GUILD-2058] - Role image upload save button fix
  src/components/[guild]/RoleCard/components/EditRole/EditRole.tsx
Labels: bug

#988 feat: DiscordBotPermissionsChecker component
  public/videos/dc-bot-permissions.webm
  src/components/[guild]/DiscordBotPermissionsChecker.tsx
  src/hooks/useToast.tsx
  src/pages/[guild]/index.tsx
Labels: improvement

#999 [GUILD-2074] - Fix GitHub reauth alert
  src/components/[guild]/JoinModal/hooks/useConnectPlatform.ts
  src/components/common/GitHubGuildSetup.tsx
  src/components/create-guild/MultiPlatformGrid/components/MultiPlatformSelectButton.tsx
Labels: bug

#1003 feat: new Twitter follow/like/retweet requirements
  src/requirements/Twitter/TwitterForm.tsx
  src/requirements/Twitter/TwitterRequirement.tsx
  src/requirements/Twitter/components/TwitterIntent.tsx
  src/requirements/Twitter/components/TwitterUserLink.tsx
  src/requirements/requirements.ts
Labels: feature

#1009 feat: `WEB3INBOX_SUBSCRIBERS` requirement type
  public/requirementLogos/web3inbox.png
  src/requirements/Web3Inbox/Web3InboxForm.tsx
  src/requirements/Web3Inbox/Web3InboxRequirement.tsx
  src/requirements/requirements.ts
  src/theme/colors.ts
Labels: feature

#1023 Fuel improvements
  src/hooks/useFuel.ts
  src/requirements/Fuel/FuelForm.tsx
  src/requirements/requirements.ts
Labels: improvement

#1017 feat(ActivityLog): User & Admin actions tabs on guild activity log
  src/components/[guild]/activity/ActivityLogContext.tsx
  src/components/[guild]/activity/ActivityLogFiltersBar/ActivityLogFiltersBar.tsx
  src/components/[guild]/activity/ActivityLogFiltersBar/GuildActivityLogFiltersBar.tsx
  src/components/[guild]/activity/ActivityLogFiltersBar/UserActivityLogFiltersBar.tsx
  src/components/[guild]/activity/ActivityLogFiltersBar/components/DateRangeInput.tsx
  src/components/[guild]/activity/ActivityLogFiltersBar/components/FilterTag/components/ActionSuggestons.tsx
  src/components/[guild]/activity/ActivityLogFiltersBar/index.ts
  src/components/[guild]/activity/constants.ts
  src/components/[guild]/crm/FilterByRoles/FilterByRolesLogicSelector.tsx
  src/components/common/RadioButtonGroup.tsx
  src/pages/[guild]/activity.tsx
  src/pages/profile/activity.tsx
Labels: improvement

#1022 feat: show points card in access hub
  src/components/[guild]/AccessHub/AccessHub.tsx
  src/platforms/Points/EditPointsModal.tsx
  src/platforms/Points/PointsCardMenu.tsx
  src/platforms/Points/PointsRewardCard.tsx
  src/platforms/Points/TextCardButton.tsx
  src/utils/numberToOrdinal.ts
Labels: feature

#1033 fix(nft-reward-spec): wait for the join request too
  .github/workflows/e2e-tests.yml
  cypress.config.ts
  cypress/e2e/2-guild-checkout/2-nft-reward.spec.ts
Labels: improvement

#1035 feat: Fuel wallet activity requirements
  src/requirements/Fuel/FuelForm.tsx
  src/requirements/Fuel/FuelRequirement.tsx
  src/requirements/Fuel/components/FuelTransactions.tsx
  src/requirements/requirements.ts
Labels: feature

#1037 fix: disable type field when req form is in edit mode
  src/requirements/Discord/DiscordForm.tsx
  src/requirements/Email/EmailForm.tsx
  src/requirements/EthereumAttestation/EthereumAttestationForm.tsx
  src/requirements/Farcaster/FarcasterForm.tsx
  src/requirements/Fuel/FuelForm.tsx
  src/requirements/Galaxy/GalaxyForm.tsx
  src/requirements/GitcoinPassport/GitcoinPassportForm.tsx
  src/requirements/Github/GithubForm.tsx
  src/requirements/Guild/GuildForm.tsx
  src/requirements/Lens/LensForm.tsx
  src/requirements/Optimism/OptimismForm.tsx
  src/requirements/Parallel/ParallelForm.tsx
  src/requirements/Points/PointsForm.tsx
  src/requirements/PolygonID/PolygonIDForm.tsx
  src/requirements/Shield/ShieldForm.tsx
  src/requirements/Snapshot/SnapshotForm.tsx
  src/requirements/Sound/SoundForm.tsx
  src/requirements/Twitter/TwitterForm.tsx
  src/requirements/WalletActivity/WalletActivityForm.tsx
Labels: bug

#1036 feat: allow customization for all requirement types
  src/components/create-guild/Requirements/components/RequirementEditableCard.tsx
  src/requirements/index.ts
  src/requirements/requirements.ts
Labels: feature

#1025 [GUILD-2148] - Join status indication
  src/components/[guild]/JoinModal/JoinModal.tsx
  src/components/[guild]/JoinModal/components/JoinStep.tsx
  src/components/[guild]/JoinModal/components/JoinStepIndicator.tsx
  src/components/[guild]/JoinModal/components/ProgressJoinStep/ProgressJoinStep.tsx
  src/components/[guild]/JoinModal/components/ProgressJoinStep/components/JoinStateCount.tsx
  src/components/[guild]/JoinModal/components/ProgressJoinStep/components/JoinStatusStepIndicator.tsx
  src/components/[guild]/JoinModal/components/ProgressJoinStep/index.ts
  src/components/[guild]/JoinModal/components/ProgressJoinStep/static.ts
  src/components/[guild]/JoinModal/components/ProgressJoinStep/utils/getStepIndicatorProps.ts
  src/components/[guild]/JoinModal/components/SatisfyRequirementsJoinStep.tsx
  src/components/[guild]/JoinModal/hooks/useJoin.tsx
  src/components/[guild]/JoinModal/utils/mapAccessJobState.ts
  src/components/[guild]/Members/Members.tsx
Labels: feature
