Repository guildxyz/guild.xyz, pull requests merged in 2024-07, with the labels that each got.

#1333 feat: `Toast` component & `useToast` hook
  package-lock.json
  package.json
  src/app/globals.css
  src/v2/components/ui/Toast.stories.tsx
  src/v2/components/ui/Toast.tsx
  src/v2/components/ui/Toaster.tsx
  src/v2/components/ui/Tooltip.tsx
  src/v2/components/ui/hooks/useToast.ts
  tailwind.config.ts
Labels: feature

#1337 feat: `AlertDialog` component
  package-lock.json
  package.json
  src/v2/components/ui/AlertDialog.stories.tsx
  src/v2/components/ui/AlertDialog.tsx
Labels: feature

#1351 `Dialog` improvements
  src/v2/components/ui/Dialog.stories.tsx
  src/v2/components/ui/Dialog.tsx
Labels: feature

#1355 Add Mint support for Guild Pin & NFT reward
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddContractCallPanel/components/CreateNftForm/hooks/useCreateNft.ts
  src/utils/guildCheckout/constants.ts
Labels: bitesize

#1358 feat: `Form` component
  package-lock.json
  package.json
  src/app/playground/_components/FormExample.tsx
  src/app/playground/page.tsx
  src/v2/components/ui/Button.tsx
  src/v2/components/ui/Form.tsx
  src/v2/components/ui/Input.stories.ts
  src/v2/components/ui/Input.tsx
  src/v2/components/ui/Label.tsx
Labels: feature

#1359 feat: `DropdownMenu` component
  package-lock.json
  package.json
  src/app/globals.css
  src/v2/components/ui/DropdownMenu.stories.tsx
  src/v2/components/ui/DropdownMenu.tsx
  tailwind.config.ts
Labels: feature

#1334 feat: AddSolutionsModal
  public/platforms/form.png
  public/platforms/nft.png
  public/platforms/points.png
  public/platforms/text.png
  public/solutions/discord-bg.jpg
  public/solutions/form-bg.jpg
  public/solutions/gather-bg.jpg
  public/solutions/github-bg.jpg
  public/solutions/google-bg.jpg
  public/solutions/liquidity-bg.jpg
  public/solutions/liquidity.png
  public/solutions/nft-bg.jpg
  public/solutions/poap-bg.jpg
  public/solutions/points-bg.jpg
  public/solutions/polygon-bg.jpg
  public/solutions/telegram-bg.jpg
  public/solutions/text-bg.jpg
  src/components/[guild]/AddRewardAndCampaign.tsx
  src/components/[guild]/AddRewardButton/SelectRolePanel.tsx
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddPointsPanel/AddPointsPanel.tsx
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddPointsPanel/components/ExistingPointsTypeSelect.tsx
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddPointsPanel/components/SetPointsAmount/components/DynamicPointsAmountForm.tsx
  src/components/common/SegmentedControl.tsx
  src/components/create-guild/PlatformsGrid/components/PlatformSelectButton.tsx
  src/rewards/ContractCall/index.ts
  src/rewards/SecretText/index.ts
  src/rewards/Token/DynamicRewardModal.tsx
  src/rewards/components/PointsPreview.tsx
  src/solutions/LiquidityIncentive/LiquidityIncentiveSetupModal.tsx
  src/solutions/components/AddSolutionsButton.tsx
  src/solutions/components/AddSolutionsModal.tsx
  src/solutions/components/Category.tsx
  src/solutions/components/SolutionCard.tsx
  src/solutions/components/SolutionSelectButton.tsx
  src/solutions/components/SolutionsPanel.tsx
  src/solutions/constants.ts
  src/solutions/index.ts
  src/solutions/types.ts
  src/theme/components/modal.ts
  src/utils/transparentize.ts
Labels: feature

#1361 feat(`/[formId]`): mutate form after access check
  src/components/[guild]/forms/FormNoAccess.tsx
  src/pages/[guild]/forms/[formId]/index.tsx
Labels: improvement

#1367 fix(AddRequirement): transform requirement data before parsing
  src/components/create-guild/Requirements/components/AddRequirement.tsx
Labels: bug

#1384 feat(`Button`): new variants
  src/app/explorer/_components/Explorer.tsx
  src/app/explorer/_components/StickyBar.tsx
  src/app/globals.css
  src/components/[guild]/Requirements/components/ConnectRequirementPlatformButton.tsx
  src/v2/components/Account/Account.tsx
  src/v2/components/Account/components/AccountModal/components/DisconnectAccountButton.tsx
  src/v2/components/Account/components/AccountModal/components/EmailAddress.tsx
  src/v2/components/Account/components/AccountModal/components/FarcasterProfile.tsx
  src/v2/components/Account/components/AccountModal/components/LinkAddressButton.tsx
  src/v2/components/Account/components/AccountModal/components/LinkDelegateVaultButton.tsx
  src/v2/components/Account/components/AccountModal/components/LinkedAddress.tsx
  src/v2/components/Account/components/AccountModal/components/SharedSocials.tsx
  src/v2/components/Account/components/AccountModal/components/SocialAccount.tsx
  src/v2/components/Account/components/NetworkModal/NetworkButton.tsx
  src/v2/components/Account/components/Notification/Web3Inbox.tsx
  src/v2/components/Header/NavMenu.tsx
  src/v2/components/Web3ConnectionManager/PlatformMergeErrorAlert.tsx
  src/v2/components/Web3ConnectionManager/WalletLinkHelperModal.tsx
  src/v2/components/Web3ConnectionManager/WalletSelectorModal/WalletSelectorModal.tsx
  src/v2/components/Web3ConnectionManager/WalletSelectorModal/components/AccountButton.tsx
  src/v2/components/Web3ConnectionManager/WalletSelectorModal/components/ConnectorButton.tsx
  src/v2/components/ui/AlertDialog.tsx
  src/v2/components/ui/Button.stories.ts
  src/v2/components/ui/Button.tsx
  src/v2/components/ui/Form.tsx
  tailwind.config.ts
Labels: feature

#1391 fix(guild page): Vercel ISR issues
  next.config.js
  package-lock.json
Labels: improvement

#1402 fix: add existing rewards to a guild
  src/components/[guild]/AddRewardButton/AddRewardButton.tsx
  src/components/[guild]/AddRewardButton/hooks/useAddRoleRewards.ts
  src/components/[guild]/AddRewardButton/hooks/useMutateAdditionsToRoles.ts
  src/components/[guild]/AddRewardButton/index.ts
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/AddRoleRewardModal.tsx
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/SelectExistingPlatform.tsx
  src/pages/[guild]/[group].tsx
  src/solutions/components/AddSolutionsModal.tsx
Labels: bug

#1407 Playwright
  .env.example
  .github/workflows/playwright.yml
  .gitignore
  biome.json
  cypress.config.ts
  cypress/e2e/1-roles-requirements-rewards/0-manage-roles.spec.ts
  cypress/e2e/2-guild-checkout/0-payment-requirement.spec.ts
  cypress/e2e/2-guild-checkout/1-guild-pins.spec.ts
  cypress/e2e/2-guild-checkout/2-nft-reward.spec.ts
  cypress/e2e/readme.md
  cypress/fixtures/cypress-gang-nft.png
  cypress/fixtures/testUserDiscordGateables.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  cypress/tsconfig.json
  package-lock.json
  package.json
  playwright.config.ts
  playwright/auth.setup.ts
  playwright/constants.ts
  playwright/dummy.spec.ts
  playwright/fixtures.ts
  src/components/[guild]/Requirements/components/GuildCheckout/hooks/useMintGuildPin.tsx
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddContractCallPanel/components/CreateNftForm/hooks/useCreateNft.ts
  src/components/[guild]/collect/hooks/useCollectNft.ts
  src/hooks/useSubmitTransaction.ts
  src/requirements/Payment/components/RegisterVaultForm/hooks/useRegisterVault.ts
  src/rewards/Token/hooks/useCollectToken.tsx
  src/rewards/Token/hooks/useRegisterPool.tsx
  src/rewards/Token/hooks/useWithdrawPool.tsx
  src/v2/components/Account/Account.tsx
  src/v2/components/Web3ConnectionManager/WalletSelectorModal/WalletSelectorModal.tsx
  src/v2/components/Web3ConnectionManager/WalletSelectorModal/components/ConnectorButton.tsx
  src/v2/hooks/useAutoReconnect.ts
  src/wagmiConfig/index.ts
  src/wagmiConfig/mockConnector.ts
  tsconfig.json
Labels: testing

#1410 Add Mode support for Guild Pin & NFT reward
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddContractCallPanel/components/CreateNftForm/hooks/useCreateNft.ts
  src/utils/guildCheckout/constants.ts
Labels: bitesize

#1413 feat: Guild Pin minting E2E test
  .github/workflows/playwright.yml
  package-lock.json
  package.json
  playwright.config.ts
  playwright/01-auth.setup.ts
  playwright/02-dummy.spec.ts
  playwright/03-guild-pin.spec.ts
  playwright/constants.ts
  src/components/[guild]/Requirements/components/GuildCheckout/MintGuildPin/MintGuildPin.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/GuildPinFees.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/buttons/MintGuildPinButton.tsx
  src/v2/components/Web3ConnectionManager/Web3ConnectionManager.tsx
  src/v2/hooks/useAutoReconnect.ts
  src/wagmiConfig/index.ts
  src/wagmiConfig/mockConnector.ts
Labels: testing

#1419 fix(EditGuildDrawer): validate `eventSources` with Zod
  src/components/[guild]/EditGuild/EditGuildDrawer.tsx
  src/components/[guild]/EditGuild/components/Events/EventInput.tsx
Labels: improvement

#1416 fix(RoleRequirements): properly display "Some secret requirements"
  src/components/[guild]/Requirements/RoleRequirements.tsx
  src/components/[guild]/Requirements/components/ExpandRequirementsButton.tsx
  src/components/[guild]/Requirements/components/RequirementDisplayComponent.tsx
Labels: bug

#1422 feat: hidden pages
  src/components/[guild]/AccessHub/components/CampaignCards/CampaignCards.tsx
  src/components/[guild]/AccessHub/components/CampaignCards/components/CampaignCardMenu.tsx
  src/components/[guild]/AccessHub/components/CampaignCards/components/EditCampaignModal.tsx
  src/components/[guild]/AccessHub/components/CampaignCards/hooks/useEditRoleGroup.ts
  src/components/[guild]/CreateCampaignModal/components/CampaignForm.tsx
  src/components/[guild]/[group]/EditCampaignButton.tsx
  src/types.ts
Labels: feature
