Repository guildxyz/guild.xyz, pull requests merged in 2024-10, with the labels that each got.

#1513 feat(RoleCard): simplify height logic & migrate to shadcn/ui
  package-lock.json
  package.json
  src/app/globals.css
  src/components/[guild]/LogicDivider.tsx
  src/components/[guild]/Requirements/RoleRequirements.tsx
  src/components/[guild]/Requirements/components/ExpandRequirementsButton.tsx
  src/components/[guild]/Requirements/components/Requirement.tsx
  src/components/[guild]/Requirements/components/RequirementAccessIndicatorUI.tsx
  src/components/[guild]/Requirements/index.ts
  src/components/[guild]/RoleCard/RoleCard.tsx
  src/components/[guild]/RoleCard/components/AccessIndicator.tsx
  src/components/[guild]/RoleCard/components/RoleDescription.tsx
  src/components/[guild]/RoleCard/components/RoleHeader.tsx
  src/components/[guild]/RoleCard/components/RoleRequirementsSection.tsx
  src/components/[guild]/RoleCard/index.ts
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/DynamicSetup/BaseValueModal.tsx
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/SelectExistingPlatform.tsx
  src/components/[guild]/Roles.tsx
  src/components/[guild]/collect/components/RequirementsCard.tsx
  src/components/[guild]/crm/FilterByRoles/components/SetHiddenRoleRequirements.tsx
  src/components/[guild]/hooks/useGuild.ts
  src/components/[guild]/hooks/useRequirements.ts
  src/components/create-guild/IconSelector/IconSelector.tsx
  src/components/create-guild/Requirements/EditRequirements.tsx
  src/components/create-guild/Requirements/SetRequirements.tsx
  src/pages/[guild]/forms/[formId]/index.tsx
  src/pages/_app.tsx
  src/v2/components/ui/Tooltip.tsx
  src/v2/hooks/useDisclosure.ts
  src/v2/hooks/useMeasure.ts
Labels: improvement

#1514 chore: migrate the `MemberCount` component to Tailwind CSS & Radix UI
  src/components/[guild]/AddAndOrderRoles/components/DraggableRoleCard.tsx
  src/components/[guild]/GuildPageImageAndName.tsx
  src/components/[guild]/RecheckAccessesAndLeaveButton.tsx
  src/components/[guild]/RoleCard/components/MemberCount.tsx
  src/components/[guild]/RoleCard/components/MemberCountLastSyncTooltip.tsx
  src/components/[guild]/RoleOptionCard.tsx
  src/components/[guild]/crm/ExportMembers/ExportCard/ExportCard.tsx
  src/components/[guild]/crm/FilterByRoles/FilterByRoles.tsx
  src/hooks/useActiveStatusUpdates.ts
Labels: improvement

#1517 fix(RoleDescription min height): handle roles without rewards
  src/components/[guild]/RoleCard/RoleCard.tsx
  src/components/[guild]/RoleCard/components/RoleDescription.tsx
Labels: bug

#1518 fix: make the farcaster-related hooks work with the new API
  src/app/(marketing)/profile/[username]/page.tsx
  src/app/(marketing)/profile/_hooks/useFarcasterProfile.tsx
  src/requirements/Farcaster/FarcasterRequirement.tsx
  src/requirements/Farcaster/components/FarcasterCast.tsx
  src/requirements/Farcaster/components/FarcasterCastHash.tsx
  src/requirements/Farcaster/components/FarcasterCastSmall.tsx
  src/requirements/Farcaster/components/FarcasterChannel.tsx
  src/requirements/Farcaster/components/FarcasterUser.tsx
  src/requirements/Farcaster/hooks/useFarcasterCast.ts
  src/requirements/Farcaster/hooks/useFarcasterChannels.ts
  src/requirements/Farcaster/hooks/useFarcasterUsers.ts
  src/requirements/Farcaster/types.ts
  src/v2/hooks/useFarcasterAPI/constants.ts
  src/v2/hooks/useFarcasterAPI/index.ts
Labels: bug

#1468 feat: World ID identity & requirement
  public/requirementLogos/worldid.svg
  src/app/globals.css
  src/components/[guild]/JoinModal/hooks/useConnectPlatform.ts
  src/components/[guild]/Requirements/components/ConnectRequirementPlatformButton.tsx
  src/components/create-guild/Requirements/hooks/useHandleRequirementState.ts
  src/requirements/WorldID/WorldIDForm.tsx
  src/requirements/WorldID/WorldIDRequirement.tsx
  src/requirements/requirementDisplayComponents.ts
  src/requirements/requirementFormComponents.ts
  src/requirements/requirements.ts
  src/requirements/types.ts
  src/rewards/Github/data.ts
  src/rewards/Twitter/data.ts
  src/rewards/WorldID/data.ts
  src/rewards/index.ts
  src/static/icons/world-id.svg
  src/theme/colors.ts
  src/types.ts
  src/v2/components/Account/components/AccountModal/components/SocialAccount.tsx
  src/v2/components/ui/Input.tsx
  src/v2/components/ui/Select.tsx
  tailwind.config.ts
Labels: feature

#1525 feat: use custom serverless endpoints for farcaster
  src/app/(marketing)/profile/[username]/page.tsx
  src/app/(marketing)/profile/_components/ProfileSocialCounters.tsx
  src/app/(marketing)/profile/_hooks/useFarcasterProfile.tsx
  src/app/api/farcaster/casts/route.ts
  src/app/api/farcaster/channels/[id]/route.ts
  src/app/api/farcaster/channels/search/route.ts
  src/app/api/farcaster/neynarAPIClient.ts
  src/app/api/farcaster/relevant-followers/[viewerfid]/[targetfid]/route.ts
  src/app/api/farcaster/types.ts
  src/app/api/farcaster/users/[fid]/route.ts
  src/app/api/farcaster/users/search/route.ts
  src/components/[guild]/JoinModal/JoinModal.tsx
  src/env.js
  src/requirements/Farcaster/components/FarcasterAction.tsx
  src/requirements/Farcaster/components/FarcasterCast.tsx
  src/requirements/Farcaster/components/FarcasterCastSmall.tsx
  src/requirements/Farcaster/hooks/useFarcasterCast.ts
  src/requirements/Farcaster/hooks/useFarcasterChannels.ts
  src/requirements/Farcaster/hooks/useFarcasterUsers.ts
  src/v2/hooks/useFarcasterAPI/constants.ts
  src/v2/hooks/useFarcasterAPI/index.ts
Labels: feature

#1527 feat(playwright): join & leave guild tests
  playwright/05-join-leave.spec.ts
  playwright/constants.ts
  src/components/[guild]/JoinButton.tsx
  src/components/[guild]/JoinModal/JoinModal.tsx
  src/components/[guild]/LeaveButton/LeaveButton.tsx
Labels: improvement

#1528 Add leave guild button for admin
  src/components/[guild]/EditGuild/components/LeaveGuildButton.tsx
  src/pages/[guild]/dashboard/index.tsx
Labels: bitesize

#1529 feat(VisitLinkRequirement): use Tailwind CSS and Radix UI
  src/requirements/VisitLink/VisitLinkRequirement.tsx
  src/v2/components/ui/AlertDialog.tsx
Labels: improvement

#1530 feat: `LINEA_POH` requirement
  package-lock.json
  package.json
  src/components/create-guild/Requirements/components/AddRequirement.tsx
  src/requirements/LineaPOH/LineaPOHForm.tsx
  src/requirements/LineaPOH/LineaPOHRequirement.tsx
  src/requirements/requirementDisplayComponents.ts
  src/requirements/requirementFormComponents.ts
  src/requirements/requirements.ts
Labels: feature

#1533 feat(AirdropRequirement): use Tailwind CSS and Radix UI
  src/components/[guild]/leaderboard/Snapshots/CreateSnapshotModal.tsx
  src/components/[guild]/leaderboard/Snapshots/SnapshotModal.tsx
  src/components/[guild]/leaderboard/Snapshots/SnapshotTable.tsx
  src/requirements/Airdrop/AirdropRequirement.tsx
  src/requirements/Airdrop/providedValue/AirdropProvidedValue.tsx
  src/rewards/Token/EditTokenModal.tsx
  src/v2/components/CopyableAddress.tsx
Labels: improvement
