Repository guildxyz/guild.xyz, pull requests merged in 2024-12, with the labels that each got.

#1574 feat: RewardCard component
  src/components/rewards/RewardCard.tsx
  src/stories/rewards/RewardCard.stories.tsx
Labels: feature

#1577 feat. link preview for role groups
  src/pages/[guild]/[group].tsx
  src/pages/api/linkpreview/[timestamp]/[guild]/[group].tsx
  src/pages/api/linkpreview/[timestamp]/[guild]/index.tsx
Labels: feature

#1578 chore: extract changes from `add-guild-page` branch
  package.json
  src/actions/auth.ts
  src/app/(dashboard)/create-guild/components/CreateGuildButton.tsx
  src/app/(dashboard)/explorer/atoms.ts
  src/app/(dashboard)/explorer/components/AssociatedGuilds.tsx
  src/app/(dashboard)/explorer/components/GuildCard.tsx
  src/app/(dashboard)/explorer/components/InfiniteScrollGuilds.tsx
  src/app/(dashboard)/explorer/components/StickyNavbar.tsx
  src/app/(dashboard)/explorer/constants.ts
  src/app/(dashboard)/explorer/fetchers.ts
  src/app/(dashboard)/explorer/layout.tsx
  src/app/(dashboard)/explorer/options.ts
  src/app/(dashboard)/explorer/page.tsx
  src/app/playground/page.tsx
  src/components/NavMenu.tsx
  src/components/Providers.tsx
  src/components/SignInDialog.tsx
  src/components/rewards/RewardCard.tsx
  src/lib/env.ts
  src/lib/fetchGuildApi.ts
  src/lib/fetcher.ts
  src/lib/fetchers.ts
  src/lib/getCookieClientSide.ts
  src/lib/getQueryClient.ts
  src/lib/options.ts
  src/lib/resolveIdLikeRequest.ts
  src/lib/schemas/user.ts
  src/lib/token.ts
  src/lib/types.ts
Labels: bug, improvement

#1572 feat: requirements
  src/app/(dashboard)/[guildUrlName]/[pageUrlName]/page.tsx
  src/components/requirements/RequirementDisplayComponent.tsx
  src/components/requirements/constants.ts
  src/lib/schemas/common.ts
  src/lib/schemas/role.ts
  src/lib/schemas/rule.ts
Labels: feature

#1587 feat: add support for Pin on Ink & Form, NFT reward on Ink
  package-lock.json
  package.json
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddContractCallPanel/components/CreateNftForm/hooks/useCreateNft.ts
Labels: bitesize
