Repository guildxyz/guild.xyz, pull requests merged in 2024-08, with the labels that each got.

#1423 feat: rework the `Layout` component
  src/app/explorer/page.tsx
  src/v2/components/Layout/Layout.stories.tsx
  src/v2/components/Layout/Layout.tsx
  src/v2/components/Layout/index.ts
Labels: improvement

#1428 feat(guild page): remove members section & redesign cover
  src/app/globals.css
  src/components/[guild]/EditGuild/EditGuildButton.tsx
  src/components/[guild]/Members/Members.tsx
  src/components/[guild]/Members/components/Member.tsx
  src/components/[guild]/Members/index.ts
  src/components/[guild]/ThemeContext.tsx
  src/components/common/Layout/components/BackButton.tsx
  src/pages/[guild]/index.tsx
  src/theme/styles.ts
  src/utils/parseDescription.tsx
  src/v2/components/GuildCard.tsx
  src/v2/components/Header/Header.tsx
  src/v2/components/Header/NavMenu.tsx
  src/v2/components/Layout/Layout.tsx
  src/v2/components/ui/Badge.tsx
  tailwind.config.ts
Labels: improvement

#1431 feat: remove tabs & add `/dashboard` page
  src/app/globals.css
  src/components/[guild]/AccessHub/AccessHub.tsx
  src/components/[guild]/AccessHub/components/CreatePageCard.tsx
  src/components/[guild]/ActiveStatusUpdates.tsx
  src/components/[guild]/AddAndOrderRoles/AddAndOrderRoles.tsx
  src/components/[guild]/AddRewardAndCampaign.tsx
  src/components/[guild]/AddSolutionsAndEditGuildButton.tsx
  src/components/[guild]/EditGuild/EditGuildButton.tsx
  src/components/[guild]/EditGuild/EditGuildDrawer.tsx
  src/components/[guild]/EditGuild/EditGuildDrawerContext.tsx
  src/components/[guild]/EditGuild/EditGuildDrawerProvider.tsx
  src/components/[guild]/EditGuild/EditGuildFormComponent.tsx
  src/components/[guild]/EditGuild/components/DeleteGuildButton/DeleteGuildButton.tsx
  src/components/[guild]/EditGuild/components/DeleteGuildButton/hooks/useDeleteGuild.ts
  src/components/[guild]/EditGuild/components/Events/EventInput.tsx
  src/components/[guild]/EditGuild/components/SocialLinks.tsx
  src/components/[guild]/EditGuild/components/TransferOwnership/TransferOwnership.tsx
  src/components/[guild]/EditGuild/components/UrlName.tsx
  src/components/[guild]/EditGuild/hooks/useEditGuild.ts
  src/components/[guild]/EditGuild/types.ts
  src/components/[guild]/GroupPageImageAndName.tsx
  src/components/[guild]/GuildPageBanner.tsx
  src/components/[guild]/GuildPageImageAndName.tsx
  src/components/[guild]/JoinButton.tsx
  src/components/[guild]/LeaveButton/LeaveButton.tsx
  src/components/[guild]/Members/components/MembersExporter.tsx
  src/components/[guild]/RecheckAccessesAndLeaveButton.tsx
  src/components/[guild]/RecheckAccessesButton.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/MintGuildPin/components/ActivateGuildPinModal.tsx
  src/components/[guild]/Roles.tsx
  src/components/[guild]/StayConnectedToast.tsx
  src/components/[guild]/Tabs/GuildTabs.tsx
  src/components/common/FloatingFooter.tsx
  src/components/common/Layout/components/BackButton.tsx
  src/components/common/Layout/components/BackToExplorerButton.tsx
  src/components/common/Layout/index.tsx
  src/components/common/Section.tsx
  src/components/create-guild/Description.tsx
  src/pages/[guild]/[group].tsx
  src/pages/[guild]/activity.tsx
  src/pages/[guild]/analytics.tsx
  src/pages/[guild]/dashboard/index.tsx
  src/pages/[guild]/events.tsx
  src/pages/[guild]/forms/[formId]/index.tsx
  src/pages/[guild]/index.tsx
  src/pages/[guild]/leaderboard/[pointsId].tsx
  src/pages/[guild]/members.tsx
  src/pages/[guild]/messages.tsx
  src/pages/profile/activity.tsx
  src/pages/superadmin/activity.tsx
  src/solutions/components/AddSolutionsButton.tsx
  src/theme/index.ts
  src/v2/components/Layout/index.ts
  src/v2/components/StickyAction.tsx
  src/v2/components/[guild]/constants.ts
Labels: feature

#1442 Add Avalanche & Lisk support for NFT reward
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddContractCallPanel/components/CreateNftForm/hooks/useCreateNft.ts
Labels: bitesize

#1443 fix: display `DynamicTag` for the relevant rewards
  src/components/[guild]/RoleCard/components/DynamicReward/DynamicTag.tsx
  src/components/[guild]/RoleCard/components/RoleRewards.tsx
  src/rewards/Points/usePointsCardProps.tsx
  src/rewards/Token/hooks/useTokenCardProps.tsx
Labels: bug

#1444 feat: migrate the `/create-guild` page to Tailwind
  package-lock.json
  package.json
  src/app/create-guild/_components/CreateGuildButton.tsx
  src/app/create-guild/_components/CreateGuildCard.tsx
  src/app/create-guild/_components/CreateGuildFormProvider.tsx
  src/app/create-guild/_components/CreateGuildImageUploader.tsx
  src/app/create-guild/_components/EmailFormField.tsx
  src/app/create-guild/_hooks/useCreateGuild.ts
  src/app/create-guild/page.tsx
  src/app/create-guild/types.ts
  src/app/explorer/_components/GuildSearchBar.tsx
  src/app/globals.css
  src/components/create-guild/BasicInfo/components/ContactInfo.tsx
  src/components/create-guild/CreateGuildButton.tsx
  src/components/create-guild/CreateGuildForm.tsx
  src/components/create-guild/IconSelector/IconSelector.tsx
  src/components/create-guild/IconSelector/components/PhotoUploader.tsx
  src/components/create-guild/IconSelector/utils.ts
  src/hooks/usePinata/usePinata.ts
  src/pages/create-guild.tsx
  src/v2/components/ui/Button.tsx
  src/v2/components/ui/Form.tsx
  src/v2/components/ui/Input.stories.ts
  src/v2/components/ui/Input.tsx
  tailwind.config.ts
Labels: improvement
