Repository guildxyz/guild.xyz, pull requests merged in 2024-05, with the labels that each got.

#1189 feat: add `PURCHASE_REQUIREMENT` & `PAYMENT_REQUIREMENT` feature flags
  src/components/[guild]/EditGuild/components/FeatureFlags.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/DynamicPurchaseRequirement.tsx
  src/components/create-guild/Requirements/components/AddRequirement.tsx
Labels: feature

#1158 [GUILD-2732] - Uniswap V3 positions requirement
  package-lock.json
  package.json
  public/requirementLogos/uniswap.svg
  src/requirements/Uniswap/UniswapForm.tsx
  src/requirements/Uniswap/UniswapRequirement.tsx
  src/requirements/Uniswap/hooks/usePairOfTokenId.ts
  src/requirements/Uniswap/hooks/useParsePoolTokenId.ts
  src/requirements/Uniswap/hooks/useParseVaultAddress.ts
  src/requirements/Uniswap/hooks/useSymbolsOfPair.ts
  src/requirements/Uniswap/hooks/useTokenSymbolsOfPoolVault.ts
  src/requirements/Uniswap/hooks/useTokensOfPoolVault.ts
  src/requirements/common/TokenPicker.tsx
  src/requirements/requirements.ts
  src/static/abis/uniswapV3Factory.ts
  src/static/abis/uniswapV3PositionsNFT.ts
  src/static/abis/uniswapV3PositionsVault.ts
  src/theme/colors.ts
Labels: feature

#1192 improvement(CreateNftForm): copy & UI updates
  cypress/e2e/3-guess-the-guild/0-guess-name.spec.ts
  cypress/e2e/3-guess-the-guild/1-assign-logos.spec.ts
  cypress/fixtures/testGuilds.json
  package-lock.json
  package.json
  src/components/[guild]/DiscordBotPermissionsChecker.tsx
  src/components/[guild]/JoinModal/hooks/useConnectPlatform.ts
  src/components/[guild]/JoinModal/hooks/useFetchUserEmail.ts
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddContractCallPanel/components/CreateNftForm/CreateNftForm.tsx
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddContractCallPanel/components/CreateNftForm/components/ImagePicker.tsx
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddContractCallPanel/components/CreateNftForm/components/MintPerAddressInput.tsx
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddContractCallPanel/components/CreateNftForm/components/NftTypeInput.tsx
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddContractCallPanel/components/CreateNftForm/components/SupplyInput.tsx
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddContractCallPanel/components/CreateNftForm/hooks/useCreateNft.ts
  src/components/[guild]/activity/ActivityLogAction/components/ClickableTagPopover/ClickableTagPopover.tsx
  src/components/[guild]/crm/RoleTags.tsx
  src/components/common/SegmentedControl.tsx
  src/components/guess-the-guild/EndGame.tsx
  src/components/guess-the-guild/StartGame.tsx
  src/components/guess-the-guild/assign-logos/AssignLogos.tsx
  src/components/guess-the-guild/assign-logos/components/Draggable.tsx
  src/components/guess-the-guild/assign-logos/components/GuildCardWithDropzone.tsx
  src/components/guess-the-guild/assign-logos/components/SkeletonAssignLogos.tsx
  src/components/guess-the-guild/assign-logos/components/SourceDropzone.tsx
  src/components/guess-the-guild/assign-logos/components/TargetDropzone.tsx
  src/components/guess-the-guild/assign-logos/hooks/useDragAndDrop.tsx
  src/components/guess-the-guild/components/ResultAlert.tsx
  src/components/guess-the-guild/components/ScoreIndicator.tsx
  src/components/guess-the-guild/guess-name/GuessName.tsx
  src/components/guess-the-guild/guess-name/components/AnswerButton.tsx
  src/components/guess-the-guild/guess-name/components/SkeletonGuessName.tsx
  src/components/guess-the-guild/guess-the-guild-types.tsx
  src/components/guess-the-guild/hooks/useGameLogic.tsx
  src/pages/guess-the-guild.tsx
  src/platforms/SecretText/TextCardButton.tsx
  src/types.ts
  src/utils/shuffleArray.ts
Labels: improvement

#1198 refactor: extend ControlledNumberInput
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddTokenPanel/components/ConversionInput.tsx
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddTokenPanel/components/ConversionNumberInput.tsx
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddTokenPanel/components/DynamicAmount.tsx
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddTokenPanel/components/PoolStep.tsx
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddTokenPanel/components/StaticAmount.tsx
  src/components/[guild]/hooks/useGuildPlatform.tsx
  src/components/[guild]/leaderboard/LeaderboardUserCard.tsx
  src/components/create-guild/PlatformsGrid/PlatformsGrid.tsx
  src/pages/[guild]/collect/[chain]/[address].tsx
  src/platforms/Token/EditTokenModal.tsx
  src/platforms/Token/FundPoolModal.tsx
  src/platforms/Token/hooks/useCalculateToken.tsx
  src/platforms/components/PointsPreview.tsx
  src/requirements/Points/PointsRequirement.tsx
  src/requirements/WalletActivity/components/ControlledNumberInput.tsx
  src/utils/getNumOfDecimals.ts
  src/utils/guildCheckout/constants.ts
Labels: improvement

#1208 [GUILD-2228] - Gateables & Discord setup flow optimization
  package-lock.json
  package.json
  public/discord_permissions.png
  src/components/[guild]/DiscordBotPermissionsChecker.tsx
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddDiscordPanel.tsx
  src/components/common/DiscordGuildSetup/DiscordGuildSetup.tsx
  src/components/common/DiscordGuildSetup/components/DCServerCard.tsx
  src/components/common/DiscordGuildSetup/components/ServerSetupCard/ServerSetupCard.tsx
  src/components/common/GoogleGuildSetup/components/GoogleDocCard.tsx
  src/components/create-guild/MultiPlatformGrid/components/CreateGuildDiscord.tsx
  src/components/create-guild/github/RepoCard.tsx
  src/hooks/useCountdownSeconds.ts
  src/hooks/useGateables.ts
  src/hooks/useServerPermissions.ts
  src/types.ts
Labels: improvement

#1212 fix: don't use `replace` from `useRouter` in dependency arrays
  src/components/[guild]/forms/responses/FormResponsesTable.tsx
  src/hooks/useOAuthResultToast.ts
  src/hooks/useQueryState.ts
  src/pages/[guild]/members.tsx
  src/pages/_app.tsx
Labels: bug

#1216 fix(useSetRoleImageAndNameFromPlatformData): add early return to useEffect
  src/components/[guild]/AddRewardButton/hooks/useSetRoleImageAndNameFromPlatformData.ts
Labels: bug

#1218 refactor(useEditGuildPlatform): send the whole `platformGuildData` object to our API
  src/components/[guild]/AccessHub/hooks/useEditGuildPlatform.ts
  src/components/[guild]/RoleCard/components/EditNFTDescriptionModal.tsx
  src/platforms/Poap/PoapCardButton.tsx
  src/platforms/Poap/PoapCardMenu.tsx
  src/platforms/Poap/UploadMintLinksModal.tsx
  src/platforms/UniqueText/UniqueTextDataForm.tsx
Labels: improvement

#1227 fix(ClaimTokenModal): add labels for each button disabled state
  src/platforms/Token/ClaimTokenModal/ClaimTokenModal.tsx
Labels: improvement, bitesize

#1224 feat(InformationModal): info modal in dynamic reward setup
  public/img/dynamic_illustration.svg
  public/img/dynamic_illustration_light.svg
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddPointsPanel/components/SetPointsAmount/components/DynamicPointsAmountForm.tsx
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddPointsPanel/components/SetPointsAmount/components/PointsAmountTypeSelector.tsx
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/DynamicSetup/InformationModal.tsx
Labels: improvement

#1234 feat(Guild Pin & NFT reward): Cyber support
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddContractCallPanel/components/CreateNftForm/hooks/useCreateNft.ts
  src/pages/api/nft/collectors/[chain]/[address].ts
  src/utils/guildCheckout/constants.ts
Labels: bitesize
