Repository guildxyz/guild.xyz, pull requests merged in 2024-11, with the labels that each got.

#1536 feat: Ink Sepolia chain support
  package-lock.json
  package.json
  public/networkLogos/inkSepolia.png
  src/components/[guild]/Requirements/components/GuildCheckout/MintGuildPin/Fuel/hooks/constants.ts
  src/hooks/useTokens.ts
  src/static/customChains.ts
  src/wagmiConfig/chains.ts
  src/wagmiConfig/index.ts
Labels: feature

#1540 Change fuel token address input to asset id
  src/requirements/Fuel/components/FuelBalance.tsx
Labels: bitesize

#1541 fix: edit token reward modal improvements and fixes
  src/components/[guild]/RoleCard/components/RoleRewards.tsx
  src/rewards/Token/EditTokenModal.tsx
Labels: bug

#1542 feat(token reward): transfer pool ownership
  src/rewards/Token/ClaimTokenButton.tsx
  src/rewards/Token/EditTokenModal.tsx
  src/rewards/Token/TokenRewardCardEditMenu.tsx
  src/rewards/Token/TransferPoolOwnershipDialog.tsx
Labels: feature

#1544 feat: migrate TransactionStatusModal to Tailwind CSS & Radix UI
  playwright/04-nft-reward.spec.ts
  src/components/[guild]/Requirements/components/GuildCheckout/MintGuildPin/MintGuildPin.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/TransactionStatusContext.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/TransactionStatusModal/TransactionStatusModal.stories.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/TransactionStatusModal/TransactionStatusModal.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/TransactionStatusModal/components/TransactionLink.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/TransactionStatusModal/components/TransactionModalCloseButton.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/TransactionStatusModal/components/TxError.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/TransactionStatusModal/components/TxInProgress.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/TransactionStatusModal/components/TxSuccess.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/TransactionStatusModal/index.ts
  src/components/[guild]/Requirements/components/GuildCheckout/hooks/useMintGuildPin.tsx
  src/components/[guild]/collect/components/CollectNftContext.tsx
  src/components/[guild]/collect/hooks/useCollectNft.ts
  src/hooks/useSubmitTransaction.ts
Labels: improvement

#1549 feat: Dialog, Drawer and ResponsiveDialog components
  .storybook/main.ts
  .storybook/preview.tsx
  package-lock.json
  package.json
  src/app/components/ui/Dialog.tsx
  src/app/components/ui/Drawer.tsx
  src/app/components/ui/ResponsiveDialog.tsx
  src/app/components/ui/ScrollArea.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/stories/Button.stories.tsx
  src/stories/Dialog.stories.tsx
  src/stories/Drawer.stories.tsx
  src/stories/ResponsiveDialog.stories.tsx
  tailwind.config.ts
Labels: feature

#1551 feat: simple sign in flow
  .env
  .gitignore
  .husky/.gitignore
  package-lock.json
  package.json
  src/actions/auth.ts
  src/actions/me.ts
  src/app/explorer/components/GuildCard.tsx
  src/app/layout.tsx
  src/components/AuthBoundary.tsx
  src/components/Header.tsx
  src/components/Providers.tsx
  src/components/SignInButton.tsx
  src/components/SignInDialog.tsx
  src/components/SignOutButton.tsx
  src/components/ui/Badge.tsx
  src/components/ui/Button.tsx
  src/components/ui/Card.tsx
  src/components/ui/Dialog.tsx
  src/components/ui/Drawer.tsx
  src/components/ui/ResponsiveDialog.tsx
  src/components/ui/ScrollArea.tsx
  src/config/atoms.ts
  src/config/constants.ts
  src/config/wagmi.ts
  src/lib/env.ts
  src/lib/fonts.ts
  src/lib/shortenHex.ts
  src/stories/Badge.stories.tsx
  src/stories/Button.stories.tsx
  src/stories/Dialog.stories.tsx
  src/stories/Drawer.stories.tsx
  src/stories/ResponsiveDialog.stories.tsx
  src/styles/globals.css
  tsconfig.json
Labels: feature

#1553 feat: form related components
  .storybook/preview.tsx
  package-lock.json
  package.json
  src/components/ui/Checkbox.tsx
  src/components/ui/Collapsible.tsx
  src/components/ui/Dialog.tsx
  src/components/ui/Form.tsx
  src/components/ui/Input.tsx
  src/components/ui/Label.tsx
  src/components/ui/RadioGroup.tsx
  src/components/ui/Switch.tsx
  src/components/ui/Textarea.tsx
  src/stories/Checkbox.stories.tsx
  src/stories/Collapsible.stories.tsx
  src/stories/Form.stories.tsx
  src/stories/Input.stories.tsx
  src/stories/RadioGroup.stories.tsx
  src/stories/Switch.stories.tsx
  src/stories/Textarea.stories.tsx
  src/styles/globals.css
  tailwind.config.ts
  tsconfig.json
Labels: feature

#1559 feat: Toast component with Sonner
  package.json
  src/app/layout.tsx
  src/components/ui/Toaster.tsx
  src/stories/Toast.stories.tsx
Labels: feature

#1556 feat: create guild page
  guild.d.ts
  package.json
  src/actions/getPinataKey.ts
  src/app/[guild]/page.tsx
  src/app/create-guild/components/CreateGuildButton.tsx
  src/app/create-guild/components/CreateGuildForm.tsx
  src/app/create-guild/components/CreateGuildFormProvider.tsx
  src/app/create-guild/page.tsx
  src/app/explorer/components/GuildCard.tsx
  src/app/explorer/fetchers.ts
  src/app/explorer/page.tsx
  src/components/ConfettiProvider.tsx
  src/components/Header.tsx
  src/components/ImageUploader.tsx
  src/components/SignInButton.tsx
  src/components/SignOutButton.tsx
  src/components/ui/Toaster.tsx
  src/config/pinata.client.ts
  src/config/pinata.server.ts
  src/lib/env.ts
  src/lib/fetcher.ts
  src/lib/getCookie.ts
  src/lib/schemas/guild.ts
  src/lib/types.ts
  src/styles/globals.css
  tailwind.config.ts
Labels: feature

#1566 feat(SignInDialog): generate SIWE URL on the fly
  src/components/SignInDialog.tsx
Labels: improvement

#1567 feat: Guild, Role, RoleGroup schemas
  src/lib/schemas/common.ts
  src/lib/schemas/guild.ts
  src/lib/schemas/role.ts
  src/lib/schemas/roleGroup.ts
Labels: feature

#1568 feat: use Bun in the `code-check` GitHub Action
  .github/workflows/code-check.yml
  .husky/pre-commit
  README.md
  package.json
Labels: improvement

#1569 remove slugify and adjust guild creation to backend
  package.json
  src/app/(dashboard)/create-guild/components/CreateGuildButton.tsx
  src/app/(dashboard)/create-guild/components/CreateGuildFormProvider.tsx
  src/lib/schemas/guild.ts
Labels: bitesize

#1571 feat: requirement building blocks
  public/chainLogos/eth.svg
  src/components/Providers.tsx
  src/components/SignInDialog.tsx
  src/components/requirements/ChainIndicator.tsx
  src/components/requirements/DataBlock.tsx
  src/components/requirements/DataBlockWithCopy.tsx
  src/components/requirements/Requirement.tsx
  src/components/requirements/RequirementLink.tsx
  src/components/ui/Anchor.tsx
  src/components/ui/Badge.tsx
  src/components/ui/Button.tsx
  src/config/chains.ts
  src/stories/Anchor.stories.tsx
  src/stories/requirements/ChainIndicator.stories.tsx
  src/stories/requirements/DataBlock.stories.tsx
  src/stories/requirements/DataBlockWithCopy.stories.tsx
  src/stories/requirements/Requirement.stories.tsx
  src/stories/requirements/RequirementLink.stories.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: feature
