Repository guildxyz/guild.xyz, pull requests merged in 2024-04, with the labels that each got.

#1137 feat: flag deprecated chains
  src/components/common/Layout/components/Account/components/NetworkModal/NetworkButton.tsx
  src/components/common/Layout/components/Account/components/NetworkModal/NetworkButtonsList.tsx
  src/hooks/useSubmit/useSubmit.ts
  src/requirements/common/ChainPicker.tsx
  src/wagmiConfig/chains.ts
  src/wagmiConfig/index.ts
Labels: improvement

#1142 `useGuild` & `useRole` optimization
  src/components/[guild]/hooks/useGuild.ts
  src/components/[guild]/hooks/useRole.ts
Labels: improvement

#1138 feat: use the `/role/:roleId/requirements` endpoint
  src/components/[guild]/JoinModal/components/CompleteCaptchaJoinStep.tsx
  src/components/[guild]/JoinModal/components/ConnectPolygonIDJoinStep.tsx
  src/components/[guild]/Requirements/RoleRequirements.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/DynamicPurchaseRequirement.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/hooks/useMintGuildPin.tsx
  src/components/[guild]/Requirements/components/HiddenRequirementAccessIndicator.tsx
  src/components/[guild]/RoleCard/components/AccessIndicator/AccessIndicator.tsx
  src/components/[guild]/RoleCard/components/EditRole/EditRole.tsx
  src/components/[guild]/crm/RoleTags.tsx
  src/components/[guild]/hooks/useNonPurchasableAssets.ts
  src/components/[guild]/hooks/useRequirements.ts
  src/components/create-guild/Requirements/EditRequirements.tsx
  src/components/create-guild/Requirements/components/ExistingRequirementEditableCard.tsx
  src/components/create-guild/Requirements/components/LogicFormControl.tsx
  src/components/create-guild/Requirements/hooks/useCreateRequirement.ts
  src/components/create-guild/Requirements/hooks/useDeleteRequirement.ts
  src/components/create-guild/Requirements/hooks/useEditRequirement.ts
  src/requirements/Captcha/components/CompleteCaptcha.tsx
  src/requirements/Captcha/hooks/useVerifyCaptcha.ts
  src/types.ts
Labels: improvement

#1095 feat: farcaster accept urls too
  src/requirements/Farcaster/FarcasterRequirement.tsx
  src/requirements/Farcaster/components/FarcasterCast.tsx
  src/requirements/Farcaster/components/FarcasterCastHash.tsx
  src/requirements/Farcaster/components/FarcasterCastSmall.tsx
  src/requirements/Farcaster/components/FarcasterUser.tsx
  src/requirements/Farcaster/hooks/useFarcasterCast.ts
Labels: feature

#1147 feat: access check for chained roles
  src/components/[guild]/JoinModal/hooks/useActiveMembershipUpdate.tsx
  src/components/[guild]/JoinModal/utils/mapAccessJobState.ts
Labels: feature

#1148 feat: messaging rate limit alert
  src/components/[guild]/EditGuild/components/FeatureFlags.tsx
  src/components/[guild]/Tabs/GuildTabs.tsx
  src/components/[guild]/messages/SendNewMessage/SendNewMessage.tsx
  src/components/[guild]/messages/SendNewMessage/components/MessagingRateLimitAlert.tsx
  src/components/common/Layout/components/Account/components/Web3Inbox/Web3InboxMessage.tsx
Labels: feature

#1155 fix: use the v2 Lens API
  public/requirementLogos/lens.png
  public/requirementLogos/lens.svg
  src/components/[guild]/SocialIcon.tsx
  src/hooks/useResolveAddress.ts
  src/requirements/Lens/LensForm.tsx
  src/requirements/Lens/LensRequirement.tsx
  src/requirements/Lens/hooks/useLensProfile.ts
  src/requirements/Lens/hooks/useLensProfiles.ts
  src/requirements/requirements.ts
Labels: improvement

#1154 feat: change primary address
  src/components/common/Layout/components/Account/components/AccountModal/AccountModal.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/AccountConnections.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/LinkedAddress.tsx
  src/components/common/Layout/components/Account/components/AccountModal/hooks/useEditPrimaryAddress.ts
  src/types.ts
Labels: feature

#1156 fix(chainsOfAddressWithDeployedContract): save response in localstorage
  src/hooks/useSubmit/useSubmit.ts
Labels: improvement

#1157 refactor: simplify Delegate functionality
  src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx
  src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/components/DelegateCashButton.tsx
  src/components/common/Layout/components/Account/Account.tsx
  src/components/common/Layout/components/Account/components/AccountModal/AccountModal.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/LinkDelegateVaultButton.tsx
  src/components/common/Layout/components/Account/components/delegate/DelegatePopoverWrapper.tsx
  src/components/common/Layout/components/Account/components/delegate/useDelegateVaults.ts
Labels: improvement

#1149 [GUILD-2695] - Allowlist with IPFS file
  src/components/common/Button.tsx
  src/hooks/usePinata/usePinata.ts
  src/requirements/Allowlist/AllowlistRequirement.tsx
  src/requirements/Allowlist/components/AllowlistFormInputs.tsx
Labels: improvement

#1159 feat(Guild Pin & NFT reward): Linea support
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddContractCallPanel/components/CreateNftForm/CreateNftForm.tsx
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddContractCallPanel/components/CreateNftForm/hooks/useCreateNft.ts
  src/pages/api/nft/collectors/[chain]/[address].ts
  src/utils/guildCheckout/constants.ts
Labels: bitesize

#1162 fix(WalletSelectorModal): add a general injected wallet
  src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx
Labels: bug

#1164 refactor(guild/group): extract role list related logic
  src/components/[guild]/Requirements/RoleRequirements.tsx
  src/components/[guild]/Roles.tsx
  src/pages/[guild]/[group].tsx
  src/pages/[guild]/index.tsx
Labels: improvement

#1169 feat(useActiveMembershipUpdate): fallback to `requirementError`
  src/components/[guild]/JoinModal/hooks/useActiveMembershipUpdate.tsx
Labels: bug

#1171 feat: opBNB, X Layer mainnet, Form testnet, Metis Sepolia support
  public/explorerLogos/opbnb.png
  public/networkLogos/form.svg
  src/hooks/useTokens.ts
  src/static/customChains.ts
  src/wagmiConfig/chains.ts
  src/wagmiConfig/index.ts
Labels: feature

#1172 feat: upgrade lens requirements & add new ones
  src/requirements/Lens/LensForm.tsx
  src/requirements/Lens/LensRequirement.tsx
  src/requirements/Lens/components/LensAction.tsx
  src/requirements/Lens/components/LensPostInput.tsx
  src/requirements/Lens/components/LensProfileSelect.tsx
  src/requirements/Lens/components/LensReact.tsx
  src/requirements/Lens/components/LensTotalInput.tsx
  src/requirements/Lens/hooks/useLensProfile.ts
  src/requirements/Lens/hooks/useLensProfiles.ts
  src/requirements/requirements.ts
Labels: feature, improvement

#1179 feat(useServerData): remove `categories` & simplify hook
  src/hooks/useServerData.ts
Labels: bitesize

#1182 feat: rework the Collect NFT page
  src/components/[guild]/Requirements/RoleRequirements.tsx
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddContractCallPanel/components/CreateNftForm/hooks/useCreateNft.ts
  src/components/[guild]/collect/components/RequirementsCard.tsx
  src/components/[guild]/collect/hooks/useNftDetails.ts
  src/hooks/useUsersGuildPins.ts
  src/pages/[guild]/collect/[chain]/[address].tsx
  src/pages/_error.tsx
  src/pages/api/nft/[chain]/[address].ts
  src/pages/api/nft/collectors/[chain]/[address].ts
  src/types.ts
  src/utils/ipfsToGuildGateway.ts
  src/wagmiConfig/index.ts
Labels: improvement

#1187 fix(authenticated pages): don't fallback to 404 unintentionally
  src/components/[guild]/hooks/useGuild.ts
  src/pages/[guild]/analytics.tsx
  src/pages/[guild]/forms/[formId]/responses.tsx
  src/pages/[guild]/members.tsx
Labels: bug
