Repository guildxyz/guild.xyz, pull requests merged in 2024-03, with the labels that each got.

#1098 feat: blast mainnet support
  src/chains.ts
  src/hooks/useTokens.ts
  src/static/customChains.ts
Labels: feature

#1107 feat: warning copy for twitter requirements due to api limitations
  src/requirements/Twitter/TwitterForm.tsx
  src/requirements/Twitter/components/TwitterAccountAge.tsx
  src/requirements/Twitter/components/TwitterUserInput.tsx
Labels: improvement, bitesize

#1091 fix: dont auto prepend guildxyz to links in secret rewards
  src/components/[guild]/collect/components/RichTextDescription.tsx
  src/components/lexical/plugins/ToolbarPlugin/components/LinkEditor.tsx
  src/platforms/SecretText/hooks/useClaimText.tsx
  src/utils/ensureUrlProtocol.ts
Labels: bitesize

#1099 feat: gather town space as reward
  public/platforms/gather.png
  src/components/[guild]/JoinModal/JoinModal.tsx
  src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddGatherPanel.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/AccountConnections.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/SocialAccount/EmailAddress.tsx
  src/components/create-guild/MultiPlatformGrid/components/MultiPlatformSelectButton.tsx
  src/components/create-guild/PlatformsGrid/PlatformsGrid.tsx
  src/pages/api/gather.ts
  src/platforms/Gather/ClaimGatherModal.tsx
  src/platforms/Gather/EditGatherModal.tsx
  src/platforms/Gather/GatherCardButton.tsx
  src/platforms/Gather/GatherCardMenu.tsx
  src/platforms/Gather/GatherConnectionForm.tsx
  src/platforms/Gather/GatherConnectionStatusAlert.tsx
  src/platforms/Gather/GatherForm.tsx
  src/platforms/Gather/GatherGuestForm.tsx
  src/platforms/Gather/hooks/useClaimGather.tsx
  src/platforms/Gather/hooks/useGatherAccess.tsx
  src/platforms/Gather/useGatherCardProps.tsx
  src/platforms/components/GatherPreview.tsx
  src/platforms/components/GatherReward.tsx
  src/platforms/platforms.tsx
  src/theme/colors.ts
  src/types.ts
Labels: feature

#1108 feat: PolygonID QR code auth
  src/platforms/PolygonID/components/ConnectDIDModal.tsx
Labels: improvement

#1110 fix: set new visibilityRoleId on save
  src/components/[guild]/RoleCard/components/EditRole/EditRole.tsx
  src/components/[guild]/SetVisibility/components/PrivateVisibilityOptions.tsx
  src/components/[guild]/SetVisibility/index.ts
Labels: bug, bitesize

#1115 `platforms.tsx` refactor & cleanup
  src/components/[guild]/AccessHub/components/RemovePlatformMenuItem.tsx
  src/components/[guild]/EditGuild/components/DeleteGuildButton/DeleteGuildButton.tsx
  src/components/[guild]/JoinModal/JoinModal.tsx
  src/components/[guild]/RemovePlatformAlert.tsx
  src/components/[guild]/RoleCard/components/EditRole/components/DeleteRoleButton/DeleteRoleButton.tsx
  src/components/[guild]/RolePlatforms/RolePlatforms.tsx
  src/components/[guild]/RolePlatforms/components/RemovePlatformButton/RemovePlatformButton.tsx
  src/components/[guild]/ShouldKeepPlatformAccesses.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/AccountConnections.tsx
  src/components/create-guild/Requirements/components/ConfirmationAlert.tsx
  src/components/create-guild/Requirements/components/ExistingRequirementEditableCard.tsx
  src/platforms/platforms.tsx
Labels: improvement

#1122 feat(useEditGuild): display error messages from our backend
  src/components/[guild]/EditGuild/hooks/useEditGuild.ts
Labels: improvement

#1131 fix(access check): check for falsy value instead of `null`
  src/components/[guild]/Requirements/components/HiddenRequirementAccessIndicator.tsx
  src/components/[guild]/RoleCard/components/AccessIndicator/AccessIndicator.tsx
Labels: improvement, bitesize

#1127 fix: scroll restoration in guild explorer
  src/components/common/Layout/components/NavMenu/NavMenu.tsx
  src/components/explorer/hooks/useScrollRestoration.ts
  src/pages/explorer.tsx
Labels: bug, bitesize

#1129 Twitter v1 cleanup + enable
  src/components/[guild]/JoinModal/components/ConnectPlatform.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/AccountConnections.tsx
  src/components/common/Layout/components/Account/components/AccountModal/components/SocialAccount/SocialAccount.tsx
  src/pages/api/twitter-request-token.ts
  src/platforms/rewards.tsx
Labels: bitesize

#1134 refactor: remove deprecated `/guilds` mutations & improve the existing ones
  next-env.d.ts
  src/components/[guild]/EditGuild/components/DeleteGuildButton/hooks/useDeleteGuild.ts
  src/components/[guild]/EditGuild/hooks/useEditGuild.ts
  src/components/[guild]/LeaveButton/hooks/useLeaveGuild.ts
  src/components/[guild]/RoleCard/components/EditRole/components/DeleteRoleButton/hooks/useDeleteRole.ts
  src/components/[guild]/RoleCard/components/EditRole/hooks/useEditRole.ts
  src/components/[guild]/crm/FilterByRoles/components/useCreateHiddenRole.tsx
  src/components/common/Layout/components/Account/components/AccountModal/hooks/useDisconnect.ts
  src/components/create-guild/hooks/useCreateGuild.tsx
  src/components/create-guild/hooks/useCreateRole.tsx
  src/components/explorer/YourGuilds.tsx
  src/hooks/useMatchMutate.ts
  src/hooks/useSWRWithOptionalAuth.ts
  src/platforms/Discord/DiscordCardMenu/DiscordCardMenu.tsx
  src/platforms/Discord/DiscordCardMenu/hooks/useSyncMembersFromDiscord.ts
  src/types.ts
Labels: improvement

#1130 feat(NFT requirement): allow multiple IDs
  src/requirements/Allowlist/AllowlistRequirement.tsx
  src/requirements/Nft/NftForm.tsx
  src/requirements/Nft/NftRequirement.tsx
  src/requirements/Nft/components/UploadIDs.tsx
  src/requirements/common/SearchableVirtualListModal.tsx
  src/types.ts
  src/utils/mapRequirement.ts
  src/utils/preprocessRequirement.ts
Labels: feature

#1135 [GUILD-2561] - Email allowlist
  next-env.d.ts
  package-lock.json
  package.json
  src/components/[guild]/Requirements/components/RequirementAccessIndicator.tsx
  src/requirements/Allowlist/AllowlistForm.tsx
  src/requirements/Allowlist/AllowlistRequirement.tsx
  src/requirements/requirements.ts
Labels: feature

#1136 feat: lazy load Intercom with facade
  package-lock.json
  package.json
  public/intercom.js
  src/components/[guild]/ReportGuildButton.tsx
  src/components/[guild]/Requirements/components/GuildCheckout/components/AlphaTag.tsx
  src/components/[guild]/Tabs/GuildTabs.tsx
  src/components/_app/IntercomProvider.tsx
  src/pages/[guild]/index.tsx
  src/pages/_app.tsx
  src/pages/_error.tsx
Labels: improvement

#1141 fix(join flow): join guild with hidden roles
  src/components/[guild]/JoinModal/hooks/useJoin.tsx
  src/components/[guild]/JoinModal/utils/mapAccessJobState.ts
Labels: bug

#1139 feat: ZetaChain, Astar zkEVM, Core Dao, Lisk Sepolia support
  public/networkLogos/astar-zkevm.png
  public/networkLogos/coredao.png
  public/networkLogos/lisk.svg
  src/hooks/useTokens.ts
  src/requirements/WalletActivity/WalletActivityForm.tsx
  src/wagmiConfig/chains.ts
  src/wagmiConfig/index.ts
Labels: feature
